### ISSUE TITLE
[9.5.6] Tools are visible without permission (personal)

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#10003]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Unable to define permissions to 'Personal reminders' and 'Personal RSS feed'

### Page URL

front/central.php

### Steps To reproduce

1. Create a new profile.
2. Don't add any permissions.
3. Create a new 'Authorizations assignment rules' for "test" user and assign it to profile  from step 1.
4. Log in as a "test" user.
5. Tools are available (personal reminders and rss feed).

### Anything else?

I know these are personal not public settings, but the administrator should still be able to disable access to this functionality.

**Comment by cconard96** [comment]
Is the new profile using Standard or Simplified interface?

**Comment by joomlafun** [comment]
The permission is meant for public reminders and public rss feed.

The menus visible are for personal reminder and personal rss feed so it is kind of normal that it is visible

**Comment by cconard96** [comment]
Personal RSS Feeds and Personal Reminders are available for all users and are not locked behind a permission. Having the ability to remove them for certain users would involve adding new rights. Only the public RSS feeds and reminders have permissions.

Since this is related to a new feature, please open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).
