### ISSUE TITLE
Users Picture Ratio change when importing from LDAP backend

### ISSUE THREAD

**Issue by roumano** [glpi-project/glpi#10054]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.5

### Bug description

If use `Authentification` / `LDAP directories` with **Picture** get on the LDAP for user

- Glpi download successfully images but change the ratio.
As exemple, we have only User pictures with `120*160 px`.
But GLPI transform them to 71*71 px.

So the ratio is change and mean the picture is distorter (enlarge) so it's not very beautiful.

### Steps To reproduce

1. Install and configure a LDAP server
2. Create a account in the LDAP with a picture on the field jpegPhoto with a ratio different of 1
3. Configure GLPI as LDAP client with `Authentication` / `LDAP directories`
4. Don't forget to add Users : Picture : jpegphoto on the LDAP backend
5. In the User : Actions / Force synchronization to force download of the lastest picture of the user
6. The image ration is not good

**Comment by roumano** [comment]
still can reproduce the issue on the last stable version

**Comment by roumano** [comment]
still can reproduce the issue on the last stable version

**Comment by cconard96** [comment]
@roumano

The images you are seeing are the generated thumbnails which are currently using default values which would force the thumbnail to be 71x71 without maintaining aspect ratio.

For GLPI 9.5.7, can you try:
1. Changing https://github.com/glpi-project/glpi/blob/e9b16bc8e9b61ebb2d35b96b9c71cd25c5af9e48/inc/user.class.php#L1219 to be `Toolbox::resizePicture($file, $thumb, 71, 71, 0, 0, 0, 0, 71);`
2. Removing or changing the current picture for an LDAP user in GLPI (The image won't re-sync and have the thumbnail regenerated since the source image is the same)
3. Sync the user with LDAP in the Syncronization tab for the user

The replacement code would generate a thumbnail where the max size is 71px. If the height or width is larger, it will shrink it and maintain the aspect ratio. If both the height and width are smaller, then the image will remain the same size.

I'm not entirely sure how well the user pictures will be displayed throughout GLPI if certain things were made expecting the images to always be 71x71.

**Comment by roumano** [comment]
Hi,
I just tested this recommnendation and it's partially work's : 
- If i open the picture on a new browser tab ( only the picture, like this url link : https://glpi.XXXXX/front/document.send.php?file=_pictures/8c/395_YYYYY_min.jpg , the ratio is good )
- But the ratio of the picture inside GLPI ( like in ticket system https://glpi.XXXXX/front/ticket.form.php?id=YYY , or in user https://glpi.XXXXX/front/user.form.php?id=YYY is still not good )

**Comment by roumano** [comment]
the issue still exisr

**Comment by cedric-anne** [comment]
Fixed by #13798 in GLPI 10.0.6.
