### ISSUE TITLE
GLPI 10 - Can not add new user 

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#10134]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10 Beta

### Bug description

Hi,

The user add tab shows only following information

![image](https://user-images.githubusercontent.com/22425503/146315159-168d3371-9e18-42a3-8b06-f0e2c528c9f4.png)

![image](https://user-images.githubusercontent.com/22425503/146315296-b0a98664-7bee-469f-8ff6-fc07cbfe5840.png)

**Comment by ZeikoFr** [comment]
Hi,

What's your php version ?

Can you give more info about the installation (you have fields in the issue template to put them)

**Comment by roshanroche** [comment]
Hi,

PHP 8.0.13 

Operating system: Linux 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64
PHP 8.0.13 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, mysql,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader,
	xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.37 (centos) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.4.12-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.0.13) is supported.PHP version (8.0.13) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.4.12) is supported.Database engine version (10.4.12) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by mrajema** [comment]
I have the same problem, I use Online test beta

**Comment by tomolimo** [comment]
Hello,

Same issue for this on-prem configuration:

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0-dev ( => L:\inetpub\wwwroot\glpi10.0-official)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT ARGLPIT20 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
PHP 7.4.21 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, readline, session, soap, sodium, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="1G" post_max_size="80M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Microsoft-IIS/8.5
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.34-log
	Server SQL Mode: STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi10@127.0.0.1/glpi10.0official
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (7.4.21) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (5.7.34) is supported.
The log file has been created successfully.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_cache has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/config has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_cron has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_dumps has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_graphs has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_lock has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_pictures has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_plugins has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_rss has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_sessions has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_tmp has been validated.
Write access to L:\inetpub\wwwroot\glpi10.0-official/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to L:\inetpub\wwwroot\glpi10.0-official/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: L:\inetpub\wwwroot\glpi10.0-official
GLPI_CONFIG_DIR: L:\inetpub\wwwroot\glpi10.0-official/config
GLPI_VAR_DIR: L:\inetpub\wwwroot\glpi10.0-official/files
GLPI_MARKETPLACE_DIR: L:\inetpub\wwwroot\glpi10.0-official/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_DOC_DIR: L:\inetpub\wwwroot\glpi10.0-official/files
GLPI_CACHE_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_cache
GLPI_CRON_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_cron
GLPI_DUMP_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_dumps
GLPI_GRAPH_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_graphs
GLPI_LOCAL_I18N_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_locales
GLPI_LOCK_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_lock
GLPI_LOG_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_log
GLPI_PICTURE_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_pictures
GLPI_PLUGIN_DOC_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_plugins
GLPI_RSS_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_rss
GLPI_SESSION_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_sessions
GLPI_TMP_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_tmp
GLPI_UPLOAD_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_uploads
GLPI_INVENTORY_DIR: L:\inetpub\wwwroot\glpi10.0-official/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: L:\inetpub\wwwroot\glpi10.0-official/locales
GLPI_VERSION: 10.0.0-dev
GLPI_SCHEMA_VERSION: 10.0.0-dev@5d5ed159d30f08ffa4fb9065d7c3f64855d5d4e1
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_YEAR: 2021

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (L:\inetpub\wwwroot\glpi10.0-official\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.5.3 in (L:\inetpub\wwwroot\glpi10.0-official\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.6 in (L:\inetpub\wwwroot\glpi10.0-official\vendor\simplepie\simplepie\library)
mpdf/mpdf in (L:\inetpub\wwwroot\glpi10.0-official\vendor\mpdf\mpdf\src)
michelf/php-markdown in (L:\inetpub\wwwroot\glpi10.0-official\vendor\michelf\php-markdown\Michelf)
true/punycode in (L:\inetpub\wwwroot\glpi10.0-official\vendor\true\punycode\src)
iamcal/lib_autolink in (L:\inetpub\wwwroot\glpi10.0-official\vendor\iamcal\lib_autolink)
sabre/dav in (L:\inetpub\wwwroot\glpi10.0-official\vendor\sabre\dav\lib\DAV)
sabre/http in (L:\inetpub\wwwroot\glpi10.0-official\vendor\sabre\http\lib)
sabre/uri in (L:\inetpub\wwwroot\glpi10.0-official\vendor\sabre\uri\lib)
sabre/vobject in (L:\inetpub\wwwroot\glpi10.0-official\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (L:\inetpub\wwwroot\glpi10.0-official\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (L:\inetpub\wwwroot\glpi10.0-official\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (L:\inetpub\wwwroot\glpi10.0-official\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (L:\inetpub\wwwroot\glpi10.0-official\vendor\sebastian\diff\src)
elvanto/litemoji in (L:\inetpub\wwwroot\glpi10.0-official\vendor\elvanto\litemoji\src)
symfony/console in (L:\inetpub\wwwroot\glpi10.0-official\vendor\symfony\console)
scssphp/scssphp in (L:\inetpub\wwwroot\glpi10.0-official\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (L:\inetpub\wwwroot\glpi10.0-official\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (L:\inetpub\wwwroot\glpi10.0-official\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (L:\inetpub\wwwroot\glpi10.0-official\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (L:\inetpub\wwwroot\glpi10.0-official\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (L:\inetpub\wwwroot\glpi10.0-official\vendor\ramsey\uuid\src)
psr/log in (L:\inetpub\wwwroot\glpi10.0-official\vendor\psr\log\Psr\Log)
psr/simple-cache in (L:\inetpub\wwwroot\glpi10.0-official\vendor\psr\simple-cache\src)
psr/cache in (L:\inetpub\wwwroot\glpi10.0-official\vendor\psr\cache\src)
league/csv in (L:\inetpub\wwwroot\glpi10.0-official\vendor\league\csv\src)
mexitek/phpcolors in (L:\inetpub\wwwroot\glpi10.0-official\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (L:\inetpub\wwwroot\glpi10.0-official\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (L:\inetpub\wwwroot\glpi10.0-official\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (L:\inetpub\wwwroot\glpi10.0-official\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (L:\inetpub\wwwroot\glpi10.0-official\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (L:\inetpub\wwwroot\glpi10.0-official\vendor\paragonie\sodium_compat\src)
symfony/cache in (L:\inetpub\wwwroot\glpi10.0-official\vendor\symfony\cache)
html2text/html2text in (L:\inetpub\wwwroot\glpi10.0-official\vendor\html2text\html2text\src)
symfony/dom-crawler in (L:\inetpub\wwwroot\glpi10.0-official\vendor\symfony\dom-crawler)
twig/twig in (L:\inetpub\wwwroot\glpi10.0-official\vendor\twig\twig\src)
twig/string-extra in (L:\inetpub\wwwroot\glpi10.0-official\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (L:\inetpub\wwwroot\glpi10.0-official\vendor\symfony\polyfill-php80)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

Thank you,
Regards,
Tomolimo

**Comment by 99net** [comment]
same on 7.4

**Comment by 99net** [comment]
![image](https://user-images.githubusercontent.com/43380069/146348109-42b2e8a7-23ec-4830-9da1-d3ed33366510.png)

**Comment by cconard96** [comment]
To clarify, you see this for the form to create a user and not what you see for the newly created user correct?

**Comment by 99net** [comment]
It appears while you try to create new user.

**Comment by cconard96** [comment]
My original PR had the check in the personal form instead of the regular user form by accident. Does this work any better?
https://github.com/cconard96/glpi/commit/7ecf5f213da793ba52df899d00a49671361f4d2e

**Comment by 99net** [comment]
Same as before.

**Comment by orthagh** [comment]
Hello

Please check #10151 fix

**Comment by 99net** [comment]
Well done. Thx.

**Comment by tomolimo** [comment]
Thank you @orthagh

**Comment by LucianoFred** [comment]
Thank you @orthagh . It work!
