### ISSUE TITLE
Prevent sql issues using unsigned int

### ISSUE THREAD

**Issue by CorentinS6** [glpi-project/glpi#10262]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

9.5.6

### Bug description

Hello,

To prevent issues like https://github.com/yllen/behaviors/issues/4 , it would be good to use **unsigned (big)int** with mysql PK.

Its seems also a best practice to use unsigned int for primary key ? May be use a bigint is also an option ?

Regards.

**Comment by trasher** [comment]
We've talked about that in a meeting this morning; using a bigint does not seems a good option, we will work on a script to switch to unsigned integers on primary and foreign keys.

**Comment by wellington1993** [comment]
Maybe add ways to change ticket format, removing the date from the string could be help too.
I can't find easy way to do that, and the alternative ways can be lost in config files updates after  glpi versions change.

Thanks!

**Comment by orthagh** [comment]
> I can't find easy way to do that, and the alternative ways can be lost in config files updates after glpi versions change.

I think there are not easy options for that as you may want to parse all tables referencing old ticket's id.

By the way, changing the column to unsigned should permits the behaviors plugin option to year 2044 at least, so i guess it's ok for the original issue in a short term sight.

For future, we will work on a way to customize displayed id in GLPI core.
In database they will be stored with incremented integers (unsigned) as usual but we will store in another field (varchar probably) the formated id.

**Comment by arthurrschaefer** [comment]
I'm sorry if I'm being a fool, asking you this.

Could this limitation affect also the glpi_logs IDs?
Because this field, in a regular environment even without behaviors format, tends to receive a lot of IDs. More IDs than the tickets or changes themselves. And could also bring some problems in the future in my humble point of view.

I know. 2 billion, 147 million are a lot of IDs, furthermore we have ways to erase some tickets and/or logs even though the IDs are always sequential and never restart. But just thinking, mainly because I'm not a databases expert.

I'm just brainstorming. But I guess it's a great move to think about the future of the tables IDs.

**Comment by trasher** [comment]
> Could this limitation affect also the glpi_logs IDs?

This limitation affects all signed integers used in the database inluding all `id` fields (most of them are simple auto-increments) and their corresponding foreign keys.
Until now, the behavior plugin possibility to change the id (not a good idea IMHO) is the only way that issue has appeared.

The proposed change will fix behavior plugin issue until 2044 only, but for standard cases, it double the limit: it should be enough for some time.

If someone reach one day the new limit on `glpi_logs.id` field, a specific fix would be possible (because id of the logs really does not matters).

If that limit is reached on another field like `glpi_tickets.id`... Well, we'll have to investigate ;o)

**Comment by orthagh** [comment]
> Could this limitation affect also the glpi_logs IDs?

To precise also the limitations and the choice of changing to unsigned and not to bigint:

The last will take a lot more space on disk (as we need to change format of id but also all foreign keys) and apart with behavior formatting, we though it was very unlikely to have a classic id in glpi superior to the limitation of a classic integer.

We considered also the case of glpi_logs, i saw very large database during my work experience with glpi but nothing overloading 4 billion rows. It's would take more than 600 Go of data on disk
I can imagine an instance like that (never saw one by the way, the most i saw was 600 millions rows and it was a buggy and very problematic instance)  but a lot of problems will occur with this size of glpi_logs (like upgrading, backup, replication).
A normal instance (without bugs) should never have this kind of id.

But if you ever encounter the case, the fix is more easy than the one we facing currently, you can change on this particular instance the id of glpi_logs to bigint. There is no foreign key in glpi core referencing glpi_logs.id.

**Comment by orthagh** [comment]
internal ref : !21687

**Comment by cedric-anne** [comment]
In 9.5.7 version of GLPI, a command (`php bin/console glpi:migration:unsigned_keys`) has been introduced to migrate some primary/foreign keys to unsigned integers, see #10263.

For GLPI 10.0, some additionnal changes have been made in order to migrate all primary/foreign keys to unsigned integers, and to encourage people to do this migration.

So I close this issue as all that can be done on GLPI core has been done.
