### ISSUE TITLE
[GLPI 10.0 RC1] : On the main page, the backup search button (star) no longer exists on the GLPI 10 version (version 9.5.7 its ok)

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10689]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 RC1

### Bug description

On version 9.5.7, there was the backup search button on the main page but on the GLPI 10 version, the button does not exist

For the list button to appear, click on park and any tab.

9.5.7
![image](https://user-images.githubusercontent.com/68054991/154440720-0c3a5541-1d53-4e82-acd6-583d797563c9.png)
![image](https://user-images.githubusercontent.com/68054991/154446154-03a30c05-3e2b-4c50-8adf-aa3d612a9f97.png)

10.0 RC1 nothing
![image](https://user-images.githubusercontent.com/68054991/154440960-ac6139c5-1807-42fd-8dc7-472fdaf88739.png)
 
The button "listes" appear here and no on the main page
![image](https://user-images.githubusercontent.com/68054991/154441238-d19bfedb-461d-404c-9055-6d11dc21077c.png)

**Comment by cconard96** [comment]
This appears to be intentional as saved searches are now segmented by the different item types and the button was moved from the global top bar to the extra options that show depending on which item type you are looking at. For example, when on the Computers search page you will see this button and the Computer saved searches will show by default.

**Comment by steph461** [comment]
ok it's really good this way, I had not seen it this way
