### ISSUE TITLE
Bug: CSS with IE10-11 and Edge GLPI v0.90.1, v0.90.5, v0.91  (Contains the correction)

### ISSUE THREAD

**Issue by titio04** [glpi-project/glpi#1075]
Hi,

The CSS is not correctly displayed with IE11 and Edge.
Same problem when i run the install interface.
Important: it's not possible to tick the checkbox (In particular for the database and for to accept licences) with  the first install or with the upgrade.

Please and this code on the page index.php  for a compatibility with IE, just after the ligne: 
`echo '<meta http-equiv="Content-Script-Type" content="text/javascript"/>'."\n";`

Insert this code:
`echo '<meta http-equiv="X-UA-Compatible" content="IE=edge" >';`

Best Regards

**Comment by trasher** [comment]
I do not have any IE nor Edge installed, can someone confirm this issue?

**Comment by tomolimo** [comment]
I don't have IE11 nor Edge either, but just IE10...

**Comment by titio04** [comment]
Hello,

I confirm the problem. 

Sometimes IE don't detect correctly the website when the compatibility mode of IE is activated.
All the CSS is impacted.

See these issues on the GLPI-project github :
- 0.90/ie8 compat #1010
- GLPI image on logon page internet explorer 11 #975
- GLPI 0.9.0.5 retrocompatibility issue with IE8 :: proposed fixes #920

This meta is not for the "Edge" navigator, and exist between a long time.
It just force IE (version IE 7, 8, 9, 10, 11) to use the most reçent compatibility mode.

See this article (in french):
http://www.alsacreations.com/astuce/lire/1437-comment-interdire-le-mode-de-compatibilite-sur-ie.html
https://msdn.microsoft.com/fr-fr/library/cc817574.aspx

this problem impact only the version before IE11 release 11.0.9600.18341 (same problem with IE 10, IE 9, and IE8). 

With IE11 release version 11.0.9600.18341, the bug was solved by Microsoft.


Best Regards,

**Comment by trasher** [comment]
Hum... Another round on IE specific issues... :D

Well, blocking compatibility mode will prevent developers to test on any other IE version than the one installed; so I'm not completely convinced :-/

Also, reading https://n.survol.fr/n/x-ua-compatible-ieedge let me think this is not a good solution; we are not ion any of the cases where this meta is really required.

As far as I can remember, I already see this kind of comportment because of a page that was not HTML standard compliant; and therefore make IE switch to any compatibility mode.
If that issue can be solved fixing standards, it would be far better.

As for IE8, it is no longer supported; while we won't refuse PR that would make a better compatibility, th main developers won't work on it (see #1010 for example - that still need some work)..

**Comment by trasher** [comment]
Saying that, I've just seen that we have this meta tag in the `inc/html.class.php` already... Since 2014.
