### ISSUE TITLE
Automatically expand/collapse submenus by hovering over the navigation bar

### ISSUE THREAD

**Issue by KongNan** [glpi-project/glpi#10865]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

In previous versions, I could expand a submenu by hovering over the main menu item in the navigation bar, and when I moved the mouse over another main menu item, another submenu would be expanded and the previous submenu would disappear.

In Glpi10, the default PageLayout is set to display the menu in the sidebar, but it doesn't have the above feature, and it even results in the inconvenience of not being able to quickly switch to the main menu item below when expanding the main menu item above because the vertical space is occupied by its submenu (you need to collapse that main menu item or scroll the mouse first); and even if you change the PageLayout back to display the menu bar in the header, you can't get back the auto expand/collapse feature in the previous version.

### Anything else?

I'm not sure if I should post it in the bug section, but the description of the feature request is "Suggest a new feature to the GLPI team", so apparently it's not a new feature either ...... Sorry for my bad English.

**Comment by cconard96** [comment]
In previous versions of GLPI, it was *required* to have hover-to-expand functionality because the top-level menu options were links that would navigate to the default/first option in their submenu so you had no other way to see all the sub-menu options. In GLPI 10, you can click the top-level options without navigating away to another page.

It may be something that can get re-added by a plugin, but I don't know if it is wanted to re-add this functionality globally. Hover-to-expand on its own isn't really mobile friendly. If the menu automatically collapses when the mouse is no longer hovering over the top-level or sub-items it could reduce accessibility (users with tremors for example) and would require additional consideration to delay the closing of the menu (and then cancel the collapse if the mouse re-enters the area within that time).

**Comment by KongNan** [comment]
If constrained, I recommend at least using the classic menu layout when setting the PageLayout to display the menu bar in the header, perhaps this will be able to reuse the previous code and facilitate a little. (sorry for my English)

**Comment by KongNan** [comment]
I eventually found that the popup menu disappears automatically by collapsing the sidebar, thus avoiding redundant clicks (when I forget the specific menu and need to browse it one by one to find it).

Now that this issue is basically useless, I will close it.

Of course, in this way, it is better for the user to remember the main menu icon more clearly.
