### ISSUE TITLE
[GLPI 10.0.0-rc3] Pending reason workflow broken

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#11231]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc3

### Bug description

1. Returning to working status by adding follow up seems to be broken in GLPI10
When ticket was put into "Pending" status in 9.x and Requester provided follow-up, status was changed to working state automatically.
With version 10 adding follow-up by requester does not change the status.

2. Now with GLPI10 it is possible to define pending reason per follow up with different reasons. So one Ticket can have multiple pending follow-ups.
Follow-ups added by requester does not affect existing pending status of other follow-ups in tickets.
Only way seems like when Technician manually edits his follow up and "Saves" it again or "Deletes Permanently".

If this is intention I am ok with that, but I did not see that documented anywhere and could not get through the new code yet. 
I just set my expectations based on PR https://github.com/glpi-project/glpi/pull/8706

### Steps To reproduce

1, Crete ticket as post-only
2. As tech update ticket, add follow-up with pending reason
3. As post-only add follow-up
4. Check ticket status

### Your GLPI setup information

10.0.0-rc3

**Comment by eric95630** [comment]
I have the same issue with the final version of GLPI...

**Comment by AdrienClairembault** [comment]
Issue 1 is known and will be fixed in the 10.0.1 release (scheduled for this week).

Regarding your second issue, if I understand correctly you have the following situation where:
- A pending reason was added with a followup
- The requester added a followup and the ticket is no longer pending
- The pending reason is still displayed in the timeline

![image](https://user-images.githubusercontent.com/42734840/171169701-38798a8a-d611-4e04-8f75-428035f2f357.png)

The goal is to keep a visual track of the different pending reasons that were applied to the ticket.

If I understand correctly, you would have preferred for these pending reasons to be removed from the timeline once they are no longer affecting the ticket ?

**Comment by VladoTTX** [comment]
Thanks for the feedback.
Issue 1. Do you have PR# which contains the fix please?
Issue 2. I just wanted to know the workflow behind. As it looked like Pending to Working status was automatically set just in case Follow-up with Pending reason was edited and saved again (so Pending reason removed). 
If it is intention to have it visualized, I am fine with reply.

**Comment by AdrienClairembault** [comment]
> Issue 1. Do you have PR# which contains the fix please?

I think it should be this one: https://github.com/glpi-project/glpi/pull/11327.
Note that the `10.0.1` version was just released so you should probably use it instead of patching this issue.

> Issue 2. I just wanted to know the workflow behind. As it looked like Pending to Working status was automatically set just in case Follow-up with Pending reason was edited and saved again (so Pending reason removed).
If it is intention to have it visualized, I am fine with reply.

The intention is indeed to have it visualized.

**Comment by Joselitossss** [comment]
Good

I have installed the final version (10.0.2) and I have beem triying that my technicians cannot put a ticket as a pending but the answer button does not allow me to disable the "Set ticket as pending" box, which regardless of the restrictions that I put on them on the technician profile its just allows them to put it on hold
