### ISSUE TITLE
[GLPIP 10.R3] : Network sockets are no longer displayed in the preview

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#11258]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.x

### Bug description

Network sockets are no longer displayed in the preview

They are well displayed on the information of the network cards

examples version 9.5.7 and 10.X :

**1 . **computer.php or glpi/front/phone.php****

9.5.7 : glpi/front/computer.php or glpi/front/phone.php OK
![image](https://user-images.githubusercontent.com/68054991/162703643-8d3bad40-2a07-4966-9bc4-ddb6aa5d83d4.png)

10.x : glpi10beta/front/computer.php or glpi/front/phone.php KO
![image](https://user-images.githubusercontent.com/68054991/162703860-a2f378bb-fd25-4714-8f13-89782c35a9e7.png)

2. networkequipment.form.php

9.5.7 glpi/front/networkequipment.form.php OK
![image](https://user-images.githubusercontent.com/68054991/162704650-a82893c6-aae6-43b4-8ae6-bc5e66b1ebc8.png)

10.0 : glpi/front/networkequipment.form.php column doesnt exist KO
![image](https://user-images.githubusercontent.com/68054991/162705327-3b79044b-bf09-472b-8f11-2a715032567f.png)

### Relevant log output

```shell
no log
```

**Comment by steph461** [comment]
in the networks controller, its ok in glpi 10
![image](https://user-images.githubusercontent.com/68054991/162708777-8af89807-74c3-40b6-ae22-0494c8caa2a2.png)

**Comment by steph461** [comment]
Yes same issue glpi 10.0.1 fix 20220524

other similar problem :

Computer (networkport.form.php)
Port Ethernet and connecteur reseau doesnt exist
![image](https://user-images.githubusercontent.com/68054991/170205546-a81e21b2-72b9-44c4-9fc6-43d0ba071960.png)


phone and networkequipment (networkport.form.php)
Port Ethernet and connecteur reseau exist
![image](https://user-images.githubusercontent.com/68054991/170205120-83ef9410-fe1f-4034-9d6a-a256421999ef.png)

**Comment by cconard96** [comment]
For ports that do not have the "Port Ethernet" section in the form, how were they created?
It looks like the instantiation information (Ethernet, WiFi, Aggregation, etc) wasn't added when the port was added so the search option does not apply.

For the search option to work, the ports need the Ethernet type instantiation and there needs to be a Socket linked to the port.

**Comment by WebGregGit** [comment]
Hi @cconard96 

I am also having a lot of problems with the network ports tab - especially with sockets.

1. When I add more columns, I don't have a scroll bar.

![sockets_01](https://user-images.githubusercontent.com/68922721/171604430-110a42b7-3a3e-4299-ac3f-8f4b632bb2c6.jpg)

2. As @steph461 mentioned - the column with the socket number does not exist. He wrote a 10.0.1 20220524 fix but I just installed nightly build and I don't have that column. Don't know why.

3. front/networkport.form.php - there is no add button to add new network socket and the list is unreadable, because it displays names without a location (the location appears only when I choose a specific socket)

![sockets_02](https://user-images.githubusercontent.com/68922721/171605620-e0644e46-a3d9-480b-90cd-3ce085d26e77.jpg)

4. When I add a new network socket, but I do not bind to a network port - when entering the sockets - the data is not displayed.

![sockets_03](https://user-images.githubusercontent.com/68922721/171605927-9f1087e6-ff89-4545-8240-65ceb3c70049.jpg)

5. front/networkequipment.form.php - socket tab. There is no lacalisation column.

![sockets_04](https://user-images.githubusercontent.com/68922721/171606257-17d7f6de-1a99-4675-95bb-60f38d1f9982.jpg)

They have different names in the screenshot above, but if the names are repeated - identification is impossible

**Comment by steph461** [comment]
> Salut@cconard96
> 
> J'ai également beaucoup de problèmes avec l'onglet des ports réseau - en particulier avec les sockets.
> 
> 1. Lorsque j'ajoute plus de colonnes, je n'ai pas de barre de défilement.
> 
> ![douilles_01](https://user-images.githubusercontent.com/68922721/171604430-110a42b7-3a3e-4299-ac3f-8f4b632bb2c6.jpg)
> 
> 2. Comme@steph461mentionné - la colonne avec le numéro de socket n'existe pas. Il a écrit un correctif 10.0.1 20220524 mais je viens d'installer la construction nocturne et je n'ai pas cette colonne. Je ne sais pas pourquoi.
> 3. front/networkport.form.php - il n'y a pas de bouton d'ajout pour ajouter un nouveau socket réseau et la liste est illisible, car elle affiche des noms sans emplacement (l'emplacement n'apparaît que lorsque je choisis un socket spécifique)
> 
> ![douilles_02](https://user-images.githubusercontent.com/68922721/171605620-e0644e46-a3d9-480b-90cd-3ce085d26e77.jpg)
> 
> 4. Lorsque j'ajoute un nouveau socket réseau, mais que je ne me lie pas à un port réseau - lors de la saisie des sockets - les données ne sont pas affichées.
> 
> ![douilles_03](https://user-images.githubusercontent.com/68922721/171605927-9f1087e6-ff89-4545-8240-65ceb3c70049.jpg)
> 
> 5. front/networkequipment.form.php - onglet socket. Il n'y a pas de colonne de lacalisation.
> 
> ![douilles_04](https://user-images.githubusercontent.com/68922721/171606257-17d7f6de-1a99-4675-95bb-60f38d1f9982.jpg)
> 
> Ils ont des noms différents dans la capture d'écran ci-dessus, mais si les noms sont répétés, l'identification est impossible

I had same issue

**Comment by WebGregGit** [comment]
> [cconard96](/cconard96) added the [ Need feedback ](/glpi-project/glpi/labels/Need%20feedback) label [19 dni temu](#event-6671683261)

Hi @cconard96 - feedback done :)

**Comment by cedric-anne** [comment]
@steph461 

Could you check if this issue is still present on latest version/nightly build?

**Comment by trasher** [comment]
No feedback, I close

**Comment by jlriver0** [comment]
>     3. front/networkport.form.php - there is no add button to add new network socket and the list is unreadable, because it displays names without a location (the location appears only when I choose a specific socket)
> 
> 
> ![sockets_02](https://user-images.githubusercontent.com/68922721/171605620-e0644e46-a3d9-480b-90cd-3ce085d26e77.jpg)
> 

Hi

In version 10.0.9 of glpi I still have the same problem as mentioned in point 3 with socket networks.

Has anyone been able to solve it or is it a part that is bugged?

Thank you

PD: sorry for my bad english

**Comment by iPaulis** [comment]
I can confirm this is still reproducible on the current 11.0.x: a network port with a linked socket shows nothing about the socket in the ports table, and the socket column is not even offered in the "Select default items to show" display preferences.

The cause is in `NetworkPort::rawSearchOptions()`: the socket search option (id 9) is guarded by `isField('sockets_id')`, but `glpi_networkports` has never had a `sockets_id` column (the link lives on `glpi_sockets.networkports_id` since the 10.0 data model change), so the guard is always false and the option never gets added.

I prepared a fix in #25223 that always provides the search option with a proper child join on `glpi_sockets.networkports_id` and renders the linked socket in the ports table.

**Comment by iPaulis** [comment]
Following up on this thread: most of the points reported here have since been resolved in the 11.0.x line (column scrollbar, the missing socket column in the ports list now has a fix in #25223, and a socket created without being bound to a port does appear in the Sockets tab as long as it is created from that tab).

One point from the list is still present in 11.0.x: the Sockets tab on asset pages never shows the socket location, which makes sockets with similar names hard to tell apart. I opened a dedicated, up-to-date report with a repro and a patch: #25224.
