### ISSUE TITLE
GLPI 10.0.0 - Unable to change the time of a task

### ISSUE THREAD

**Issue by Meyckoo** [glpi-project/glpi#11510]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Hello,
Since the update to version 10.0.0 it is impossible to change the time of a task. When I click on the date of the task I don't have the window to change like on the old version.

Whether with the technician or super-admin

Old version
<a href="https://zupimages.net/viewer.php?id=22/18/ulup.png"><img src="https://zupimages.net/up/22/18/ulup.png" alt="" /></a>

New version
<a href="https://zupimages.net/viewer.php?id=22/18/x6rn.png"><img src="https://zupimages.net/up/22/18/x6rn.png" alt="" /></a>

Thanks :)

**Comment by Yorgh** [comment]
I confirm this also.
Maybe it is something expected not to be able to modify a task creation date but I was using this changing my Tasks order when needed as I had no other way to do it.

If that was wanted, I can understand you do not want any more people to change this date but then I would suggest you to implement a task order number so that we can change the order of affected tasks without having to delete the tasks which would came after the one I would like to insert into my list.

I hope you understand what I mean. If not, please, tell me so that I can try better explain this.

Thanks in advance for any feedback.

**Comment by Yorgh** [comment]
Hello,

I am really surprised this is not disturbing more people.
I kindly remind that I would follow this up as well if someone can bring this feature back.

Thanks in advance.

**Comment by Meyckoo** [comment]
Hello,

Indeed it is a feature that I use daily for statistics.
I modify the date of the task to correspond to the date of the technician's intervention. It happens that the intervention is done at D and that the report of the intervention has D+3. As a result, with the new version of GLPI the charges do not correspond to reality.

Can you explain the reason of this withdrawal? And if someone can bring this feature back ? 

Best Regards,
Robin
