### ISSUE TITLE
Default ticket module doesn't work and view's bug of impact tab

### ISSUE THREAD

**Issue by trisosamu** [glpi-project/glpi#11536]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

default module for ticket doesn't work. If I change predefinied filed or mandatory filed the ticket module doesn't change

**Comment by cconard96** [comment]
Can you test the fixes made in #11421 and #11539? The fixes should be made in that order. The first pull request fixed the issue where predefined fields were not applied at all but had an issue where the predefined fields were shown in existing tickets rather than the real values. The second pull request fixed that issue.
