### ISSUE TITLE
GLPI [10.0.0] - Email Receiver Not Working

### ISSUE THREAD

**Issue by rudolcas** [glpi-project/glpi#11782]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

I have looked around for a setup configuration to create tickets via email.  

Configured - receiver, but still doesn't work and errors out.  I have looked all over the place, but have not found a solution with the error/authentication. 

Go to Setup / Receivers / + ADD

Name = help@vista.com
Active = YES
Server = smtp.gmail.com
Connection Options = IMAP / SSL / <blank> / <blank> / <blank>
Port = 465
Connection String = {smtp.gmail.com:465/imap/ssl}
Login = help@vista.com
Password = xxxxx
Accepted Mail Archieve = <empty>
Refused Mail Archieve Folder = <empty>
Maximum Size of Each File Imported by the mails receiver = 2 MB
Use mail date, instead of collect one = NO
Use Reply-To as requester (when available) = NO
Add CC Users as an observer = NO
Comments = <empty>

<img width="182" alt="image" src="https://user-images.githubusercontent.com/42798291/171538820-16b21ef2-2aff-49a2-b8cc-76693de79657.png">

**Comment by rudolcas** [comment]
Also in additional:

Setup / General / Assistance 
- Allow anonymous followups (receiver) = **YES**

**Comment by cedric-anne** [comment]
Hi,

Your issue seems to be a configuration issue. `host doesn't allow connection` indicates that GLPI connection to mail server is refused.

We only track bugs here, so I close the issue.

You can ask for community support on [forum](https://forum.glpi-project.org/), or you can consider taking a [subscription](https://glpi-project.org/subscriptions/) to get professionnal support.

Regards
