### ISSUE TITLE
10.0.2 GLPI Rules - Rules for import - Devices Tab

### ISSUE THREAD

**Issue by brunnersm** [glpi-project/glpi#11950]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.2

### Bug description

A Tab Devices in Rules for import and link equipments, show peripheral rules. 
![image](https://user-images.githubusercontent.com/69863640/174637083-2c283f8d-2b50-48f2-bc25-96fed8447f2b.png)

And Devices rules in Global
![image](https://user-images.githubusercontent.com/69863640/174637202-b2988ff0-efc6-4859-952f-36c461bedde8.png)

### Steps To reproduce

Administration
Rules
Rules for import and link equipments
Tab [Devices]

### Anything else?

Maybe create a Tab Peripheral ?

**Comment by brunnersm** [comment]
This problem persist. 
When i choice Devices show Peripheral rules and when choice Global, show Devices and Global rules.
Not exist a column in table (glpi_rules) to fix this.

**Comment by trasher** [comment]
The issue you describe is indeed still present, but occurs only sometimes and never on the same tabs. I've not been able to find any solution or understand what goes wrong.

**Comment by brunnersm** [comment]
This issue occurs always and only on these 2 tabs.
It occurs exactly as in the images, the tabs are inverted.
![image](https://user-images.githubusercontent.com/69863640/188621560-a93ef187-726f-4673-9dbb-f4371ad07d4b.png)
![image](https://user-images.githubusercontent.com/69863640/188622439-4d5a0514-e976-466a-9f5f-c83acc3d43a7.png)

**Comment by trasher** [comment]
OK, I was indeed talking about another issue I've seen sometimes... I confirm:
- a `Peripherals` tab is certainly missing,
- devices should be displayed in `Devices` tab
- `Global` tab should not display devices

**Comment by stonebuzz** [comment]
Above all : 
It is a problem of the name of the rule.
All ```rules``` are grouped by ```itemtype``` value from criteria list

First : 
See this criteria ```Peripheral update (by serial)```, from ```Device``` tab :
![image](https://user-images.githubusercontent.com/7335054/188666959-b0112e80-2578-46bb-be61-250b4f90e123.png)

The rule name should be ```Device update (by serial)``` rather than ```Peripheral update (by serial)```

Second :
All rules that do not have an ```is``` criterion on ```itemtype``` are added to the "Global" tab.

See ```Device update (by mac+ifnumber restricted port)```
![image](https://user-images.githubusercontent.com/7335054/188668607-925c66ec-4fa7-4de9-8d2e-8f407820ab48.png)

The rule name should be ```Global update (by mac+ifnumber restricted port``` rather than ```Device update (by mac+ifnumber restricted port```

Finally, the display is correct, some rules should change their name, i don't know if it can be done easily

**Comment by brunnersm** [comment]
Thanks, I changed all the names.

**Comment by trasher** [comment]
> Finally, the display is correct, some rules should change their name, i don't know if it can be done easily

Default names can be changed easily; but we cannot really update users ones.

**Comment by trasher** [comment]
Fixed as of #12601
