### ISSUE TITLE
Unable to change status of Tickets

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#12120]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Since the update I am unable to change the status of tickets - unable to solve - unable to set to new.

Ticket does have a requester and is assigned but whatever I do the ticketstatus wont change - no error message and no errors in log.

All plugins have been disabled.

Testet with super-admin rights.

**Comment by DooBio** [comment]
Thanks @blippercop 🙏🙏🙏

We don't perform the same action but the purpose and the same on my ticket https://github.com/glpi-project/glpi/issues/12131

I tested your solution to disable the assignment rules and indeed it works very well.

I hope you can find a solution because this operation is very practical to assign automatically according to a form

**Comment by cedric-anne** [comment]
Hi,

Could you check if #12149 resolves your issue ?
