### ISSUE TITLE
Image loading problem

### ISSUE THREAD

**Issue by Dajanek7** [glpi-project/glpi#12438]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.2

### Bug description

There is a problem with loading images from email.
The problem occurs with some users.

![Bez tytułu](https://user-images.githubusercontent.com/111117496/184332914-df443413-3741-41c0-8701-bd16e6965275.png)
![Bez tytułu1](https://user-images.githubusercontent.com/111117496/184332935-ec9234a4-7400-4cbf-8dd0-bb44be979bce.png)

### Relevant log output

```shell
[2022-08-12 10:50:02] glpiphplog.WARNING:   *** PHP Warning (2): file_put_contents(/home/ticket/web/ticket.pl.ctdi/public_html/files/_tmp/image002.png): Failed to open stream: Permission denied in /home/ticket/web/ticket.pl.ctdi/public_html/src/MailCollector.php at line 1671
  Backtrace :
  src/MailCollector.php:1671                         file_put_contents()
  src/MailCollector.php:1544                         MailCollector->getRecursiveAttached()
  src/MailCollector.php:1713                         MailCollector->getRecursiveAttached()
  src/MailCollector.php:1017                         MailCollector->getAttached()
  src/MailCollector.php:761                          MailCollector->buildTicket()
  src/MailCollector.php:1830                         MailCollector->collect()
  src/CronTask.php:1018                              MailCollector::cronMailgate()
  front/cron.php:84                                  CronTask::launch()
```

### Your GLPI setup information

Operating system: Linux 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64
PHP 7.4.27 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix, pspell, readline, session, shmop, soap, sockets,
	sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="90" memory_limit="512M" post_max_size="48M" safe_mode="" session.save_handler="files"
	upload_max_filesize="128M" 
Software: Apache/2.4.52 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.5.13-MariaDB-1:10.5.13+maria~focal
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: ticket_glpi@localhost/ticket_glpi
	Host info: Localhost via UNIX socket

**Comment by trasher** [comment]
Logs are showing you have rights issues on your filesystem. Fix that and that should  be ok.

**Comment by Gitnor77** [comment]
I have the same problem.

GLPI 10.0.2 Case 1:
![image](https://user-images.githubusercontent.com/109066311/186832723-fafe093e-4392-4eb5-87f1-375a2b87a2ab.png)

![image](https://user-images.githubusercontent.com/109066311/186832882-69d712f1-3e6b-4d22-9df4-8ce699e71385.png)

GLPI 10.0.2 Case 2:
![image](https://user-images.githubusercontent.com/109066311/186833054-6ddcb56e-cfd5-413a-87fa-10bcc65ac47c.png)

![image](https://user-images.githubusercontent.com/109066311/186833191-69bce5b3-f0cc-4fe3-bafb-2a680363b4a8.png)

GLPI 9.5.7
![image](https://user-images.githubusercontent.com/109066311/186833603-0f65316e-5406-4566-8c3d-62f078e2aca9.png)

![image](https://user-images.githubusercontent.com/109066311/186833523-8b1b5e27-72f4-4ed7-8a73-f8131ea4d7d4.png)

GLPI 10 -> this problem is random, occurs with photos added in the body of the email. 
GLPI 9 -> everything works properly.
