### ISSUE TITLE
GANTT missing after upgrade

### ISSUE THREAD

**Issue by Deininger-IT** [glpi-project/glpi#12441]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Just updated from 10.0.1 to 10.0.2 and after checking all functionality i´m missing the GANTT chart within the "project" tab.
This issue is showing up on all user roles (predeifed or selfdefined).
All other functins are working without any issues.

### Your GLPI setup information

Ubuntu 20.04.4 LTS and GLPI 10.0.2 (on virtualisation platform)

**Comment by cconard96** [comment]
This was highlighted in the Changelog and the release news.

"Gantt feature has been moved into the gantt plugin."

This was done because the GLPI license had to be changed to GPL 3 or later to be compatible with the code used for the new native inventory feature. The library used for the Gantt feature did not have a compatible license, so it had to be split out into its own project/plugin.

**Comment by Deininger-IT** [comment]
Sorry, i haven´t seen this on the release page(s)
https://glpi-project.org/new-glpi-version-10-0-2/

Please close the ticket

Thanks for the quick response

**Comment by cconard96** [comment]
It was removed in 10.0.1, not 10.0.2.
https://glpi-project.org/get-the-new-glpi-version/
