### ISSUE TITLE
Reminders : cloning does not work

### ISSUE THREAD

**Issue by MaevaLaprie** [glpi-project/glpi#12487]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

When you press "send" after clicking on "clone", a blank page is displayed.

![Capture](https://user-images.githubusercontent.com/16307742/186626622-7f5e0a43-12fc-48f7-bdb6-1f5254bad25f.PNG)

J'ai testé au niveau du "projet", cela fonctionne.

### Page URL

http://XXX/front/massiveaction.php

### Steps To reproduce

1. Open reminder
2. Click "Action"
3. Click "Clone"
4. Click "Send"
5. Bug : White page

**Comment by trasher** [comment]
Please provide logs, as requested.

**Comment by MaevaLaprie** [comment]
Attached is the log file

[php-errors.txt](https://github.com/glpi-project/glpi/files/9423662/php-errors.txt)

**Comment by cconard96** [comment]
I cannot recreate the issue in 10.0.2. Reminders are not clonable items. It looks like the behavior changed in 10.0 when the Clonable trait was improved (#7816). I don't think it was originally intended for this item type to be clonable. The original feature was just applied too broadly.

Indeed, this item type has a UUID field that would need to be regenerated for any clone for it to work properly, but is not currently handled since it wasn't intended to be clonable.

**Comment by MaevaLaprie** [comment]
Ok thank you for your explanation and your time.
It's a pity that this function is not developed.
have a nice day

**Comment by cconard96** [comment]
Feel free to add this feature suggestion on the UserEcho site for it to be considered for a future version, or if you would like to try implementing this feature, you can also open a pull request.

https://glpi.userecho.com/
