### ISSUE TITLE
Missing the Lock & Unlock selection on Computers

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12505]
Missing the Unlock tab in Computers. There is only the "Unlock items" which gives an error "Failed operation", and the "Unlock Componets" in which I cannot unlock the computer name for example.

_Originally posted by @dxdemetriou in https://github.com/glpi-project/glpi/issues/11985#issuecomment-1228645914_

**Comment by WebGregGit** [comment]
Hi @dxdemetriou 

What version of GLPI?
System?
Browser?

How you locked your computer name? By global? 

![image](https://user-images.githubusercontent.com/68922721/186950375-64d0a526-88fd-4186-beec-7ad546d4f14a.png)

This is what I see. From the computer, I can only unlock the group, because the remaining locks are global and I can withdraw them only from the global tab. 
To add a single lock, I have to change some value manually or add a global lock.

If this is not what you have a problem with, you need to describe it more precisely.

**Comment by dxdemetriou** [comment]
Hello @WebGregGit 

Sorry, I forgot because of previous topic. v10.0.2, Windows/Linux, Chrome

From where is this screenshot?

I'm trying from Asset - Computers that I can select the computer. I also tried from inside (computer.form.php) but I couldn't find the Lock/Unlock as on GLPI v9.5. I used them for locking & unlocking the computer name, location, user, etc.

**Comment by WebGregGit** [comment]
![image](https://user-images.githubusercontent.com/68922721/186953431-1e43e5b8-e3f7-4db8-a014-5b7d223c241d.png)

Strange, because this tab was on Computers from the beginning version 10. The problem was with other assets. If you do not have it, try installing the GLPI nightly build ( [https://nightly.glpi-project.org/glpi/](https://nightly.glpi-project.org/glpi/) ) - a lot of fixes have been implemented since version 10.0.2

**Comment by dxdemetriou** [comment]
I found it. So it's changed the behaviour in a separated tab instead on the Actions as selection, that's why I have confused.

I'll try a nightly build on a testing environment, Thanks.
