### ISSUE TITLE
Constistent escaping

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1254]
In CommonDBTM, values are automatically escaped in the `update` method, but not in the `add` method.

This should be consistent (escaped everywqhere or escaped nowhere).

**Comment by remicollet** [comment]
?

Values are globally escaped in includes.php, for all methods
`   $_POST = array_map(array('Toolbox','addslashes_deep'), $_POST);`

But indeed we have tons of inconsistency because of this (historical) behavior.

A proper way will be to keep all values unescaped, and on espace them before DB action or display.
Way to store < and > char in the DB is also very.... ugly.

**Comment by trasher** [comment]
Yes, but the API does not use that :'(

And in facts I was wrong, nothing is escaped in commondbtm...

**Comment by pVesian** [comment]
Sorry to update this, but it is also a cause of distress in plugins. For example if I want to create a task using a solution's content that has quotes, I need to escape the message. It would be easier to maintain if it wasn't the case.

Example:
```php
global $DB;

$task_content = sprintf('%s: %s', $solution_data['date'], $solution_data['content']);
$task_data = array(
    'content' => $DB->escape($task_content),
    'tickets_id' => $ticket->getId(),
    'users_id_tech' => $solution_data['users_id'],
    'state' => Planning::INFO,
    '_status' => $ticket->input['status'],
    '_glpi_csrf_token' => Session::getNewCSRFToken(),

    // data set to default values
    'tasktemplates_id' => 0,
    'taskcategories_id' => 0,
    'is_private' => 0,
    'actiontime' => 0,
    'groups_id_tech' => 0,
    'is_recursive' => 0,
    'add' => true,
);
$task = new TicketTask();
$add_task_success = $task->add($task_data);
```
