### ISSUE TITLE
Webcal export problem glpi 9.1

### ISSUE THREAD

**Issue by morpheuz2006** [glpi-project/glpi#1257]
Hello

In planning calendar i cant export webcal to my calendar client. There is a error ..
 its a bug? 

in earlier version works very well.. can anyone fix this?

**Comment by SylvainGuibert** [comment]
Same issue for me.

**Comment by satyan01** [comment]
same issue

**Comment by satyan01** [comment]
still error on webcal export

![image](https://cloud.githubusercontent.com/assets/15144026/20300823/294de738-ab21-11e6-87d9-199060dec0a3.png)

**Comment by SylvainGuibert** [comment]
We still have this issue in 9.1.1

**Comment by Krisstof** [comment]
I have the same problem.
I used "calendar subscription" in Apple Calendar without any problem with previous v0.x versions but with GLPI v9.1.1 it doesn't work anymore (erreur -1).
That makes me sad because it was a so useful feature.
Can any one give us the correct new syntax ?

Best

**Comment by tsadock** [comment]
Are you using the fields plugin ?
Perhaps it's the same problem that the following issue : 
[https://github.com/pluginsGLPI/fields/issues/97](https://github.com/pluginsGLPI/fields/issues/97)

**Comment by Krisstof** [comment]
Hi

First, thanks for answering me.

I just install "Fields" plugin v1.4.3
Same problem with webcal export : no error in Apple Calendar or Thunderbird CalDAV but no syncing, no tasks events.

So I tried to add : 
&& $_SESSION["glpiroot"]
At line 208 of setup.php file (of "fields" plugin directory of course)

sample :
function plugin_fields_checkFiles() {
   $plugin = new Plugin();

   if (isset($_SESSION['glpiactiveentities'])
      && $plugin->isInstalled('fields')
      && $plugin->isActivated('fields')
      && Session::getLoginUserID()) {
      && $_SESSION['glpiroot']
      Plugin::registerClass('PluginFieldsContainer');
      Plugin::registerClass('PluginFieldsDropdown');
      Plugin::registerClass('PluginFieldsField');
But when I did that : glpi web interface became blank
So it seems there is a syntax glitch somewhere.
Do you have an idea of what I can try.

I don't understand why I need to use "Fields" plugin in order to have Planning Webcal Export working ?

Any help ?

Best 

Christophe Ferrandon
