### ISSUE TITLE
Issue with stacked network elements

### ISSUE THREAD

**Issue by moz4r** [glpi-project/glpi#12609]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Hi ! thank you for your work, I have odd behaviors while importing stacked elements. Sometime GLPI throw this error : Uncaught Exception RuntimeException: Cannot wire a port to itself! in /var/www/glpi.toureiffel.paris/src/Inventory/Asset/NetworkPort.php at line 763
Sometime it is OK but GLPI create duplicated networks elements ( 1 by stacked element )
I tried also with manual import to debug, same issue : I can PM xml files.

Thank you for your help

### To reproduce

glpi-agent ( networkinventory task ) OR from GUI task/import XML

### Expected behavior

A stacked element should not be duplicated , with ports listed like this ( 1/1 -> 2/24 )
( I rembember it was like this with fusion )

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

Last agent ( 1.4 ) - GLPI 10.0.0.2 - plugin 1.0.3

**Comment by steph461** [comment]
> ### Bug reporting acknowledgment
> Yes, I read it
> 
> ### Professional support
> _No response_
> 
> ### Describe the bug
> Hi ! thank you for your work, I have odd behaviors while importing stacked elements. Sometime GLPI throw this error : Uncaught Exception RuntimeException: Cannot wire a port to itself! in /var/www/glpi.toureiffel.paris/src/Inventory/Asset/NetworkPort.php at line 763 Sometime it is OK but GLPI create duplicated networks elements ( 1 by stacked element ) I tried also with manual import to debug, same issue : I can PM xml files.
> 
> Thank you for your help
> 
> ### To reproduce
> glpi-agent ( networkinventory task ) OR from GUI task/import XML
> 
> ### Expected behavior
> A stacked element should not be duplicated , with ports listed like this ( 1/1 -> 2/24 ) ( I rembember it was like this with fusion )
> 
> ### Operating system
> Linux
> 
> ### GLPI Agent version
> Other (See additional context below)
> 
> ### GLPI version
> Other (See additional context below)
> 
> ### GLPIInventory plugin or FusionInventory for GLPI plugin version
> Other (See additional context below)
> 
> ### Additional context
> Last agent ( 1.4 ) - GLPI 10.0.0.2 - plugin 1.0.3

Hello @moz4r 

its this problem ? I have aruba stacked switches
I wanted to report this bug since 10.0.2 but I have confidential information in the xml ( Mac, vlan,etcc...)
So I left this problem aside. 

On 10.0.1 its wask it seems to me

[2022-09-07 11:11:34] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Cannot wire a port to itself! in /var/www/html/glpi/src/Inventory/Asset/NetworkPort.php at line 780
  Backtrace :
  src/Inventory/Asset/NetworkPort.php:309            Glpi\Inventory\Asset\NetworkPort->addPortsWiring()
  src/Inventory/Asset/NetworkPort.php:519            Glpi\Inventory\Asset\NetworkPort->handleMacConnection()
  src/Inventory/Asset/NetworkPort.php:541            Glpi\Inventory\Asset\NetworkPort->handleConnections()
  src/Inventory/Asset/NetworkPort.php:536            Glpi\Inventory\Asset\NetworkPort->portChanged()
  src/Inventory/Asset/InventoryNetworkPort.php:610   Glpi\Inventory\Asset\NetworkPort->portCreated()
  src/Inventory/Asset/InventoryNetworkPort.php:120   Glpi\Inventory\Asset\NetworkPort->handleCreates()
  src/Inventory/Asset/NetworkPort.php:693            Glpi\Inventory\Asset\NetworkPort->handlePortsTrait()
  src/Inventory/Asset/NetworkPort.php:526            Glpi\Inventory\Asset\NetworkPort->handlePorts()
  src/Inventory/Asset/MainAsset.php:843              Glpi\Inventory\Asset\NetworkPort->handle()
  src/Inventory/Asset/MainAsset.php:763              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/Inventory/Asset/NetworkEquipment.php:221       Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/RuleImportAsset.php:965                        Glpi\Inventory\Asset\NetworkEquipment->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:702                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:283                      Glpi\Inventory\Request->inventory()
  src/Inventory/Request.php:250                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:298    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:235    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  src/Inventory/Conf.php:246                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:187                         Glpi\Inventory\Conf->importContentFile()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->importFile()

**Comment by moz4r** [comment]
Hi Steph ! Yes it is the same , I use Aruba also. I sent my xml and aruba mibs to the team. Regards

**Comment by trasher** [comment]
@moz4r @steph461 please test #12655

**Comment by steph461** [comment]
It works, i dont have error
I have 5 switch stack Aruba Its OK

**Comment by moz4r** [comment]
Tks ! I don't have the error anymore but it create duplicated elements instead of 1 element with ports from 1/1 to 5/4 )
@Steph same for you ?

**Comment by steph461** [comment]
I think glpi is based on the serial number of the switches. And it duplicates the switches by serial number but I have all the information from 1/1 to 5/48 on one of the stacked swith
![image](https://user-images.githubusercontent.com/68054991/190482775-4ddc37dc-32f6-4b07-bc76-530aa92655ea.png)

I don't know if GLPi can create a group of stacked switches and a drop-down menu of attached switches

example: SW-Test-Stack*5

**Comment by trasher** [comment]
As far as I know, s-tacked switches alwas has been inventoried on several NetworkEquipment assets. Changing that is not a bug, bu another development.
