### ISSUE TITLE
9.2 : Add child notion to software licence

### ISSUE THREAD

**Issue by stonebuzz** [glpi-project/glpi#1302]
Actually is not possible to link software licence to another.

With this notion we can create a software licence like "Microsft Licence" and add many child like "Office 365 Family" etc ..., like this :

![selection_002](https://cloud.githubusercontent.com/assets/7335054/20344262/592e600a-abf2-11e6-8bf5-e540b1a6fe59.png)

I created a PR for this

#1204 

cordially

**Comment by roscomwill** [comment]
Hi,

Licensing is a major part of most companies, including the one I currently work for. I am in support of there being additional functionality within the licensing / software area for OEM and VLK licensing keys.

I think it would also be a good idea to be able to have visibility of how many licenses are available to you when it comes to installing them on a computer.

It would be very useful to have an "install license and software" or similar button in order to pick an available product key. And install the relevant software on the particular asset to prevent having to install the software and then assign a license. 

Any questions let me know.

Kind Regards,

**Comment by trasher** [comment]
The child stuff has been merge already.

@roscomwill please use suggestions site to propose enhancements (if this is not yet existing): http://glpi.userecho.com/
