### ISSUE TITLE
Error on installing licence

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1312]
http://forum.glpi-project.org/viewtopic.php?id=155944

Full right in my profile

**Comment by trasher** [comment]
I cannot reproduce on the current 9.1/bugfixes branch.

**Comment by trasher** [comment]
OK, seems to be an issue with massive actions

**Comment by trasher** [comment]
I can reproduce the issue if the license is not attached with a software version. It seems the expected behavior, maybe we should just add a descriptive message to help using to get that fixed.

Unfortunately; this require us to add an error message with a new string (see https://github.com/trasher/glpi/commit/a08d61dc110cd26745d47be58927ded24d770b4f), but since strings are now freezed for 9.1.2 it could only reach 9.1.3.

**Comment by trasher** [comment]
Fixed from #1699
