### ISSUE TITLE
SLT on ticket creation

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1313]
http://forum.glpi-project.org/viewtopic.php?id=155915

I confirm getSltData is limited on ticket entities

**Comment by orthagh** [comment]
additionnal: http://forum.glpi-project.org/viewtopic.php?id=156443

**Comment by peraun** [comment]
I'm still facing this problem, even after the update. I think it's because I had to create SLA/SLT to the sub-entities and then being able to define SLA/SLT's until it was fixed. Doing this the button to add SLA/SLT was being displayed in the ticket and I could select one to the ticket.
After the update I deleted the sub-entities SLA/SLT's, and the button didn't showed up for selection. I also tried deleting the sub-entities SLA/SLT's before updating and got the same result.
And if I create then for the entity sub-entities again, I'm able to set a SLA/SLT.
I'll attach some images to demonstrate the error. (ps: I don't know if I can post Dropbox links here, If not please tell me which image upload service I can use.)
SLA Root entity https://www.dropbox.com/s/2ecetrinz7ck5z6/SLA%20Root%20entity.png?dl=0
Root Ticket-GLPI Version https://www.dropbox.com/s/ezppyex7yb57j4b/Root%20Ticket-GLPI%20Version.png?dl=0
Sub-entity ticket https://www.dropbox.com/s/uv0h9l76kzoi850/Sub-entity%20ticket.png?dl=0

If someone need more information let me know.
And thanks for the amazing work guys!
