### ISSUE TITLE
image access denied

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1316]
Dear all,

I tried all to fix this issue but I don't find the reason

GLPI\files

everyone
authenticated users
iusr
system
network service
domain users
administratros
iis_iusrs
trustedinstallers

and some users have access denied when they try to open an image

**Comment by tyronewyatt** [comment]
Sounds like the uploaded files are retaining the NTFS security permission of the PHP temp folder rather than inherenting permissions of glpi folder. You can either change the permissions on PHP temp folder or change the location of the PHP temp folder to another partition. When the PHP temp folder is on another partition the uploaded files inherent the permissions of the glpi folder.
