### ISSUE TITLE
TAG ##supplier.comments## doesn't work

### ISSUE THREAD

**Issue by trisosamu** [glpi-project/glpi#13253]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

when I use notification for a new comment the tag doesn't work.
On the email I see this

Comments: ##supplier.comments##

**Comment by cconard96** [comment]
What context is it being used in?
This tag is for the comments field of a supplier and must be used in a loop of the suppliers, and is not the content of a response to a ticket.

**Comment by trisosamu** [comment]
Oh, i’m sorry. What is the right tag to the content of a response to a ticket?

**Comment by cconard96** [comment]
You should probably refer to the existing notification templates and the user documentation for more information.
https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/notifications/template_example.html

```
##FOREACHtimelineitems##

##lang.timelineitem.author## ##timelineitem.author##
 ##lang.timelineitem.description## ##timelineitem.description##
 ##lang.timelineitem.date## ##timelineitem.date##

##ENDFOREACHtimelineitems##
```

For just the latest item, replace FOREACH line with
```
##FOREACH LAST 1 timelineitems##
```

Instead of `timelineitems` you can use `tasks` or `followups` to only use specific types of responses.

If you need more help, please use the community forum as GitHub is only used for tracking bugs.
https://forum.glpi-project.org/index.php
