### ISSUE TITLE
Bad display in the login text box.

### ISSUE THREAD

**Issue by Molina15** [glpi-project/glpi#13410]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When writing text to add in the start menu, in Settings-> General it is not shown above the start fields like in previous versions, but on the side. If it could be corrected in future updates I would appreciate it. Greetings.

![image](https://user-images.githubusercontent.com/91999535/203935364-4865a449-6cc0-4e37-8db4-53b19b401c1e.png)

**Comment by cconard96** [comment]
This is not a bug. The login text, public FAQ link (if enabled) and anything added to the login screen by plugins are intended to be displayed in the right column instead of above login fields.

We only track bugs here, but for feedback and suggestions,feel free to use the UserEcho site.
https://glpi.userecho.com/
