### ISSUE TITLE
Image being saved with base64 decoding.

### ISSUE THREAD

**Issue by auguzsto** [glpi-project/glpi#13628]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

# Image bug.

![image](https://user-images.githubusercontent.com/40308971/207860597-53c9b6aa-d701-49fc-8dbe-122ff59e160b.png)

**Comment by btry** [comment]
Hi

Please fill 
- the page URL (the bug may occur in some page but not in an other)
- steps to reproduce (if we try to reproduce by guessing your steps and ovserve expected behavior, we both loose precious time)
- your GLPI setup information (sometimes a bug is caused by a plugin, a bad PHP version, or an other external thing)
