### ISSUE TITLE
Ticket Satisfaction eMail is not send to "requester" as set, but to "ticket author"

### ISSUE THREAD

**Issue by jennycla** [glpi-project/glpi#13818]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

A hotline colleague opens a ticket for a user and enters this user as requestor. For sure, the hotline colleague remains the author of the ticket. 

For the "Notification - Ticket Satisfaction", we have entered the requestor as email recipient (see attached screenshot). Nevertheless, the ticket author (the hotline colleague) receives the notification. I would expect, that the requestor receives the mail.

![image](https://user-images.githubusercontent.com/122880034/212889982-af626fe7-e324-4859-87f5-e2f2b0a38251.png)

### Steps To reproduce

1. Activate ticket satisfaction email and configure the ticket satisfaction notification in the way, that the requestor receives it.
2. Open a ticket for another user and enter this user as requestor.
3. Solve the ticket.
4. Wait for the ticket satisfaction notification.

### Your GLPI setup information

![image](https://user-images.githubusercontent.com/122880034/212891466-544226e6-4b80-4d4b-a727-795eaf70b8ae.png)

**Comment by cedric-anne** [comment]
Hi,

I just made some tests.
- When the `Requester` recipient is used, then notification is correctly sent to all requesters, and is NOT sent to the writer.
- When the `Writer` recipient is used, then notification is correctly sent to the writer, and is NOT sent to the requesters.

Writer can be found here:
![image](https://user-images.githubusercontent.com/33253653/215570659-e15d556a-df87-426a-9a54-4455f9950773.png)

Could you verify that the person that received the notification is the actual writer of the ticket ?

Also, could you tell us if you are using some plugins? Maybe problem is due to a plugin.

**Comment by trasher** [comment]
No feedback, I close
