### ISSUE TITLE
Bug when assign technical group

### ISSUE THREAD

**Issue by kbn53** [glpi-project/glpi#13878]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When I create a rule to assign entity + technical group to a computer, my computer take the good entity but he take a new group (the id of my official group).

### Steps To reproduce

Create rule to assign element to entity
Assign entity and technical group
Bad group assigned

**Comment by cedric-anne** [comment]
Hi 

Please upgrade to GLPI 10.0.6 to see if problem persists.

**Comment by cedric-anne** [comment]
Initially opened with more details here: https://github.com/glpi-project/glpi-inventory-plugin/issues/291

**Comment by stonebuzz** [comment]
hi @kbn53 
This issue (already discuss here https://github.com/glpi-project/glpi-inventory-plugin/issues/276 or here https://github.com/glpi-project/glpi/issues/13667)
is fixed by this Pull Request https://github.com/glpi-project/glpi/pull/13668 
and merge in GLPI 10.0.6.

You should update your version of GLPI

Best regards
