### ISSUE TITLE
Plugin mreporting Dashboard incorrect display.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#13973]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Reports are displayed incorrectly on the Dashboard tab 
I wrote here because I didn't find a section with bugs in.
Like the plugin developers are also your team?
If I wrote it in the wrong place, please close it.

<html>
<body>

mreporting | 1.8.2
-- | --

</body>
</html>

![image](https://user-images.githubusercontent.com/16879167/215980333-e33bcc49-3a1c-4707-9be4-a2580c367f5b.png)

![image](https://user-images.githubusercontent.com/16879167/215980542-742ee5cf-703c-4d84-bb4f-fde986af0a0b.png)

**Comment by trasher** [comment]
Please report plugins issues on plugin repository

**Comment by kofe88** [comment]
@trasher 

There is simply no issues section in the plugin repository, I don't see an opportunity to write there.

![image](https://user-images.githubusercontent.com/16879167/215983755-8db620eb-1a5c-4a8d-bc15-bb61d0f118db.png)

But anyway, I'm sorry.

**Comment by cedric-anne** [comment]
@kofe88  

The issues section on the plugin is closed because there is no active developper in the community that is willing to work on this plugin on its spare-time. Almost all recent commits on the plugin were done by people that work on it either because bug was blocking a customer that paid for professional support, either because someone sponsored a new feature.

[Community forum](https://forum.glpi-project.org/) is the best place to expose your problem, if you do not want to pay for professional support. Maybe someone will be able to fix it.

If you are able to propose a fix for this bug, do not hesitate to create a pull request, we will be happy to have a new contributor.
