### ISSUE TITLE
Sure, I have read, but it seems **you did not** read when you opened your issue:

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#14281]
Sure, I have read, but it seems **you did not** read when you opened your issue:

«We do not support community plugins. Contact directly their authors, or use [the community forum](https://forum.glpi-project.org/).»

Regards.

_Originally posted by @trasher in https://github.com/glpi-project/glpi/issues/14278#issuecomment-1461672411_

@trasher
Lol... First you did not read the issue carefully, then you didn't understand the situation and then you are trying to stole away with beeing rude and closing the issue... Oh boy... :-)

@cedric-anne
You are one of the authors - where can I sumit issues for Plugin Objects Management?

**Comment by cedric-anne** [comment]
@vollkommenIrrelevant 

To make things clear, the issue section on the plugin is closed because there is no active developper in the community that is willing to work on this plugin on its spare-time. Almost all recent commits on the plugin were done by people that work on it either because bug was blocking a customer that paid for professional support, either because someone sponsored a new feature.

So, really, [community forum](https://forum.glpi-project.org/) is the best place to expose your problem, if you do not want to pay for professional support.

If you are able to propose a fix for this bug, do not hesitate to create a pull request, we will be happy to have a new contributor.
