### ISSUE TITLE
GLPI 10.0.6 upgrade to GLPI 10.0.7

### ISSUE THREAD

**Issue by RaivoMahnovs** [glpi-project/glpi#14542]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

After uploading files from GLPI 10.0.7.tar to GLPI root directory, install display shows this error:

![image](https://user-images.githubusercontent.com/120176527/232717590-948399eb-8039-4eed-872e-56f9b546d7b6.png)

Until GLPI 10.0.7 version this upgrade process worked fine.

### Relevant log output

```shell
Log files won't show any errors about this issue.
```

### Your GLPI setup information

![image](https://user-images.githubusercontent.com/120176527/232717478-258a5daf-4f2b-4822-b215-16f74df30a3b.png)

**Comment by cedric-anne** [comment]
See https://glpi-install.readthedocs.io/en/latest/update.html

**Comment by RaivoMahnovs** [comment]
I managed to get the upgrade to work by finding a file with name "10.0.6" in directory '_/glpi_root/version_', which i deleted after uploading files from 10.0.7 and everything worked fine afterwards. If anybody has the same issue, maybe this is useful.

Thank you!

**Comment by cconard96** [comment]
That isn't the correct fix if you or others experience this issue.
GLPI has these files named for specific versions precisely because people were just copying the new files over the old ones instead of the way recommended in the update documentation. This leads to old code being left behind which can cause issues.

The update process for GLPI is to always extract GLPI to a new/empty folder, then copy only specific files/folders from your old installation to the new folder.

**Comment by RaivoMahnovs** [comment]
Thank you! I will keep that in mind and do it all over again in the correct way.
