### ISSUE TITLE
Knowledge Base "No item found"

### ISSUE THREAD

**Issue by SpyPenguins** [glpi-project/glpi#14597]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

I am having an issue where if I'm in the knowledge base and click on the next page button it comes up with "No item found". If I change the number of items displayed on a page I can see all of my documents. This only happens in the knowledge base. I can change pages on any other part and get all of my items.

![Firstpage](https://user-images.githubusercontent.com/72776049/234682172-534e593e-c7bb-48ff-9f98-5aa01e26e90c.png)
![Secondpage](https://user-images.githubusercontent.com/72776049/234682168-143a4225-e5bf-488c-a00b-dd54a0e20392.png)

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue.

To reproduce:
 - Create a KB category "test",
 - Create 6 elements in this category,
 - Go to the KB browse view,
 - Change "Display (number of items)" to 5,
 - Filter on the "test" category (from the tree on left panel),
 - Go to next page,
 - `No item found` is displayed, instead of a list containing the 6th item.

**Comment by cconard96** [comment]
I cannot recreate the issue with the latest release. Is this still an issue?

**Comment by SpyPenguins** [comment]
This is resolved. Thank you!
