### ISSUE TITLE
max_closedate is only updated for root entity and never for childs

### ISSUE THREAD

**Issue by sebastien-weiland** [glpi-project/glpi#14707]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

When generating surveys, the max close date of the ticket is stored during a loop (by entity) => $max_closedate

At the end, the code updates the parent entity maxdate but never the code never update the current/child entity (so the query is not good)

**Comment by cedric-anne** [comment]
Hi,

Indeed, it seems that the `max_closedate` is never updated for entities that are located the end of the tree. It probably has no functional impact (i.e. there is no bug), but could have a really negative effect on crontask performances.

**Comment by sweiland57** [comment]
Apparently there is a functional impact as the SQL request is constructed with potential old tickets (if no survey attached), so this can produce more surveys than expected

We implemented a small fix to update the end of tree max close date so that we ensure the tickets are not parsed twice for the entity:
// Sauvegarde du max_closedate sur entites filles pour ne pas tester les meme tickets 2 fois (##FIX)
	$conf->getFromDB($current);
        $conf->update(['id' => $conf->fields['id'], 'max_closedate' => $max_closedate]);

Also, after checking, we were unsure about this clause in SQL statement:
new QueryExpression("ADDDATE(" . $DB->quoteName("glpi_entities.max_closedate") . ", INTERVAL $duration DAY) <= NOW()"),

As the surveys are using the time of generation as start date, the survey duration should not be used in the SQL query I guess ($duration)

**Comment by cedric-anne** [comment]
Could you create a pull request with your fix?

**Comment by sebastien-weiland** [comment]
Got no dev environment but I can give you the update file that matches current 9.5 bugfixes
[ticket.class.php.txt](https://github.com/glpi-project/glpi/files/11478415/ticket.class.php.txt)

**Comment by sweiland57** [comment]
@cedric-anne 
Could you provide me a one liner to dump the final SQL request on a log file please ?

Everything seemed to work correctly for a few days but I got a lot of surveys generated sunday evening, I am wondering if something (an automatic action?) did change the max_closedate for the child entity (otherwise we could not have ticket closed before)

![image](https://github.com/glpi-project/glpi/assets/114492076/e6629e27-f246-4292-aef5-2a908dc3866f)

**Comment by sweiland57** [comment]
I can confirm that something is modifiying the date apparently in DB for the child entity:
![image](https://github.com/glpi-project/glpi/assets/114492076/08661e02-320b-412e-8a27-e2e82fd6af19)

Maybe the fix is not working as expected, for the moment I have no clue about the root cause
