### ISSUE TITLE
"Password Forget" after entities transfer not working

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi#14934]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

If you transfer the "Password Forget" notification to a subentity, the TYPE field no longer displays the "user" option, and it stops functioning. Notifications cannot be customized based on the user's entity.
![image](https://github.com/glpi-project/glpi/assets/56876938/a68bd1d8-8ae0-4f1e-ad98-f082e09dd6ba)

### Page URL

/front/notification.form.php?id=93

### Steps To reproduce

1. transfer to sub entities "Password Forget" notification
2. go to front/lostpassword.php?lostpassword=1
3. Do the password reset

### Your GLPI setup information

GLPI 10.0.7 ( => /glpi)
Installation mode: TARBALL
Current language:fr_FR

**Comment by cconard96** [comment]
Not a bug, but an intentional behavior added 12 years ago.
https://github.com/glpi-project/glpi/commit/402e9dd77df01e287bee00ca2b80c97bab2f3e4d
The issue it references in the git commit message is from the old bug tracker, so I do not know why the change was made originally.

Notifications that have templates related to Automatic Actions (CronTask), Database connection/SQL replicas (DBConnection) and User type are only allowed in the Root Entity.
This means that notifications with the following default templates will only work in the root entity:
- Password forget
- Password expires alert
- Password initialization
- MySQL Synchronization
- CronTask
