### ISSUE TITLE
Error Invalid cookie data

### ISSUE THREAD

**Issue by hakihosting** [glpi-project/glpi#15303]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.9

### Bug description

when i navigate on the glpi , i am disconnected and have this error : 
Error Invalid cookie data

I need to relogin to have access again

**Comment by cedric-anne** [comment]
Hi,

This error happens when your session cookie has expired AND when the "remember me" token is not anymore valid.

If you use GLPI on different browsers/machines, as the "remember me" token is unique and regenerated on each machine, these present on any other machine are invalidated. This is a known limitation.
