### ISSUE TITLE
gui error when plugin install fails

### ISSUE THREAD

**Issue by ftoledo** [glpi-project/glpi#15392]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When there is a failure in the installation of a plugin, the error message is not displayed correctly.
It's not easy to see the problem or  copy and paste it.

![imagen](https://github.com/glpi-project/glpi/assets/95441/e6f65a62-d48b-4081-8e35-91262d9c2d1e)

**Comment by trasher** [comment]
Try if you reproduce with ltest stable release.

**Comment by cedric-anne** [comment]
Hi,

Error display is indeed not optimal here, but it is due to the fact that, in debug mode, the error message is sent to output at the moment it is triggered. We will probably change this in the future, but as debug mode is not expected to be used in production, we will not consider it as a bug.

The error trace can be found in `files/_log/php-errors.log`. As it is related to a plugin, you have to report it on the corresponding plugin issue tracker.
