### ISSUE TITLE
Start Date for contracts on Computer list

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#15689]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

When looking at the list of computers it's impossible to set the star date of a contract that might be related to the computer assets whether it is default personal, or default public view. I can just select the End Date.

In other asset lists, like Monitors, Data Centers, Enclosures, it is possible.

![image](https://github.com/glpi-project/glpi/assets/13874922/249fc52b-eaee-4373-8325-7a122e553bef)

Look on Monitor list
![image](https://github.com/glpi-project/glpi/assets/13874922/a089447e-2391-4c91-b71f-dee2c02ce636)

### Steps To reproduce

1. Go to Assets > Computers
2. Click on the icon to change the default personal, or global view
3. Look for Date under Contracts
4. There's no Start Date under Contracts

On other assets, you can set this up.

**Comment by 0xNath** [comment]
Hello,
I can reproduce the issue on glpi version "10.0.11-dev".

Here is a begin of explanations for what I think is the issue.

Contracts entries in the Monitors view :
```
[Contracts] => Array
(
    [139] => Location
    [29] => Name
    [30] => Number
    [129] => Type
    [130] => Duration
    [131] => Periodicity
    [132] => Start date
    [133] => Account number
    [134] => End date
    [135] => Notice
    [136] => Cost
    [137] => Invoice period
    [138] => Renewal
)
```

Contracts entries in the Computers view :
```
[Contracts] => Array
(
    [139] => Location
    [29] => Name
    [30] => Number
    [133] => Account number
    [134] => End date
    [135] => Notice
    [136] => Cost
    [137] => Invoice period
    [138] => Renewal
)
```


In the final list of options for computers we can see those :
```
...
[105] => monitor
[106] => 129
[107] => peripheral
[108] => 130
[109] => printer
[110] => 131
[111] => phone
[112] => 132
...
```

In _glpi/src/Search.php_ at line 8250 we have this  :
`self::$search[$itemtype] += Contract::getSearchOptionsToAdd();`

The key with value 129 to 132 from the Contracts don't get added because they already exists in the array.
If we reverse the order we don't get monitor and phone options but we get the Contracts : 
`self::$search[$itemtype] = Contract::getSearchOptionsToAdd() + self::$search[$itemtype];`
![image](https://github.com/glpi-project/glpi/assets/67143274/d8ee2e7a-038c-49f8-8d0f-7effa207c8e5)

It seems that those key value are principally used in the table "glpi_displaypreferences" to retain position of column in views, but I'm not able to determine why those number are specifically chosen and not some others, or if they are used elsewhere...
Could anyone enlighten me about this please ?
