### ISSUE TITLE
Consumables Alarm - Unable to select Technician/Group in charge of the Hardware as notification recipient.

### ISSUE THREAD

**Issue by TimmMateus** [glpi-project/glpi#15808]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Unable to select the 'Group in charge of the hardware' and 'Technician in charge of the hardware' as notification recipient for the consumable alarm.

Consumable example:
![image](https://github.com/glpi-project/glpi/assets/57238589/be076cd4-453d-4208-91f0-6253a32d53ee)

Recipients for consumables (does not appear):
![image](https://github.com/glpi-project/glpi/assets/57238589/1eefe845-3183-4b89-9ca0-bb1ed3a5895a)

Recipients for Certificates
![image](https://github.com/glpi-project/glpi/assets/57238589/4c9a06eb-4edf-4bf9-adc7-67a5194ff729)

### Relevant log output

```shell
N/A
```

**Comment by cedric-anne** [comment]
Hi,

This is not possible as notifications are sent for multiple objects at once, and each may have a different tech/group in charge. This feature is available for certificates since #11068. To be able to send notifications related to consumable to tech/group in charge, a similar change should be done, but not anyone is OK with this, as it may result in sending too many notifications at once.

Anyway, this is not a bug, but a missing feature.

**Comment by cedric-anne** [comment]
Similar to #13774.
