### ISSUE TITLE
Edition of items in timeline

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#159]
To open a followup or a task in this tab, you must double clic. 
Elsewhere in GLPI a single click enough.

**Comment by remicollet** [comment]
I agree simple clic should be enough. 
Double clic is not intuitive.

**Comment by vlegros** [comment]
Hello, I also agree that this is a bit confusing...

**Comment by orthagh** [comment]
*I removed tags of this issue waiting for a final decision and discussion*

I added this change in talk plugin (before glpi integration) because it's difficult to copy/paste text without opening edition form (frequent behavior in my support team, also i saw this in other companies).
On talk plugin integration, this behaviors stayed.

I disagree on "not intuitive" term. I think its more your usual usage.
I dislike simple clic in this case. It's a personnal view but i'll be sad to retrieve old behavior.
We can match other parts of glpi with simple click but i believe you'll disagree :).

I think we can do better on this part : 
* remove simple or double click on full body of fup/task
* add an edition icon (pencil)
* edition form appears inline 

Like this github page in fact.
If you agree on a test, i'll push a pr next week

**Comment by vlegros** [comment]
Seems ok to test the edit button


---- Alexandre Delaunay a écrit ----


I removed tags of this issue waiting for a final decision and discussion

I added this change in talk plugin (before glpi integration) because it's difficult to copy/paste text without opening edition form (frequent behavior in my support team, also i saw this in other companies).
On talk plugin integration, this behaviors stayed.

I disagree on "not intuitive" term. I think its more your usual usage.
I dislike simple clic in this case. It's a personnal view but i'll be sad to retrieve old behavior.
We can match other parts of glpi with simple click but i believe you'll disagree :).

I think we can do better on this part :

  *   remove simple or double click on full body of fup/task
  *   add an edition icon (pencil)
  *   edition form appears inline

Like this github page in fact.
If you agree on a test, i'll push a pr next week

**Comment by tomolimo** [comment]
Ok for I’ll prefer this version
And I’l ready to test ☺

tomolimo

**Comment by orthagh** [comment]
a proposal for this issue.
It change the following : 

- double click removed
- icon to edit item
- inline edition (before, it was on page top)
- a little review of involved forms (better organization)

@tomolimo, if you can review that ?

**Comment by tomolimo** [comment]
Yes, but not today, as I'am writing the form validation plugin wiki :smile: 
I'll do that tomorrow,

**Comment by orthagh** [comment]
Sure ^^

**Comment by orthagh** [comment]
Just added also 'mark as done' on task boxes

a preview : 
![image](https://cloud.githubusercontent.com/assets/418844/15677337/2898ae64-274a-11e6-832e-674fa28e6830.png)

**Comment by tomolimo** [comment]
We (@vlegros and me) validate the evolutions.
We have only one remark: could it be possible to enlarge the checkbox?
examples:
for information:
![image](https://cloud.githubusercontent.com/assets/7569958/15708540/4908d1f0-27ff-11e6-8821-8da72fbb8c61.png)

for done:
![image](https://cloud.githubusercontent.com/assets/7569958/15708589/940df162-27ff-11e6-8052-66a8ae211fb1.png)

for to do:
![image](https://cloud.githubusercontent.com/assets/7569958/15708643/ef356c32-27ff-11e6-98b7-a75544f70daa.png)

These are examples and can be (of course) modified.

thank you,
regards,
Tomolimo

**Comment by orthagh** [comment]
ok, i merge.
For information, i change icons for a better reading (as asked), but with less flashy design.

**Comment by orthagh** [comment]
#694 merged
