### ISSUE TITLE
Problem duration not added to ticket

### ISSUE THREAD

**Issue by boscorelly** [glpi-project/glpi#1593]
When you create a problem in a ticket, and when you create a task in the problem, the total time of the problem is updated, but the total time in the ticket is not updated.

It's a real problem because we are billing at spent time.

GLPI 9.1.1

**Comment by orthagh** [comment]
Hello @boscorelly .

I don't understand your need.
GLPI have a relation between ticket and problem.
With its itil model, tickets permits to do "bypassing" solution and problems definitives ones.
But theses objects have a different lifetime.

And tickets shouldn't impact total time of associated problems.

For the shortcut "Create a problem from this ticket", it's a copy (ticket's field to new problem), not an active link. After problem creation, the ticket didn't affect anymore.

**Comment by boscorelly** [comment]
when i create a ticket, i sometimes create problems in link with this ticket.
in the problems, i create tasks, with duration.
i need the duration of this tasks to be added in the ticket global duration, as it is when projects and tickets are linked

**Comment by orthagh** [comment]
You can't do that with glpi, (itil) problems are not designed to update tickets duration.
Project have indeed a possible link between their task and a ticket (and their duration) but it's not the same relation :

- Tickets could be linked to problem as they target the same "original cause"
- Projects can have tasks who could be managed by tickets

We won't add the behavior of project into problem (why have different object otherwise)

**Comment by boscorelly** [comment]
Et mon message en français ?...

**Comment by orthagh** [comment]
?

**Comment by boscorelly** [comment]
J'avais posté un long message en français, il a été supprimé...

**Comment by trasher** [comment]
No messages have been deleted; I've checked in my mails, I've not received any french message from you on this thread. A gihub bug or an issue with your browser/connection maybe?
