### ISSUE TITLE
[GLPI 10.0.10] Outlook and Caldav Synchronizer

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#16035]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.10

### Bug description

I've got the a problem with Outlook and Caldav Synchronizer since GLPI v10.0.x (v10.0.10 now).

I'm using Apache2 configured like recommended with "DocumentRoot /path/glpi/public" + directory "<Directory /var/www/html/glpi/public>" and the rewrite cond.

```
<Directory /var/www/html/glpi/public>
        Require all granted
        RewriteEngine On
        # Redirect all requests to GLPI router, unless file exists.
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ index.php [QSA,L]
</Directory>
```

I've got a 403 error on Caldav Synchronizer and this line on the access apache2 log file :
"PROPFIND /caldav.php/calendars/users/J.DUPONT/calendar/ HTTP/1.1" 403 2017 "-" "CalDavSynchronizer/4.4"

If i remove "public" on the DocumentRoot, Caldav Synchronizer works.

**Comment by Rom1-B** [comment]
It also seems to be linked to the presence of the dot in the login "J.DUPONT". A login without a dot seems to work.

**Comment by felag** [comment]
This issue seems present even with GLPi 10.0.11 including code fix.

@sina-4 Using guidelines from [this sabre-io issue](https://github.com/sabre-io/dav/issues/1336#issuecomment-811709335), after changing apache configuration to replace line:

`RewriteRule ^(.*)$ index.php [QSA,L]`

by

`RewriteRule ^(.*)$ index.php [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]`

@cedric-anne Is it possible to update installation documentation with such information (or is there another way to eventually fix this issue) ?

**Comment by cedric-anne** [comment]
> This issue seems present even with GLPi 10.0.11 including code fix.
> 
> @sina-4 Using guidelines from [this sabre-io issue](https://github.com/sabre-io/dav/issues/1336#issuecomment-811709335), after changing apache configuration to replace line:
> 
> `RewriteRule ^(.*)$ index.php [QSA,L]`
> 
> by
> 
> `RewriteRule ^(.*)$ index.php [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]`
> 
> @cedric-anne Is it possible to update installation documentation with such information (or is there another way to eventually fix this issue) ?

Hi,

Here is the documentation update proposal: https://github.com/glpi-project/doc-install/pull/94

Next time, feel free to create the pull request by yourself.
