### ISSUE TITLE
Computer history shows only new values

### ISSUE THREAD

**Issue by AldarisPale** [glpi-project/glpi#16257]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

As I was trying to tackle https://github.com/glpi-project/glpi/issues/16256 I arrived to a problem - history is being logged for assets, but the history shows only new values without showing what the old value was. This means that if something overrides a value, in this case glpiinventory or core, note sure which, and field being "Comments", it's impossible to know what was the previous value, making it impossible to restore the data.

### Your GLPI setup information

GLPI 10.0.11
GLPI GenericObject Plugin 2.14.8
GLPI Fields plugin 1.21.6
GLPI Inventory Plugin 1.3.4

### Anything else?

Although the case is about computer history, I expect the problem to be the same for everything which has a history tab.

**Comment by cconard96** [comment]
I cannot recreate the issue. Changing fields like "Inventory number" for a computer properly shows the old (if it was set before) and new values. For comments, the old and new values are stored properly, but neither are displayed in the history tab. That behavior is expected since comments can be very long. This could be improved, but it isn't a bug.

I didn't see any case where a new value was displayed, but not an old one except for when there was no old value.
