### ISSUE TITLE
[GLPI 9.1.1] PHP Notice: Undefined index

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#1654]
Good day.
With the inclusion of debug mode, displays the following notification. I would like to understand the criticality and impact on system performance.
If you can fix it?
![3](https://cloud.githubusercontent.com/assets/21122546/22107078/dbd7a4dc-de6d-11e6-9f9a-c75ab50048e2.jpg)

**Comment by trasher** [comment]
This may happen if during upgrade process the table `glpi_objectlocks` have been created but not the associated configuration options (because of an update crash).

At this point, this is not critical, you just have to save the default form for the values to be created. It may be a little more problematic on the use side; but it should just throws notices.
