### ISSUE TITLE
preselected as requester, impossible to clear

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#1736]
![peek 30-01-2017 17-40](https://cloud.githubusercontent.com/assets/418844/22431844/3ddc7dda-e713-11e6-8540-04df1c277bdc.gif)

**Comment by orthagh** [comment]
Precision, assignee and observer are not directly impacted by thi issue but after a category selection, theses fields are also reset.

**Comment by tomolimo** [comment]
for requester: If you chose someone else, it will be kept, the described behavior occurs only when you want to clear the field, **and** if you have set the 'pre-select me as requester' in your settings.
for observer: I can't reproduce the behavior you explained, nor for the technician
version used for tests 9.1/bugfixes

**Comment by nailyk-fr** [comment]
Yes, this problem seems to happens for requester and assignee but not observer. 
Assignee field is affected at reload time: 
1. set auto assign into settings, 
2. open new ticket form, 
3. select assignee to '-----'
4. change category

page is reloaded, assignee is back to preselected on. 

glpi 9.1.2

**Comment by nailyk-fr** [comment]
Wondering if https://github.com/glpi-project/glpi/commit/293c2bb11148188f062688f1054f06cba752f81d will not fix this too?
