### ISSUE TITLE
Business rules for tickets - "assign" action does not replace current actor, just add it

### ISSUE THREAD

**Issue by pablitobin** [glpi-project/glpi#17739]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

I have several Business Rules for Ticket to "assign" a watcher group based on ticket category. When a specific category is added, right group is "added" to Watcher field, but if Category is modified, the watcher actor should be replace with another group. Does not matter if in the business rule, i choose "assign" or "add" as action, the new actor is added and I have 2 groups in the Watcher field.

### Steps To reproduce

1. Create a ticket
2. assign "Category X"
3. (business rule assign "Group X" to "watcher"
4. modify Category to "Category Y"
5. (business rule adds "Group Y" to watcher field. I have 2 groups assigned now on Watcher field: "Group X" and "Group Y".

### Your GLPI setup information

GLPI 10.0.16 
Installation mode: TARBALL
Current language:en_GB

Operating system: Windows NT 
PHP 8.3.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date,
	dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, random, readline, session, soap, sodium, standard, sysvshm, tokenizer, xml, xmlreader, xmlwriter, zlib)
Setup: max_execution_time="0" memory_limit="2048M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" disable_functions="" 
Software: Apache/2.4.58 (Win64) PHP/8.3.9 OpenSSL/3.1.3 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 11.2.2-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	
PHP version (8.3.9) is supported.PHP version (8.3.9) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (11.2.2) is supported.Database engine version (11.2.2) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.

Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar. Following extensions are not present: zip.Following extensions are installed: bz2, Phar.
Following extensions are not present: zip.
Zend OPcache extension is not present.Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.

Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by Mgabr90** [comment]
## Local patch for GLPI 11.0.4

This issue is still present in GLPI 11.0.4. For anyone hitting this, here's a two-file patch that fixes it cleanly.

### Root cause

The problem is a two-function chain:

1. **`src/RuleCommonITILObject.php` — `executeActions()`**: the `"assign"` case correctly writes `$output['_groups_id_assign']` but never signals that the new value should *replace* the existing actor — it just adds to it.
2. **`src/CommonITILObject.php` — `updateActors()`**: additive-only by design; never removes existing group actors before adding the new one.

### Fix

**Patch 1 — `src/RuleCommonITILObject.php`**

In `executeActions()`, `case "assign":`, after setting the output value, flag which group fields should be replaced:

```php
if (in_array($action->fields["field"], ['_groups_id_assign', '_groups_id_requester', '_groups_id_observer'])) {
    if (!isset($output['_rule_replace_actor_groups'])) {
        $output['_rule_replace_actor_groups'] = [];
    }
    $output['_rule_replace_actor_groups'][] = $action->fields["field"];
}
```

Add this block right after the existing `$output[$action->fields["field"]] = $action->fields["value"];` line, before the `// Special case of status` comment.

**Patch 2 — `src/CommonITILObject.php`**

In `updateActors()`, after the `$existings = $this->getActorsForType($actor_type_value);` line, add:

```php
if (
    isset($this->input['_rule_replace_actor_groups'])
    && in_array('_groups_id_' . $actor_type, $this->input['_rule_replace_actor_groups'])
) {
    foreach ($existings as $existing) {
        if ($existing['itemtype'] === Group::class) {
            $actor_obj = $this->getActorObjectForItem(Group::class);
            $actor_obj->delete(['id' => $existing['id']]);
        }
    }
    $existings = $this->getActorsForType($actor_type_value); // reload after deletion
}
```

### Tested on

- GLPI 11.0.4, PHP 8.3, MariaDB
- Created a ticket under category **SAP S4/Hana > MM** → business rule assigned group **SAP Consultants**
- Changed category to **SAP S4/Hana > SD** → business rule fired on update
- **Result**: only **SD Consultant** group remained — old group correctly removed ✅

The fix works by passing a `_rule_replace_actor_groups` flag through the input array so `updateActors()` knows to delete existing group actors of that type before applying the new assignment, rather than stacking on top.
