### ISSUE TITLE
Add anonymous watcher from mail

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1779]
http://forum.glpi-project.org/viewtopic.php?id=156566
http://forum.glpi-project.org/viewtopic.php?id=37347

**Comment by hmrito** [comment]
Any advance on this subject? I realy think is a big miss dont have anonymous watchers...

**Comment by stdglpi** [comment]
Like said @hmrito and others on the forum if a parameter can be added, 

Some people use more the "anonymous" heldesk than the intern GLPI mod.

Otherwise, the anonyme user has to say in the mail or by phone he wants that someone to be part of the watcher.

they think it's a simple option that should be considered.

Thanks for all !
