### ISSUE TITLE
help please downgrade glpi 9.2 to 9.1.2

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1894]
Hello

I have many issues on glpi 9.2 no task template, no view of computers in super admin, ticket created many times

how can I do ? because the database is 9.2

**Comment by trasher** [comment]
There is no downgrade possible. You should have used the current stable version as stated... Almost everywhere.

**Comment by trasher** [comment]
BTW, you already have issues just because you did not upgrade your database; it may be once again the reason to the issues you're the only one to see.

**Comment by satyan01** [comment]
So I have to wait the new 9.2 release stable

**Comment by trasher** [comment]
I guess so. But as you have a database in an unstable state, you may still have unpredictable issues.

You really should follow database upgrades very carefully working on a development version.

**Comment by satyan01** [comment]
How Can I copy database content without error ?

**Comment by satyan01** [comment]
maybe I can send you my database to check

**Comment by remicollet** [comment]
> maybe I can send you my database to check

Seriously ?

**Comment by satyan01** [comment]
yes, Why ?

**Comment by wawax** [comment]
Hi,

A dev version is not to use in production, we're not going to do anything to help you on that kind of issue.

**Comment by satyan01** [comment]
ok thank you for your help

**Comment by RubenYisuscraist** [comment]
same issue here, but I downloaded 9.2.2 which **is actually a stable version** according to GLPI's webpage.
I'm trying to downgrade to 9.1.6 due to csv importation doesn't work on 9.2.2, keep getting this message: 

Run "composer install --no-dev" in the glpi tree

any suggestion? already tried that and did not work.

Thanks everyone in advanced, regards from Argentina.
