### ISSUE TITLE
[9.1.2] error when adding actor

### ISSUE THREAD

**Issue by sebfun** [glpi-project/glpi#2030]
Hi there

When adding an actor in GLPI 9.1.2 an existing ticket in sender's field (without removing the existing one), it correctly adds the actor but i click on "save" it reloads the page and adds a non existing actor.
Also I can't remove it, it says "Unauthorized access" (even I have Super Admin profile)

Take a look at the screenshot please : http://www.cjoint.com/c/GDmiyXnGZZk

Thanks

Sébastien

**Comment by trasher** [comment]
I cannot reproduce on current 9.1/bugfixes branch. Either the issue has been resolved, or there is something else that goes wrong.

Do you have any entries in the log files when you got this issue?

**Comment by trasher** [comment]
This duplicates #1806

**Comment by tomolimo** [comment]
Hello,
I got the same, when adding an actor in the requester list, then I got an empty actor with ID equals to '0'.
I found that it was due to a new business rule recently added.
I just de-activated this rule, and the issue was fixed.
The rule was about  automatically assigning a SLA to a ticket when it was about a certain entity
regards,
Tomolimo

**Comment by trasher** [comment]
Thanks for the precisions! I was failing to reproduce; will try with a rule.
