### ISSUE TITLE
Can't search netpoints

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#2138]
1. Go to any asset.
2. Select: **Networking - Network outlet**
3. And search.

If you type something to search you'll get "No item found", if not the column is blank.

GLPI version: 9.1.3.

**Comment by trasher** [comment]
Indeed... The problem is the serach is done only on fiber channel network ports actually; that overrides ethernet network ports (in the complexity of the search engine).

Do not know yet if it will be possible to have this search working (this should work on both fiber channel and ethernet).
An alternative would be to add two options (search on ethernet network outlets and search on fiber channel network outlets).
