### ISSUE TITLE
Search engine user form multi groups

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2260]
http://forum.glpi-project.org/viewtopic.php?id=157840

**Comment by iamc** [comment]
(I'm the original poster of the issue)

Also, and this may be related, I observed that as you filter users by eg. "groups is group1", in the resulting filtered list, filtered users appear as belonging **only** to this one "group1". Thus, further filtering relating to groups will of course not work properly.

I guess this should be related to users and groups having a many-to-many relationship, thing that does not typically occurs with other fields. But my database knowledge is very superficial, so this is just a wild guess.

**Comment by trasher** [comment]
I can replicate the original issue; but not what you added in your comment.

Found users belongs to the searched group; even if they also belongs to other groups.

**Comment by iPaulis** [comment]
When users are filtered as "Group is X", the list shows the users that belong to that group, and as you say, they are shown in the list even if they also belong to other groups. But the column wont show what other groups they belong to, so it seems they only belong to the searched group.
I hope you can replicate this too now, although I don't know if that behavior can be related to the original issue or not.

**Comment by trasher** [comment]
@iPaulis indeed; search results are correct; but the column in the table only shows searched group; thanks for the clarifications.

This is not strictly a bug, and this is not really related to the original issue. Fixing that my cause issues; what if the user belongs to 100 groups? They cannot be listed entirely and I don't think we actually have anything to handle that cases properly.

**Comment by iPaulis** [comment]
Well, if it is a different thing, no problem. I just thought that behavior was a bit misleading. Anyway, if the user belongs to 100 groups, the same problem would happen now in an unfiltered list of users in the group column. The same behavior applies to the email field which can be various too. 
In any case, in an unfiltered list, all of the emails or all of the groups show up in their respective columns, it is only if you filter by them when you can only see the one that you searched for, but not the rest of the info of those columns for the filtered users. 
I think this is a conceptual error, as the User section should show all the information regarding users, even if the results are filtered by a field with multiple simultaneous options, otherwise we are forced to click in the user details to see the info that the column itself should contain.

**Comment by iPaulis** [comment]
I am not completely sure, but this might also be related to the original issue. 
When I try to filter by groups, if there are users who belong to groups A and B, and the filter condition is GROUP IS NOT B, it does not filter them. 
The search result shows all users as long as they belong to a group different to B, even the users belonging to B are shown if they also belong to another group. 
So in practice, the filter does not filter at all, because users belonging to several groups at once is very common.
Can anyone else confirm?
