### ISSUE TITLE
[DISCUSSION] Schema from class docblock

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#2397]
Here is my new stupid idea ;)

Experimental work in https://github.com/glpi-project/glpi/tree/glpi-schema-docblock

Having a better knowledge of the table schema will allow some improvement.
* create table from schema

```
 $query = $migration->getCreateTable('DeviceGenericType');
 $DB->queryOrDie($query, "9.2 add table glpi_devicegenerictypes");
```

* update table from scheme
* better add/update colum
* empty.sql only used for data (everything else created from schema)
* more work toward DB format independency
* etc

**Comment by trasher** [comment]
As I've commented on the code; this should not be used in the update scripts. This would cause current update to fail in the future, when table schema has changed.

**Comment by remicollet** [comment]
TODO: add checkSchema method (and expose it in tools/schema.php) to compare DB schema and expected one.

**Comment by ddurieux** [comment]
I really prefer have a function `get_schema` or something like this than use class docblock.
The docblock is for documentation, so we must not use it as code generation

**Comment by trasher** [comment]
A huge monolitic method would be hard to maintain/read.

And... Well database schema in the documentation is documentation, It would help to know which fields are defined and how while working in a class (rather than look to the empty.sql file or something similar).

Since the phpdoc generators will totally ignore what they do not know about; this is not a technical problem.

**Comment by cconard96** [comment]
Why not use a proper ORM like Doctrine instead of trying to mimic one in GLPI using PHPDocs? Even if it doesn't seem handle polymorphic relations (itemtype + items_id relation where itemtype could be anything) well, it is more than capable of tracking schemas and creating migrations. There may be better alternative ORMs than that too, but Doctrine is the one I have experience with.

It solves many issues I have with GLPI currently:
1. I have no idea what should be in the fields array (or what type it should be) without looking in the DB and hoping everything is populated right. With Doctrine:
```
/**
 * The item's name
 * @var string
 * @ORM\Column(type="string", length=255)
 */
private $name;
```
You know exactly what fields the itemtype has and the DB information for each. It should say a lot that I felt it was worth making a plugin that lets me view the DB schema for classes (and search options but I won't rant about the issues I have with the Search system here...).

2. No good way to create proper sub-types for itemtypes (mainly assets). In Doctrine you keep common fields in a parent class and add `@MappedSuperclass` annotation to the class. All classes that extends that parent will inherit those fields and Doctrine is smart enough to take that into account when handling schema updates.

3. No good way to add "features" or "behaviors" to classes without copy-pasting code. If any change is made that alters that behavior, you need to find every class that uses it, even plugins, and make changes there. Many itemtypes in GLPI share behaviors like having timestamps (creation, modification), being trashable, having a location, ability to have notes, etc. Having an ORM makes it easier to create Traits like "Timestampable", "Locatable", "Noteable", etc and adding the shared fields there instead of every class. By the way, it is very easy to have Doctrine manage the creation and modification date fields on its own.

4. No good way to update DB between development commits. I must search for and make the needed changes manually, or add `$_GET['donotcheckversion']` in `config.php` if I don't plan to work on anything related. Unfortunately I end up doing the latter more often than not because that blocking "You are trying to update to a development version" warning is very annoying when switching branches. I just keep that file unstaged. I don't have time or patience to manually fix the DB every time or set up a new DB for every fix/feature on the same major version I work on. I've had almost no issues running 'bin/console doctrine:schema:update --force' in a Symfony application to do delta updates to the DB. Plus, I can use `--dump-sql` instead of `--force` to see what actually changes before committing. The only time I've had issues with Doctrine not being able to update the DB was when a ton of foreign key constraints were added and it tried applying them out of order. Seeing as GLPI doesn't actually add FKs to the DB, that is a non-issue and that even invalidates the polymorphic restriction I mentioned earlier.

5. No way to lazy-load relation data. If I get a user from the DB and want to get information about the location in some cases but not others, I either need to get that data using the initial query adding extra processing time in all cases, or add a second DB call which can be messy. Doctrine supports lazy associations. The first time you access the association (like $user->location) it loads the required data.

Not saying Doctrine is a good way to go, just that adding an already established ORM is my recommendation even if we don't end up using all of the features it offers. It would certainly work better then adding custom solution after custom solution to try and mimic one. I know a lot of work went into the current DB iterator system, but it seems that an ORM would fix a lot of frustrations and add many wanted features are the same time. There may even be a way to use the current query system in conjunction with an ORM even if it is just to ensure BC.

Doctrine also adds:
- Query caching (When using DQL). The GLPI query-as-array solution does not do this and must parse the array every time it is used.
- An intuitive query builder and custom query language
- Event system (Relating to DB record lifecycle actions like remove and persist)
- Multiple sources of metadata like PHPDoc, XML, or PHP code
- Supports MySQL, MariaDB, Oracle, Microsoft SQL Server, PostgeSQL, SQLite, and more.
- Built-in pagination
