### ISSUE TITLE
Mail Receiver Error.  PHP Warning imap_open()

### ISSUE THREAD

**Issue by virginiacorrea** [glpi-project/glpi#2523]
Good day.

I was unable to enable the mail receiver option. I get the following error: PHP Warning: imap_open (): Could not open stream {ipserver: 993} in /var/www/glpi/inc/mailcollector.class.php at line 1060

I have already done it with imap, ssl {ipserver: 993 / imap / ssl} and other multiple options however the error persists. The server I'm going to connect to is exchange.

The strange thing is that running tests with gmail {imap.gmail.com:993/imap/ssl} works ok.

The server exchange has the SMTP and TCP IMAP 993 ports enabled.

Anyone have an idea that may be happening?

Thank you.

**Comment by roshanroche** [comment]
Dear @virginiacorrea ,
i have configured Receivers on glpi to fetch mails from exchange, following is the setup hope it might help you,
Name (Email address) - email id from which u want to fetch mail 
Active  - yes
Server - exchange server IP or FQDN (eg: mail.yourdomain.com )
Connection options - POP , SSL , NO-TLS , NO VALIDATE CERT , ---  , --- , ----
![image](https://user-images.githubusercontent.com/22425503/28654269-0b370dec-72a4-11e7-8ff1-004ef7ac4aa2.png)
Incoming mail folder (optional, often INBOX) - leave it blank as it will search Inbox by default
Port - 995
Connection string - it will automatically create based on values u give above
![image](https://user-images.githubusercontent.com/22425503/28654331-79e5dd2c-72a4-11e7-8ec0-84e458617ae5.png)
Login - username@yourdomain.com ( login of account from which u want to import mails )
Password - password of the account
Use Kerberos authentication - NO
Maximum size of each file imported by the mails receiver - Desired size 
Use mail date, instead of collect one - Yes
Then Save
Action - Click Get Email Tickets now
it should work.
this setup is on GLPI 9.1 onwards should work on 9.1.6 also.

**Comment by virginiacorrea** [comment]
Thanks roshanroche :)

I did the indicated configuration but it still does not work ... I get the same error ...

![php warning](https://user-images.githubusercontent.com/16838689/28691051-1c79bdce-72e1-11e7-8d11-50a4609a32e5.png)


Could something be disabled in Exchange, or some configuration?

I do not know what may be happening.

Thank you very much for your attention. Good day!

**Comment by virginiacorrea** [comment]
Version glpi 090.1 Although tested with 9.1.1 and same message

**Comment by Armin83** [comment]
- pop and 993 is wrong please select imap.
- can you try "telnet exhange-server-fqdn 993" - if you got a blank window it is correct - if you got error message your exchange server configuration is wrong

**Comment by roshanroche** [comment]
@virginiacorrea ,
sorry there was a typo. port is 995 not 993. can u check with that?

**Comment by virginiacorrea** [comment]
Hi.

Still not working. :(
![image](https://user-images.githubusercontent.com/16838689/28827706-04733d98-7694-11e7-9a54-17827a4046b4.png)

![image](https://user-images.githubusercontent.com/16838689/28827679-ef527db6-7693-11e7-8df1-7e28cec9a9ba.png)

**Comment by virginiacorrea** [comment]
When retrieving mail, it appears that the mail server could not be connected.

I'm still in trouble ...

Thank you very much for your answers and attention to my problem.

**Comment by TICgal** [comment]
Hola Virginia :)

Do you have access to this email account from another mail client? 
Test your configuration with Thunderbird for instance. Once you get access to the mailbox, just use same settings in GLPi.

My guess is an Exchange related issue. Not a GLPi one.

Saludos

**Comment by ProEdgeMaster** [comment]
Hello,

In some case Exchange don't have imap or pop activated by default.
Like user Ticgal comment, test on Mozilla thunderbird.

If this test fail, go to your exchange server and activate imap and pop.

Tutorial: How to enable this services: http://www.vkernel.ro/blog/enable-pop3-an-imap-access-in-exchange-2010

I recommend the usage of imap protocol only. 


Best regards,
     Filipe Figueiredo

**Comment by Armin83** [comment]
If you install a "new" ms exchange the default setting for imap is disabled. i don't know about pop.
"new" since exchange 2010

**Comment by virginiacorrea** [comment]
Hello

I have reviewed almost all the options that have given me (except exchange since it is in the process of validating the POP and IMAP enablement since I do not have the administration) and I have not been able to solve the inconvenience.

Testing, now it happens that the page is blank and if I repeat the apache step it restarts. I have tried with several scenarios and nothing. It only works with gmail, without problems, whose connection string used is {imap.gmail.com:993/imap/ssl}

I have verified and ports are enabled (telnet)
I have not been able to install thunderbird so far due to restrictions. However the account I tried also with outlook with POP 995 that is enabled and works ok in outlook, but in GLPI does not work.

![image](https://user-images.githubusercontent.com/16838689/29085408-d66de23a-7c34-11e7-9e89-ad75bef96a63.png)

I do not know what else to try :( I'm doing wrong, or what it takes ... :( :(

**Comment by virginiacorrea** [comment]
With what I'm testing while responding to pop and imap exchange, it's with open source zimbra. As I indicated I have configured outlook with this account and it works ok but in glpi nothing.

**Comment by trasher** [comment]
It seems that this issue is not related to GLPI; closing

**Comment by a026347** [comment]
Hi virginia, 
I have the same error when i tried setup receive connector on GLPI. 
I was trying with Gmail account, and works fine, but when i'm trying with exchage server IMAP or POP, does not working. Does you have any solution? 

Tanks
