### ISSUE TITLE
[9.2] Need to correcting translations

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#2846]
Hello,
You need to correct translations.

![glpi - plugins](https://user-images.githubusercontent.com/17082164/30907610-c12ec850-a383-11e7-9f7a-72db9fb1b7f9.png)

Please, don't close the issue while I find no translation words.

**Comment by trasher** [comment]
Those strings cannot be translated before 9.2; and they're related to plugins anyways.

I'm closing this one since this is not relevant.

For other translations issues, please open one issue for all at once then. Trying to remember which part of what you declared is fixed or not would be a nightmare; and we close tickets as they're resolved.
