### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2915]
Many functions are indicated deprecated for 9.2 but still used in this version.

A function must be clean in the core before indicated deprecated. This information is for plugins.

New use is more complex and functions in DbUtils must be static

**Comment by remicollet** [comment]
+1

**Comment by Armin83** [comment]
there is one in notification (for savedsearches_alert) https://github.com/glpi-project/glpi/issues/2807

**Comment by trasher** [comment]
The goal is to drop static methods. Usage will be officially deprecated once we have integrated a dependency injection system.

Deprecation has been added in 9.2; non static methods was required for unit tests; and those ones will be really deprecated quite soon.

**Comment by yllen** [comment]
why do you want to add a dependency injection system?

**Comment by orthagh** [comment]
> why do you want to add a dependency injection system?

Because it's a popular and better design than using globals
A lot of php applications uses it, and it simplify a lot of things.

>  Where can i see roadmap of core decided by Teclib?

I think it's not relevant with the discussion, but actually nowhere.
We try, like other contributors, to improve the product and its framework.
So we work with iterative steps, like in the past, i think.
But if you need vision, here the medium term tasklist of things we want by priority:
- better (full ?) test coverage of core (implies some restructuration like the one you mention). It's a strong priority for us.
- pdo connection.
- get rid of html/javascript mixed/concatened) into controller class.

By the way, on the current subject, i grumbled also that declaring an instance (rather static) for utility functions is not an enhancement on dev usage. @trasher needed it for adding new tests and as the old functions work actually as "Facades", i think it was ok at the moment.

So, i think the is we added the word @deprecated (no warnings btw) into the old functions.
Maybe we could keep them as facade for the new class and avoid deprecating them.

**Comment by remicollet** [comment]
>> Where can i see roadmap of core decided by Teclib?

> I think it's not relevant with the discussion, but actually nowhere.

It is, as it explains community frustration about such "unexplained" changes.

We really need such orientation to be explained
- on dev mailing-list
- on some web roadmap


> Maybe we could keep them as facade for the new class and avoid deprecating them.

Perhaps allow: 

`$nb = Dbutils::factory()->countElementsinTable($table);`

BTW, still quite ugly

**Comment by orthagh** [comment]
> We really need such orientation to be explained
> 
> * on dev mailing-list
> * on some web roadmap

Ok maybe, it was too in our heads for next steps, sorry for that.

I quickly started a page here:
https://github.com/glpi-project/glpi/projects/2

I'll try to complete it in next days.
This issues in progress (or not) could still be discussed.

> BTW, still quite ugly

+1, i still think we don't to depreciates these function, the need in tests suite was to have non static method, but core could still call static ones, i think
