### ISSUE TITLE
[9.2] Issue on display editing solution

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#2917]
Hello,

When I add a solution in Processing ticket, I can't add it to KB. For exemple : 

![image](https://user-images.githubusercontent.com/12936546/31264766-7c9887d2-aa6b-11e7-8145-59f49e92eb79.png)

I sav It : 

![image](https://user-images.githubusercontent.com/12936546/31264773-86c976e4-aa6b-11e7-872d-09fb13ce6ba9.png)

But : 
![image](https://user-images.githubusercontent.com/12936546/31264777-8daedd1e-aa6b-11e7-8620-f1c6a003d201.png)

And I see that the solution container is not correctly placed, It is on the left side and "cutted" : 

![image](https://user-images.githubusercontent.com/12936546/31264804-a7ce6f48-aa6b-11e7-952d-686277a78af8.png)

Thanks for your help !!!

**Comment by trasher** [comment]
I'm not sure I understand.

First of all, there were a JS issue on KB entry storage this way; it's been fixed in 741a742eb54042b30c619d8d43838b11ee3b8197.

Second, adding an entry in the KB from a solution does not make any link between KB entry and ticket/solution.
Ability to link that way has been added for 9.1.2 (see f3c6ca47e33c35a85429359cc058f109c29a9230); this will link created KB entry to the ticket, just like any KB link (so, not related to solution).

As of the placement issue; I have no problems on my side. When do you get the problem? Just clicking the "Solution" button in the processing ticket tab? Also, what browser are you using?

**Comment by ciadch** [comment]
I @trasher,

Effectively, the JS issue correct this bug, it's OK for me like that.

The position problem is when I click the button on the processing ticket tab : 

![image](https://user-images.githubusercontent.com/12936546/31277472-6b0cde42-aaa1-11e7-9b45-40d38dc6fb45.png)


Afer I have this behaviour in Chrome and Firefox : 

![image](https://user-images.githubusercontent.com/12936546/31277441-474093aa-aaa1-11e7-80e5-02056d8ca01a.png)

**Comment by trasher** [comment]
OK... I do not have the edit icon during my tests; I'll try to find out why.

**Comment by ciadch** [comment]
Perfect ! Thanks

**Comment by trasher** [comment]
Just a small CSS issue; see PR #2940
