### ISSUE TITLE
Notification for certificats

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2975]
http://forum.glpi-project.org/viewtopic.php?id=159320

Why notification is send after expiration and not before to have time to renew it?

**Comment by bern2b** [comment]
Effectively, since version 9.2 and the integration of certificate management, the certificate notification function will only alert us when the certificate has expired. It is no longer possible, as in the plugin, to be notified before expiration. This is however essential for a good anticipation.

Could you make a correction ? 

Thank you

(sorry for my English level)

**Comment by yllen** [comment]
Notification are correct. See https://github.com/glpi-project/glpi/issues/2983
