### ISSUE TITLE
why glpi don't import some mails?

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#2987]
why glpi don't import some mails?
can i know the reason?
thanks

**Comment by Armin83** [comment]
this depends on default rules or your rules you created in this section:
Home - Administration - RulesRules for assigni... 

Home - Setup - receivers
you can click on "List of not imported emails". I think you "SHOULD" see the mails there.

**Comment by sferia82** [comment]
in this link i see emails. i don't know why.
otherwise sometimes the mailgate don't import mails and if i disable this rule begin import:

**Rules for assigning a ticket created through a mails receiver**

the rule that if a disable begin work is 👍 
rule --> root. 


Criteria
--

  | Subject email header | regular expression matches | /.*/

ACTION:
  | Entity | Assign | Root entity


sometimes with this rule disable don't import until i enable it.


i don't know the function of this rule but it doesn't work.


thanks.

**Comment by cedric-anne** [comment]
Hi,

The mail collector requires that rule engine defines on which entity the ticket should be created. This rule is a base rule that is made to assign all tickets from collector to root entity. If you want to manage multiple entities, you have to create your own rules.

As your problem is not due to a bug but to a configuration issue, I close it. Please use forum for community support.

Regards

**Comment by dssgla** [comment]
Setup --> General --> Asistance

Allow anonymous ticket creation (helpdesk.receiver) :  No (Default)   --> Change to YES

**Comment by mls2018** [comment]
thanks dssgla

**Comment by monish2222** [comment]
i done all of above tricks but still iam didnt receive mails why ?

**Comment by cedric-anne** [comment]
> i done all of above tricks but still iam didnt receive mails why ?

This issue is closed from a while. Please open a new issue if you encounter a bug in 9.5.x version of GLPI.
