### ISSUE TITLE
TicketValidation

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3088]
When i answer to a validation, global state is not change.
I can refuse a validation an put global state to accept.

In 9.1.x when you answer to a validation, global status change and it is display as text, not as dropdown

**Comment by orthagh** [comment]
As checking the current code (and as it doesn't evolved very much since years): 

- after a validation answer, global validation state changes only when it was set previously to WAITING
- global WAITING state is set after a validation is added but when the previous global state was ACCEPTED or NONE.
- when a validation is purged, the global STATE is set to NONE when previous global state was set to WAITING
- as readonly global validation field, in 9.1 (like 9.2), it's not the state which controls this, but the right to add validation (CREATEREQUEST, CREATEINCIDENT) and recently the right to update the ticket (see https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/ticket.class.php?utf8=%E2%9C%93#L4935-L4936)

Let me know if i miss something, but all my current tests validate these statement, no ?


Also, for history, here is the recent list of changes which impacted this part (desc order):
- https://github.com/glpi-project/glpi/commit/1f73968428c
- https://github.com/glpi-project/glpi/commit/81c71fc0d7a80db6e172e9605914232566aa107b

**Comment by yllen** [comment]
I think i understand.
In my profile i have NO right to validation a ticket.
So global validation is displayed as text.
But i can click on a validation in the list under and change it.
In this case button to save or purge will not be present.

**Comment by orthagh** [comment]
Currently, to validate a validation request , you just need to be user specified in the validators_id field.
Checked in multiple locations:

https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/commonitilvalidation.class.php#L159
https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/commonitilvalidation.class.php#L175
https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/commonitilvalidation.class.php#L920

If you are on the wrong profile (without validations rights), you still able to validate those affected to you

The rights VALIDATEREQUEST & VALIDATEINCIDENT are checked only at the moment where a user request a validation. Only users with a profiles which contains these rights are listed in the dropdown.

i think, we can't change this behavior, but maybe, in ticket form, we can also check the global validation readonly state with ``TicketValidation::canValidate($tickets_id)``.

What do you think ?
