### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#3270]
Font Awesome version 5 has just been released.

Need to checks size, compatibility, what their new deign would look, and the amount of required work to switch.

**Comment by orthagh** [comment]
https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by cconard96** [comment]
@trasher 
The upgrade is mostly compatible and about the same size if we can remove unneeded fonts like the brands fonts (Extra 1 MB otherwise). Some icons like the trash icon used before is now pro and had to be changed. Others have different looks by default.

See https://github.com/cconard96/glpi/tree/feature/fa5 for POC. I can open a PR if you want, but more testing will need done to make sure I didn't miss any icons that are broken.

**Comment by orthagh** [comment]
@cconard96 publish your poc in pr.
We will test it.

**Comment by AnaelMobilia** [comment]
@trasher : I think this issue could now be closed (#4491 ) ;-)
Regards,
Anael
