### ISSUE TITLE
[9.1.4-9.4.5] Add watcher rule replace added watcher but not email

### ISSUE THREAD

**Issue by CCoruble** [glpi-project/glpi#3468]
Hello,

### Context:
using glpi on ubuntu 16.04, we have rules on some entities to automatically add someone as a watcher.
Watcher added from rules are added ONLY AFTER ticket is created, they are not added before clicking on "add".

### Problem:
If we go on "create a ticket" interface, in an entity that has a a rule to automatically add a watcher, add a watcher then click "add". Manually added watcher is overwritten by automatically added watcher, BUT when a mail is sent, for a new followup for example, when cheking queued mail, the mail got the username of the automatically added user BUT the email address where the mail will be sent is the one of the manually added user.

### Example / step to reproduce:
**2 users:**
- name: "userAuto" email: "userAuto@mail"
- name: "userMan" email: "userMan@mail"
**Steps:**
I have a rule on "root" entity that add "userAuto" as a watcher on each ticket created in "root" entity.
I click on "create ticket", interface appear and I choose "userMan" as a watcher.
At this step ticket is not created yet, I only defined parameters of it.
I click on "add", ticket is created, watcher is now "userAuto".
I add a follow "test followup", I go to "queued mail list" I click on the one that is supposed to be sent to "userAuto".
Queued mail details are: 
"Recipient name userAuto"
"Recipient email address userMan@mail"
And the mail is sent to "userMan@mail".

### What should happen
"userMan" should not be removed from watchers, "userAuto" should be added.
When a mail is sent because of a followup (or any event that send email), 2 mails are supposed to be sent, one to "userMan" and one to "userAuto"

Sorry if I was unclear about the problem, don't hesitate ask for more details.
Thank you in advance,
Best regards.

**Comment by tomolimo** [comment]
Hello,

This issue is still existing in GLPI 9.2 and 9.4.5
Here are the steps to reproduce it:

1. Import attached rules.xml file in [rules.zip](https://github.com/glpi-project/glpi/files/4029915/rules.zip). That will create a rule to assign 'normal' user as watcher when ticket is incident.
1. Add email addresses to 'normal' and 'post-only' user like following: 
![image](https://user-images.githubusercontent.com/7569958/71885721-362d6e80-313b-11ea-98d2-840f87aa87f5.png)
1. Enable notifications: enable followups and enable followups via emails like shown below: 
![image](https://user-images.githubusercontent.com/7569958/71885832-74c32900-313b-11ea-9d03-523917924a6f.png)
1. Create an incident ticket: set 'post-only' user as watcher, set title and description, see below: 
![image](https://user-images.githubusercontent.com/7569958/71886352-5873bc00-313c-11ea-8b02-5f5e0765b327.png)
1. Save the ticket.
1. Open the newly created ticket, and see that 'post-only' is replaced by 'normal' user: that's OK, the rule is doing the replace of the existing watcher,
1. But emails will be sent to 'post-only' user as the alternative_email is set to post-only@glpi.com, see below: 
![image](https://user-images.githubusercontent.com/7569958/71886143-f9ae4280-313b-11ea-9fdb-498eeb9122e2.png)

Regards,
Tomolimo

**Comment by tomolimo** [comment]
This issue is also existing for assigned technician...
