### ISSUE TITLE
Email Followups are not delivered

### ISSUE THREAD

**Issue by alexeymapper** [glpi-project/glpi#3598]
Situation: Follow up emails are not delivered (ticket creation emails are delivered correctly).
version: 0.90.5 (same with 9.1.7.1 which migrated from 0.90.5).

Steps to reproduce:
1. Add followup to someones ticket
1. Notice that owner of the ticket have not got email about follow up.

*php-errors.log*
```
2018-02-21 16:32:31 [83@b.company]
  *** PHP Notice(8): Undefined index: requesttypes_id
  Backtrace :
  inc/notificationtargetticket.class.php:533
  ...otificationtargetcommonitilobject.class.php:597 NotificationTargetTicket->getDatasForObject()
  inc/notificationtarget.class.php:1073              NotificationTargetCommonITILObject->getDatasForTemplate()
  inc/notificationtemplate.class.php:240             NotificationTarget->getForTemplate()
  inc/notificationevent.class.php:170                NotificationTemplate->getTemplateByLanguage()
  inc/ticket.class.php:1244                          NotificationEvent::raiseEvent()
  inc/commondbtm.class.php:1147                      Ticket->post_updateItem()
  front/ticket.form.php:69                           CommonDBTM->update()
```

**Comment by trasher** [comment]
There are several existing tickets talking about that. Did you check if your issue has not yet been reported?

**Comment by alexeymapper** [comment]
Checked up all all tickets with  requesttypes_id and notification delivery problems. Looks like this issue is new.
![image](https://user-images.githubusercontent.com/26652790/36486249-254ce56e-172f-11e8-8a08-ec1a77b03dfa.png)

**Comment by alexeymapper** [comment]
Do i need to provide additional info?

**Comment by alexeymapper** [comment]
I have manually created *requesttypes_id* in corresponding table (according to file mentioned in error).

Now i see that there is no more php errors. But still notifications are not delivered. As i see in **mail.log**, an emails was added to queue. But no mails coming.

**Comment by orthagh** [comment]
Hello @alexeymapper 

Mail queue is a feature since long time in glpi.
All notifications are appended to it, you can see them in Administration > Notification queue.

Also, an automatic action triggers the real mail send.
You could check it in `Setup > Automatic action, queuednotification`.
This action can be setup with the following mode:
- glpi: user actions in glpi triggers the automatic action
- cli: an external system (linux cron for example) call the automatic action script (front/cron.php) 

So if you're in cli mode but without the planned launch of the script, your notification will never be send.

Nota: notification for ticket creation bypass the queue (historical reason mainly)

**Comment by trasher** [comment]
No feedback, closing.
