### ISSUE TITLE
Attach Files function is not working for multiple files

### ISSUE THREAD

**Issue by diegomacedodasilva** [glpi-project/glpi#3604]
The attach file function is not working for multiple files.

When we try to select more than one file to upload, only the 1st file is attached.

**Comment by diegomacedodasilva** [comment]
GLPI version 9.2.1

**Comment by orthagh** [comment]
Hello @diegomacedodasilva 

Could you precise where you want to attach a file ? Ticket, Knowbase, direct document ?
Also precise the browser and os you are using.

And finaly, check if you fin any relative errors in glpi/_logs/*.log files.

**Comment by edgardmessias** [comment]
Maybe solver in GLPI 9.2.2, see #2713

**Comment by trasher** [comment]
No feedback from requester; closing

**Comment by ConteZero** [comment]
It's not possible to select multiple files in file dialog on document.form.php
#2713 doesn't solve the problem for Add Document page (it looks like it's a known limitation)
From an user point of view it's seen as a bug because on other parts of GLPI you can use the multiple upload feature but you can't use on the Document page, here you have to upload files one by one.

**Comment by trasher** [comment]
Original requester was talking about a bug, you're talking about an inconsistency in the UI; this is not exactly the same.
Feel free to open a pull request to fix that, or add an entry on the suggestion website (as I think this is a RFE).

**Comment by ConteZero** [comment]
My personal opinion is that an usability problem should be considered as a bug, because application end users see them as bugs.
Currently I'm considering whether or not to use GLPI for one of my projects, so I have not enough knowledge of GLPI code to write a fix.
Reading #2713 I have the impression that it's not an easy change to do (otherwise it would have been done on that pull request).
As a side note GLPI looks like a great software, the most important "feature" that is missing in my opinion is tracked by #4594 and I hope that it will be implemented in next major version.
Thanks anyway for your reply.

**Comment by trasher** [comment]
> that it's not an easy change to do

Probably not... That's why I want to point the difference between a "bug" that really cause an error and something "less" problematic. But I agree, in facts, that's a kind of bug ;)

#4594 is a very huge job we plan for next major, yes. Nothing more precise for the moment.
