### ISSUE TITLE
Upgrading to GLPI 9.2.2 fail

### ISSUE THREAD

**Issue by zawaye** [glpi-project/glpi#3671]
Hello,

I cannot not upgrade to GLPI 9.2.2. I got the following error message:

> 9.2 multiple alter in glpi_slas - Error during the database query: ALTER TABLE `glpi_slas` ADD INDEX `slms_id` (`slms_id`) - Error is Key column 'slms_id' doesn't exist in table 

> 

Please help me.

**Comment by trasher** [comment]
Drop your database, restore your backup and run the migration; as stated in the upgrade docs (http://glpi-install.readthedocs.io/en/latest/update.html).

**Comment by lp73** [comment]
Hello,
Read the log /var/www/glpi/files/_log/sql-errors.log

 *** MySQL query error:
  SQL: ALTER TABLE `glpi_tickets` ADD` slts_tto_id` INT (11) NOT NULL DEFAULT '0' AFTER `slts_ttr_id`,
ADD INDEX `slts_tto_id` (` slts_tto_id`)
  Error: Unknown 'slts_ttr_id' column in 'glpi_tickets'
  Backtrace:
  inc / dbmysql.class.php: 216
  inc / migration.class.php: 640 DBmysql-> queryOrDie ()
  inc / migration.class.php: 661 Migration-> migrationOneTable ()
  install / update_0905_91.php: 855 Migration-> executeMigration ()
  inc / update.class.php: 376 update0905to91 ()
  install / update.php: 457 Update-> doUpdates ()
  install / update.php: 564 doUpdateDb ()

Modify the file install / update_91_92.php: 2014
line 761: 756 // Changing the structure of the table 'glpi_slts'

   756 // Changing the structure of the table 'glpi_slts'
    757 if ($ DB-> tableExists ('glpi_slts')) {
    758 $ migration-> renameTable ('glpi_slts', 'glpi_slas');
    $ 759 migration-> migrationOneTable ('glpi_slts');
    760 $ migration-> changeField ('glpi_slas', 'slas_id', 'slms_id', 'integer');
  +761 $ migration-> migrationOneTable ('glpi_slas');
    762 $ migration-> dropKey ('glpi_slas', 'slas_id');
    763 $ migration-> addKey ('glpi_slas', 'slms_id');
    764}

Be careful, recharge your home base and restart the update. Otherwise, you will have another error:
SQL: ALTER TABLE `glpi_tickets` ADD` slts_tto_id` INT (11) NOT NULL DEFAULT '0' AFTER `slts_ttr_id`,
ADD INDEX `slts_tto_id` (` slts_tto_id`)
  Error: Unknown 'slts_ttr_id' column in 'glpi_tickets'
  Backtrace:
  inc / dbmysql.class.php: 216
  inc / migration.class.php: 640 DBmysql-> queryOrDie ()
  inc / migration.class.php: 661 Migration-> migrationOneTable ()
  install / update_0905_91.php: 855 Migration-> executeMigration ()
  inc / update.class.php: 376 update0905to91 ()
  install / update.php: 457 Update-> doUpdates ()
  install / update.php: 564 doUpdateDb ()
