### ISSUE TITLE
[9.2.2] LDAP mail updates don't change "Last update" field of users

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi#3723]
Hello,

In GLPI 9.2.2, I see that modify a mail attribute in LDAP directory don't change "Last update" field of users. However, in "Historical" tab of users, you see lines like this : 

```
31265521 | 2018-03-15 15:03 |   | Email | Add an item: Email
```
Steps to reproduce :

1. add or delete mail attribute in LDAP directory
2. do a LDAP synchronisation with `ldap_mass_sync.php` or through "Synchronization" tab
3. notice value of "Last update" field in "Administration -> Users -> User" tab

Actual result:
Date of "Last update" field is different from last line in "Historical" tab for Email field.

Expected results : 
Date of "Last update" field must be identical as last line in "Historical" tab for Email field

For Phone number field, everything works as expected.

I testing this issue on GLPI 9.2.1 and GLPI 9.2.2

**Comment by nqb** [comment]
I can reproduce this issue in 9.2.2

**Comment by dvinouze** [comment]
+1

**Comment by cedric-anne** [comment]
Hi,

Problem is still present on user form. If you just add an e-mail, `Last update` field is not changed.

It is due to the fact that `e-mail` is not a field of `User` entity, so the [common behaviour](https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/commondbtm.class.php#L1221) does not applies here.

Regards
