### ISSUE TITLE
Error - Upgrade from 9.1.7.1 to 9.2.2

### ISSUE THREAD

**Issue by dunipj** [glpi-project/glpi#3731]
Hi friends, good afternoon ! 

I'm trying to upgrade to version 9.2.2 and am getting the following error:

![image](https://user-images.githubusercontent.com/35108492/37534979-1a0f9676-2925-11e8-9a09-3fb022112027.png)

Api users tokens has been reset, if you use REST/XMLRPC api with personal token for authentication, please reset your user's token.
- Erro na consulta ao banco de dados: ALTER TABLE `glpi_knowbaseitemcategories` CHANGE `sons_cache` `sons_cache` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `level` - Erro é Unknown column 'sons_cache' in 'glpi_knowbaseitemcategories'

Any suggestion ?

Tks

**Comment by trasher** [comment]
`sons_cache` column has been added in the  `glpi_knowbaseitemcategories` since GLPI 0.83.

If this field is missing in your database; maybe an upgrade to 0.83 has fail; and we cannot do anything to get that fixed.

The only way to go is for you to add the missing field in your 9.1.7 database before doing the update. See `install/mysql/glpi-empty.sql` (in 9.1.7) to find the correct field definition.

**Comment by dunipj** [comment]
Great tip man ! 

alter table glpi_knowbaseitemcategories add sons_cache longtext COLLATE utf8_unicode_ci

Solved my problem.. tks !

**Comment by belkynbrl** [comment]
alter table glpi_knowbaseitemcategories , delete a regist with caracther and OK
