### ISSUE TITLE
Add into SLA, the management of "maximum time to taking into account" a ticket

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#382]
Add into tickets / SLA, the management of "Maximum time to taking into account" a ticket like "Maximum time to solve"

**Comment by orthagh** [comment]
Ok for me, we need full specs

**Comment by korial29** [comment]
The specifications concerning this SLA enhancement : 
[spécifications fonctionnelles - GTI.pdf](https://github.com/glpi-project/glpi/files/113617/specifications.fonctionnelles.-.GTI.pdf)

**Comment by korial29** [comment]
I updated the specifications. list of changes : 
Structure of the SLA database
Impact on ticket rules
Impact on ticket templates
[spécifications fonctionnelles - GTI - v1.1.pdf](https://github.com/glpi-project/glpi/files/116067/specifications.fonctionnelles.-.GTI.-.v1.1.pdf)

**Comment by orthagh** [comment]
--- French answer below, i keep this topic in english

I agree with you specification proposals and have no comment about to do.
However I'd like to introduce you another (big) suggestion : even if it means reviews SLA management (and alter serveral tables), it would be appropriate to review how SLA exists and is managed in GLPi.

The object, that is currently named as SLA is, in fact, more a part of it.
When you (or we) sell a service contract, it often contains (I assume) several levels of service. Those being triggered by ticket characteristics (urgency, category, etc.).

It woulb be appropriate if the database model evolves this way :
    
* glpi_slas (service level agreements) currently displayed as a list with a title and comment. It could also have financial informations (for example a contract). This object doesn't exist in the current model.
* glpi_slts (service level targets) : service levels. Sla contains one or more slt (to set the gti or gtr). This would correspond to the former glpi_slas table. Your specs would make a massive change in this part of the code.
* Change the others tables to change foreign kes to target  glpi_slts

With this model, at the ticket level it means:
* having up to 2 slts (gti / gtr) as you specified (each individually removable)
* having a general sla (switchable to remove any information in the source ticket)

Rule engine 'ruleticket' continue to apply to slts.

This would simplify reading and the administrative management of these parts. This would also open a door to financial management for contracts.

Another solution that we considered : we would give the opportunity, in one sla (using the current schema) to set a date for taking_account and / or resolution rather than dividing the same in two (as you suggest in your specs ).
----

Specs OK pour moi, pas particulièrement de commentaires sur le contenu.

J'aimerais par contre vous soumettre une (grosse) suggestion.
Quitte à revoir les sla (et bouger pas mal de tables), il serait pertinent de revoir la notion de sla  tel qu'elle existe dans glpi.

Actuellement, l'objet nommé ainsi dans glpi concerne plutôt des parties de sla.
Quand vous (ou nous) vendez un contrat de service, il contient souvent (je suppose) plusieurs niveaux de service. Ceux ci étant déclenché par des caractéristique de ticket (urgence, catégorie, etc).

Je pense qu'il serait pertinent que le modèle deviennent ainsi : 

* glpi_slas : (service level agreement) contenant des niveaux de service, lui est présenté en liste comme actuellement, en plus du titre/commentaire, pourrais contenir des informations de gestion (contrat). Cet objet n'existe pas dans le modèle actuel.
* glpi_slts : (service level target), niveau de service, un sla contient 1 ou plusieurs slt (pour définir le gti ou gtr). Cela correspondrait à l'ancien objet glpi_slas et vos specs viendrait changer massivement ici.
* vos changement pour les autres tables en modifiant les fk pour les faire pointer vers glpi_slts

Avec ce modèle, au niveau des ticket : 
* il aurait jusqu’à 2 slt (gti/gtr) comme vous l'avez spécifié (chacun étant débrayable individuellement)
* il aurait un sla général (débrayable pour enlever toute notion relative dans le ticket en question)

Les 'ruleticket' continueraient à appliquer des slt.

Tout cela permettrait de simplifier la lecture et la gestion administrative des ces parties (en plus d'ouvrir des portes sur la gestion financières).


Une autre solution que nous avons envisagé serait de donner la possibilité dans un même sla (actuel) de définir une date de prise en compte et/ou une date de résolution plutôt que de diviser un même en deux (comme vous le proposez dans vos specs).

Qu'en pensez vous ?

**Comment by orthagh** [comment]
One screenshot of itop solution : 

![image](https://cloud.githubusercontent.com/assets/418844/12810552/32eceba2-cb27-11e5-91d4-c0879741f073.png)

**Comment by korial29** [comment]
I updated the specifications to take into account your suggestions : 
[spécifications fonctionnelles - GTI - v1.2.pdf](https://github.com/glpi-project/glpi/files/117451/specifications.fonctionnelles.-.GTI.-.v1.2.pdf)

**Comment by korial29** [comment]
I updated the specifications. Changes : 
- Allow to add several SLT on SLA
- Allow to add two SLT (gti / gtr) with ticket templates
- Allow to affect two SLT (gti / gtr) with ticket rules

[spécifications fonctionnelles - GTI - v1.3.pdf](https://github.com/glpi-project/glpi/files/117877/specifications.fonctionnelles.-.GTI.-.v1.3.pdf)

**Comment by orthagh** [comment]
One point : 
why a link table between glpi_slas and glpi_slts ?
A single Slt could be in different sla ?

**Comment by korial29** [comment]
I thought we could affect many SLT to many SLA. So we have a (n,n) relation between SLA and SLT.
This solution allows to use each SLT on all SLA.
Should we have only one SLA for each SLT ?

**Comment by orthagh** [comment]
Do you have a need for this ?

**Comment by korial29** [comment]
With this solution, once a SLT is affected to a SLA, it will not be be available for other SLA : 
![image](https://cloud.githubusercontent.com/assets/12070735/12841627/67ceb7c6-cbed-11e5-931d-d9bba160a9d4.png)

**Comment by orthagh** [comment]
Yes.

**Comment by korial29** [comment]
Ok i updated the specifications, to remove the link table between SLT and SLA : 
[spécifications fonctionnelles - GTI - v1.4.pdf](https://github.com/glpi-project/glpi/files/118856/specifications.fonctionnelles.-.GTI.-.v1.4.pdf)

**Comment by orthagh** [comment]
valid for me.

I foward to another person.

**Comment by orthagh** [comment]
I close now to keep discussions in #461

**Comment by besserer** [comment]
Una consulta como puedo aumentar los tiempo de la resolución, ya que mi versión tiene un tope de 1 mes
