### ISSUE TITLE
Mixed e-mail thread between instances due to non unique In-Reply-To header

### ISSUE THREAD

**Issue by ygini** [glpi-project/glpi#3836]
* Steps to reproduce (which actions have you made) :
Setup 2 GLPI instance and receive ticket notification on the same mailbox
Create tickets on both instance
Look at the mailbox from Mail.app on macOS

* Expected result :
Each ticket should be a different e-mail thread

* Actual result :
E-mail thread are mixed due to the `In-Reply-To` header (it's the only common header I've spotted)
```In-Reply-To: <GLPI-Ticket-1564>```

**Comment by trasher** [comment]
Indeed, headers will be unique only inside a same instance.
But since you can set several parameters (such as sender name/mail and so on); I guess this is possible to make filters on the mail client side, this may be the way to go.

I've absolutely no idea what to do to get unique headers across instances.

**Comment by ygini** [comment]
The solution is quite simple and has already be done for other headers like `Message-ID` where the unique ID is set to something like `GLPI-1112.1512121086.1108516608@server-fqdn`.

You just have to apply the same mechanism to `In-Reply-To`. Since it's not a user facing value, it will be perfectly fine.

Or you can also replace ID by UUID.

**Comment by trasher** [comment]
PR #3957 is part of the solution. Will need help to get that finalized, see PR comments.
