### ISSUE TITLE
Mail embedded images no transfered in the ticket

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#3868]
Hi, I meet the following problem with the GLPI version 9.2.2
If I send a mail with embedded images (gif) to the collector, glpi convert it into a ticket with the images as attached files.
![capture2](https://user-images.githubusercontent.com/12511115/38781391-4d6ee240-40d3-11e8-80e5-7588bdb3fb18.GIF)
The image embedded in the core text of the ticket is replaced by an small icon:
![capture1](https://user-images.githubusercontent.com/12511115/38781401-6cfadbf0-40d3-11e8-85d1-0f16d4dc2bb4.GIF)
If I check the properties of this icon a receive the following address (URL )
denied:cid:_1_0A2FC8040A2FC240005A5462C125826F
If I check the source code of the core file (riche text) of the ticket I receive the following line for the icon-->
![capture3](https://user-images.githubusercontent.com/12511115/38781600-1d94e016-40d7-11e8-83e7-2e5c253255b0.GIF)
I found some issues concerning this problem but all solutions of them are already applied to the version 9.2.2
Could you check this Bug? Please
Thank you advance for your help.

Here is a copy of my configuration system:
-------------------------------------------------------------------------------------------------------

Informations sur le système, l'installation et la configuration

[code]
 
GLPI 9.2.2 (/glpi => /usr/share/glpi)
Installation mode: TARBALL

 

Server

 
Operating system: Linux chmsglpi 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64
PHP 5.6.33-3+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, apc, apcu, calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv,
	imagick, imap, intl, json, ldap, libxml, mbstring, mcrypt, memcache, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql,
	pdo_sqlite, posix, pspell, readline, recode, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy,
	tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="90" memory_limit="256M" post_max_size="200M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at chmsglpi Port 80)
	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Server Software: (Ubuntu)
	Server Version: 5.7.21-0ubuntu0.16.04.1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_cache : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
OK/usr/share/glpi/files/_log : OK

 
Web access to the files directory, should not be allowed
Automatic checks cannot be done; please review .htaccess file and the web server configuration.
 

Libraries

 
htmLawed version 1.2.4 in (/usr/share/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/usr/share/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/usr/share/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.16 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

 

LDAP directories

 
Server: '172.22.0.125', Port: '389', BaseDN: 'OU=CHA-Users,OU=CHA,DC=emea,DC=busch,DC=inet', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'EMEA\cha.glpi', Use
		TLS: none
Server: '172.22.0.26', Port: '389', BaseDN: 'OU=Composites,OU=Utilisateurs,DC=busch,DC=ch', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'administrateur', Use
		TLS: none
Server: '172.22.0.26', Port: '389', BaseDN: 'OU=Utilisateurs_Windows_7_Enteo_(dossiers_redirigés),DC=busch,DC=ch', Connection
		filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'administrateur', Use TLS: none
Server: '172.22.0.20', Port: '389', BaseDN: 'DC=busch,DC=ch', Connection filter: none, RootDN: 'administrateur', Use TLS: none
Server: '172.22.0.26', Port: '389', BaseDN: 'OU=Clean Air,OU=Utilisateurs,DC=busch,DC=ch', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'administrateur', Use
		TLS: none
Server: '172.22.0.26', Port: '389', BaseDN: 'OU=Ateliers_Busch,OU=Utilisateurs,DC=busch,DC=ch', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'administrateur', Use
		TLS: none
Server: '172.22.0.125', Port: '389', BaseDN: 'OU=CHM-Users,OU=CHM,DC=emea,DC=busch,DC=inet', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'EMEA\chm.glpi', Use
		TLS: none
Server: '172.22.0.125', Port: '389', BaseDN: 'OU=CHA-Groups,OU=CHA,DC=emea,DC=busch,DC=inet', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'EMEA\cha.glpi', Use
		TLS: none
Server: '172.22.0.125', Port: '389', BaseDN: 'OU=CHC-Users,OU=CHC,DC=emea,DC=busch,DC=inet', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'EMEA\chc.glpi', Use
		TLS: none

 

SQL replicas

 
Not active

 

Notifications

 
Way of sending emails: SMTP (anonymous@172.22.4.99)

 

Mails receivers

 
Name: 'support@busch.ch' Active: Yes
	Server: '{172.22.4.99:110/pop/notls}inbox' Login: 'support' Password: Yes
Name: 'test.user@busch.ch' Active: No
	Server: '{172.22.4.99:110/pop/notls}inbox' Login: 'User test' Password: Yes

 

Plugins list

 
	positions            Name: Cartographie                   Version: 4.4.0      State: Enabled
	shellcommands        Name: Commandes Shell                Version: 2.1.0      State: Enabled
	behaviors            Name: Comportements                  Version: 2.0.2      State: Enabled
	uninstall            Name: Désinstallation d'un matériel  Version: 2.3.1      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.2+2.0-RC1 State: Enabled
	racks                Name: Gestion de baies               Version: 1.8.0      State: Enabled
	datainjection        Name: Injection de fichiers          Version: 2.5.0      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.4.0      State: Enabled
	projet               Name: Projets                        Version: 1.4.1      State: To be cleaned
	purgelogs            Name: Purge de l'historique          Version: 1.3.0      State: Enabled
	reports              Name: Rapports                       Version: 1.11.2     State: Enabled
	reservation          Name: Réservation                    Version: 1.4.1      State: Enabled
	resources            Name: Ressources humaines            Version: 2.4.3      State: Enabled
	ticketcleaner        Name: Ticket Cleaner                 Version: 1.2.3      State: To be cleaned

 
[/code]  

A copier/coller lors d'une demande d'assistance

**Comment by trasher** [comment]
Could you please try if you reproduce the issue with current 9.2/bugfixes branch and master branch?
Check also GLPI logs (files/_log/php-errors.log and files/_log/sql-errors.log) when collector is run and when ticket is displayed.
The issue may also be related to a plugin, give a try without plugins.

**Comment by trasher** [comment]
Try with https://github.com/glpi-project/glpi/pull/3880/commits/fc995c959ec024a3aa58d3233ed0984025d64e09 added yesterday.

**Comment by Borisov707** [comment]
HI! 
I have a very similar problem. Еhe last 3 days I tried various combinations from different issues. 
in the end I'm applied all bugfixes on 24.04.18.
But problem didn't fix :(
In my case I send a mail with embedded images. 
glpi takes it by by maigate (automated action. CLI mode)
Instead of images in the ticket only strings like 
#75a05700-86cc5719-5ae10872413848.16603942# 

![2018-04-26_3-31-26](https://user-images.githubusercontent.com/38729431/39279560-92f02f72-4902-11e8-8490-ac81fd577257.png)

**Comment by Borisov707** [comment]
**# Here is my GLPI configuration:**

[code]   GLPI 9.2.3 ( => /var/www/html) Installation mode: TARBALL
--

Operating system: Linux GLPID 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 PHP 5.6.33-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, 	ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at hd Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 Server Software: (Debian) 	Server Version: 5.5.59-0+deb8u1 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /var/www/html/config : OK /var/www/html/files : OK /var/www/html/files/_dumps : OK /var/www/html/files/_sessions : OK /var/www/html/files/_cron : OK /var/www/html/files/_graphs : OK /var/www/html/files/_lock : OK /var/www/html/files/_plugins : OK /var/www/html/files/_tmp : OK /var/www/html/files/_cache : OK /var/www/html/files/_rss : OK /var/www/html/files/_uploads : OK /var/www/html/files/_pictures : OK /var/www/html/files/_log : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/var/www/html/lib/htmlawed) phpCas version 1.3.5 in (/var/www/html/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/var/www/html/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/var/www/html/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/var/www/html/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/vendor/true/punycode/src) iacaml/autolink in (/var/www/html/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib)

Server: '192.168.100.104', Port: '389', BaseDN: 'DC=tekta,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))) ', RootDN: 		'CN=ldap,CN=users,DC=tekta,DC=local', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@192.168.100.252)

Name: 'glpi@tekta.com' Active: Yes 	Server: '{192.168.100.252/pop/novalidate-cert/notls}' Login: 'glpi' Password: Yes Name: '_nav.support@tekta.com' Active: Yes 	Server: '{192.168.100.252/pop/novalidate-cert/notls}' Login: '_nav.support' Password: Yes

mod                  Name: GLPI Modifications             Version: 1.1.8      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.3.8      State: Enabled 	genericobject        Name: Objects management             Version: 2.5.0      State: Enabled 	showloading          Name: Show Loading                   Version: 1.0.0      State: Enabled 	autologin            Name: Авто вход                      Version: 2.1.1      State: Enabled 	additionalalerts     Name: Другие уведомления      Version: 2.0.0      State: Enabled 	dashboard            Name: Панель отчетов              Version: 0.9.1      State: Enabled 	behaviors            Name: Поведения                      Version: 2.0.2      State: Enabled 	mreporting           Name: Подробные отчеты          Version: 1.4.0      State: Enabled
[/code]

**Comment by FRANCOIS50** [comment]
Do you have an idea about my problem?

**Comment by tsmr** [comment]
Same problem - GLPI 9.2.3
$entities_id = $_SESSION['glpiactive_entity'];

 $_SESSION['glpiactive_entity'] does'nt exist from cron mailgate :(

**Comment by trasher** [comment]
Should be OK with 9.2.4 and 9.3

**Comment by orlandotnras** [comment]
problem now with 9.5.1

**Comment by cedric-anne** [comment]
> problem now with 9.5.1

Hi,

Please try with GLPI 9.5.2 (or even [nightly build](https://github.com/glpi-project/glpi/actions/runs/358765754)) and, if problem persist, please open a new issue with all requested informations.

Regards

**Comment by werner-h** [comment]
Problem still exists on 9.5.3 any solution here?

**Comment by trasher** [comment]
You may first try with latest stable release
