### ISSUE TITLE
Helpdesk: defined default source of demand not applied

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#3869]
version GLPI 9.2.2
Setting of the default source of demand is not applied to the corresponding field in the ticket.

Setting --> 
![capture4](https://user-images.githubusercontent.com/12511115/38781764-e56be5c4-40d9-11e8-9355-7a6490f05f95.GIF)

field in the ticket -->  
![capture6](https://user-images.githubusercontent.com/12511115/38781771-f2a5665c-40d9-11e8-926d-f83dcbc658a7.GIF)

could you check this Bug ?  Please

Thank you in advance for your help

**Comment by trasher** [comment]
Could you please try with 9.2/bugfixes branch?

**Comment by FRANCOIS50** [comment]
Hi I tested with 9.2/bugfixes branch, but I received the same problem.

**Comment by trasher** [comment]
Did you try login agin after parameter has been changed?

**Comment by orthagh** [comment]
Just tested with current 9.2/bugfixes, it's works on my instance.

Some suggestions for you as request source may be applied from multiple ways: 

- check your personal preferences (click on your name right top of glpi) instead of global configuration, if you have set here an option (like theme or disposition for example), the global configuration doesn't apply anymore for your user.
- If your test already and previously done on this personnel preference, check general setup so :).
- Tickets template can apply request sources, check also in them.
- Last thing, plugins may interfere also with this field, try to disable all.

**Comment by FRANCOIS50** [comment]
I tried to go back with my personal settings
Ticket's template are set with default request source --> "Email"
But default setting of follow-up source stay empty
I tried also with deactivated plugin and it doesn't solve my problem.
But I am not sure that we are speaking of the same field.
I speak about the filed Follow-up source and not bout the request source field

**Comment by trasher** [comment]
> I speak about the filed Follow-up source and not bout the request source field

OK... This is not what you said first.

I'm not sure this parameter was initially designed to work on followups, but it should be OK to use it.

**Comment by orthagh** [comment]
For followup source, see Setup > Dropdowns > Request sources
Edit one, and set the defaut tag for followups 
![image](https://user-images.githubusercontent.com/418844/40412132-c0ba4688-5e72-11e8-8bb0-222972ccb718.png)

**Comment by FRANCOIS50** [comment]
Thanks for your answer very helpful
