### ISSUE TITLE
Embedded images into body of emails don't appears in tickets

### ISSUE THREAD

**Issue by Borisov707** [glpi-project/glpi#4051]
In my company users send requests to Helpdesk Department by e-mail via Microsoft Outlook 2010/13/16.
GLPI creates tickets via "mailgate" automatic action.
If the user embedds a screenshot in the body of the message there is no picture in the created ticket.
Instead of it is string like on screen below.

If the picture is an attachment, then it appears in the ticket.
I tryed with #3868 and many other related and similar issues and applyed last patches.

![1](https://user-images.githubusercontent.com/38729431/40432215-d8a87dc0-5eb1-11e8-95bc-de29c9addb46.png)
![2](https://user-images.githubusercontent.com/38729431/40432216-d8d49608-5eb1-11e8-9b22-fafe2c1e05b1.png)

GLPI 9.2.3 ( => /var/www/html)
Installation mode: TARBALL

Server
 
Operating system: Linux GLPID 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64
PHP 5.6.33-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at hd Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Server Software: (Debian)
	Server Version: 5.5.59-0+deb8u1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/var/www/html/config : OK
OK/var/www/html/files : OK
OK/var/www/html/files/_dumps : OK
OK/var/www/html/files/_sessions : OK
OK/var/www/html/files/_cron : OK
OK/var/www/html/files/_graphs : OK
OK/var/www/html/files/_lock : OK
OK/var/www/html/files/_plugins : OK
OK/var/www/html/files/_tmp : OK
OK/var/www/html/files/_cache : OK
OK/var/www/html/files/_rss : OK
OK/var/www/html/files/_uploads : OK
OK/var/www/html/files/_pictures : OK
OK/var/www/html/files/_log : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.
Libraries
 
htmLawed version 1.2.4 in (/var/www/html/lib/htmlawed)
phpCas version 1.3.5 in (/var/www/html/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/var/www/html/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/var/www/html/vendor/simplepie/simplepie/library)
TCPDF version 6.2.16 in (/var/www/html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib)

LDAP directories
 
Server: '192.168.100.104', Port: '389', BaseDN: 'DC=xxxxxxxx,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))) ', RootDN:
		'CN=ldap,CN=users,DC=xxxxxxxx,DC=local', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@192.168.100.252)

Mails receivers
 
Name: 'glpi@xxxxxxxx.com' Active: Yes
	Server: '{192.168.100.252/pop/novalidate-cert/notls}' Login: 'glpi' Password: Yes
Name: '_nav.support@xxxxxxx.com' Active: Yes
	Server: '{192.168.100.252/pop/novalidate-cert/notls}' Login: '_nav.support' Password: Yes

Plugins list

**Comment by arthurrschaefer** [comment]
Take a look at #3716

**Comment by trasher** [comment]
Also try with latest 9.2/bugfixes branch.

**Comment by GuiGuiSoft** [comment]
I have the same problem here for follow-up messages where images were pasted (without using any email system).
The image does not appears anymore and it is replaced by some reference (example : ec606013-a5064f86-5ae32aa926bd01.15607630)


[code]
 
GLPI 9.2.3 ( => /opt/glpi)
Installation mode: TARBALL

Server

 
Operating system: Linux xxxx 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64
PHP 7.0.30-0ubuntu0.16.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="16M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Server Software: (Ubuntu)
	Server Version: 5.7.22-0ubuntu0.16.04.1-log
	Server SQL Mode: 
	Parameters: glpi_user@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/opt/glpi/config : OK
OK/opt/glpi/files : OK
OK/opt/glpi/files/_dumps : OK
OK/opt/glpi/files/_sessions : OK
OK/opt/glpi/files/_cron : OK
OK/opt/glpi/files/_graphs : OK
OK/opt/glpi/files/_lock : OK
OK/opt/glpi/files/_plugins : OK
OK/opt/glpi/files/_tmp : OK
OK/opt/glpi/files/_cache : OK
OK/opt/glpi/files/_rss : OK
OK/opt/glpi/files/_uploads : OK
OK/opt/glpi/files/_pictures : OK
OK/opt/glpi/files/_log : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

Libraries

 
htmLawed version 1.2.4 in (/opt/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/opt/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/opt/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/opt/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.16 in (/opt/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/opt/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/opt/glpi/vendor/true/punycode/src)
iacaml/autolink in (/opt/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/opt/glpi/vendor/sabre/vobject/lib)

LDAP directories

 
Server: 'xxxx', Port: 'xxxx', BaseDN: 'xxxx', Connection filter:
		'(&(objectClass=user)(memberOf=CN=xxxxxxxxxxxx)(cn=*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))',
		RootDN: 'xxxxxxxxxxxx', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP+SSL xxxx@smtp.xxxx)

Mails receivers

 
Name: 'xxxx@xxxx' Active: Yes
	Server: '{imapxxxx:993/imap/ssl/novalidate-cert}' Login: 'xxxx' Password: Yes
Name: 'xxxx@xxxx' Active: Yes
	Server: '{imapxxxx:993/imap/ssl/novalidate-cert}' Login: 'xxxx' Password: Yes

Plugins list

 
	fields               Name: Champs supplémentaires         Version: 1.7.0      State: Enabled
	escalade             Name: Escalades                      Version: 2.2.1      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.4.0      State: Enabled

[/code]

**Comment by Armin83** [comment]
This settings works only for new tickets. 
> 
> I haven't enabled the Rich text for helpdesk.
> After enabling it, the images started to appear.
> 
> Sorry and thanks @edgardmessias
> 
I have this in our environment Outlook 2013 + Outlook 365 (=2016). Which format do you use in Outlook ?
Html or RichText do you have this problem with both settings ?

**Comment by trasher** [comment]
Could you please provide:
* **raw** contents of the email, as seen from an IMAP call,
* content that is added in GLPI database.
Please precise client used to write the mail. As it may impact the issue, a fix may be correct fix for one but not another...

**Comment by Borisov707** [comment]
I can provide sent messages as *.msg files
Can I send this info to private e-mail?

**Comment by trasher** [comment]
Hi @Borisov707 , you can send to `glpi AT teclib.com`; thank you.

**Comment by Borisov707** [comment]
@trasher, thanks a lot! It works

**Comment by v-k-v** [comment]
I have the same problem. Upgrading to version 9.2.4 and 9.3 did not resolve the issue.

**Comment by Armin83** [comment]
Don't write at closed topics - it's not easy to work ;)
This might help you https://github.com/glpi-project/glpi/issues/4138
