### ISSUE TITLE
[9.3 RC-2]langage selection not diplayed

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#4155]
setp to reproduce (which actions have you made) :
go to user preferences; set  langage to french

* Expected result :
langage changed to french AND dropdown value set to french

* Actual result :
laguage is set to french ( including header langage selector) but in preference page dropdown displays arabic(?) langage.

* URL of the page :
http://localhost/glpi/front/preference.php

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/13557254/41195724-6582a084-6c33-11e8-87da-cde5ec26164d.png)
![image](https://user-images.githubusercontent.com/13557254/41195756-dec3048e-6c33-11e8-85ad-9953ec7785f4.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
glpi 93 RC2 tarball upgraded from 9.2.3
ubuntu 16.04 LTS server Maria DB 10

**Comment by trasher** [comment]
Just tested, I cannot reproduce. UI language has changed, so I guess this is OK i the database; this should be a "display" issue on preferences.
First, try without any plugins and make sure you cleaned your browser cache. BTW, which browser has been used?
If the issue still persists, check browser console, and give us all javascript errors/warnings displayed.

**Comment by roshanroche** [comment]
Hello ,
in my instance it happens when i select English US , refer the screen shots below

![image](https://user-images.githubusercontent.com/22425503/41213556-184c13d4-6d57-11e8-8888-393b46a20150.png)
![image](https://user-images.githubusercontent.com/22425503/41213570-321fb310-6d57-11e8-8ccb-d73b4c43b038.png)

This happens on Chrome , Firefox. even after a clean cache. without any plugins. fresh install of 9.3 RC2.

**Comment by trasher** [comment]
Any output in the brwoser console o the preferences page?

**Comment by roshanroche** [comment]
Hi @trasher ,
there is nothing in the console, interestingly this issue is since 9.3 beta release , existed in 9.3RC1 as well tried on all 3 9.3 releases so far.
issue happens when u change the Language 2nd time from the top menu. whichever language u select from the default language , that language shows arabic as the language on the Main tab of preferences page.

**Comment by ladenree76000** [comment]
This happens with FireFox(60) . with the same browser, this dropdown is OK in 9.2.3

i agree with you : it seems like a display issue in My preferences. langage is set to french and also displayed in the top menu. only this dropdown seems not initialised.

**Comment by Armin83** [comment]
I had also problems with no initialised drop downs also. If i activate debug mode it works. I thought this is normaly with RC1 / nightly tarballs. I don't test RC2 untill now.

**Comment by Armin83** [comment]
I don't have this problem with RC2 and one time debug mode on but i think it's more the browser cache problem i forgot to clear. My case is solved :)

**Comment by cedric-anne** [comment]
Hi,

Issue is reproductible when you define your language using the same value as the default one of your GLPI installation.
This is due to the fact that this form uses language stored in DB as selected value, but fields considered as preferences are not store when defined with same values as default ones (https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/user.class.php#L901).

Bug has been introduce by commit 0cef1c1e128e58629fccecd6b7e29ee9224acf77 on https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/user.class.php#L2418.

Regards
