### ISSUE TITLE
Ticket rules with categories

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#4771]
* Steps to reproduce (which actions have you made) :
Create two groups :
- The first group at the root entity with child entity option to "yes",
- The other group at a child entity 

Create One category at the root entity with : 
- The "Group in charge of the hardware" option selected with the first created group
- Child entities option to "Yes"

Create one rule with : 
- Criteria : Technician group |     is     | Group of the root entity
- Action : Technician group  | Assign | Group of the child entity

--> Create a ticket (on the child entity) in selecting the newly created category .

* Expected result :
Affect the group of the child entity to the ticket

* Actual result :
Affect the group defined in the category to the ticket

It seems that the business rule process before the category rules.
I have tested with glpi 9.2.2 and 9.3.1, same result.

**Comment by yllen** [comment]
a
I explain.
Your rule criteria is "Technician group | is | Group of the root entity"
When you create a ticket, before creation rules are played and didn't match because criteria doesn't still exist.
You must have a first rule based on category
Category  is  Mycategory      Action  Technician group  assign  Group of the root entity
and after you have your second rule.

In a rule you can't have a criteria of a non existing field.
