### ISSUE TITLE
Bug in reservation tab of an item

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4870]
if no current of futures reservations => title of the tab is a link
if no past reservations => titles of the tab is a link
if no right to read user => user name is a link
if no right to do a reservation => planning is display

**Comment by Phorms** [comment]
Hi,

GLPI version 9.3.3

it think with this fixes a new bug was born.

I had to delete the count () in Line https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/reservation.class.php#L1090 in order to make a new reservation.

Count is always zero, if the item has no reservation with an end date in the future. Therefore the link to make a reservation is never shown for a new item.

Maybe there is a other way to make a reservation, but I only know the way of clicking on "Current and future reservations" in the reservation tab of an item.
