### ISSUE TITLE
Cookie Attibutes (httponly, secure)

### ISSUE THREAD

**Issue by derricksmith** [glpi-project/glpi#4949]
OpenVas vulnerability scan indicates that GLPI does not use the httponly and secure cookie attributes.  These preventative measures help secure against XSS.  

Suggest adding these attributes to auth.class.php at lines 519 and 872.  I will submit a PR.

**Comment by M-Falken** [comment]
Also possible to put this in htaccess as an option
#php_value session.cookie_httponly true
#php_value session.cookie_secure true

**Comment by derricksmith** [comment]
Thanks, I wasn't familiar with this setting.  Is there a negative to having this in the application code vs .htaccess or apache config?

**Comment by M-Falken** [comment]
Nope,
the difference is that those .htaccess settings do not always work as some php handlers do not allow those php_value, I mean do not take them in account, that's why I keep the "#" in front for comment, and the recursive check in sub folders for htaccess rules is not always deep enough (usually 2 step by default), No problem if the rules are at root.
And could have no effect in some cases, most of the time on shared hosting with very few access to the parameters etc.
But as the htaccess is read at first, so those rules are applied at the first setcookie() detection.
But this implies that the cookie will no longer be transmitted if the connection is not https. It is therefore imperative that the site has an https redirection correctly implemented if possible with the applied hsts. That's why for the moment this has to be in the form of an option IMUO.

Example with my own GLPI:
_User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://theref.tld/
Content-Type: application/x-www-form-urlencoded
Content-Length: 161
Connection: keep-alive
Cookie: _ga=GA1.2.XXXXXXX.1543395283; glpi_XXXX5f378bf9ab3db43c9a41cf=XXXXb0add3b735bde3c14b3e0a5839
**Upgrade-Insecure-Requests: 1**
TE: Trailers_

And so the post cookie at login is:
_glpi_XXXXX75f378bf9ab3db43c9a41cf=XXXX017c5f5d2d12c74cda9ce775e12; path=/; **secure; HttpOnly**_
