### ISSUE TITLE
[GLPI 9.3.3] Ticket description consider (sometimes) empty despite of a pre-filled template

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#4987]
Hi,
For new ticket creation:

1. Create a ticket category (set to sub entities)
2. Create a sub category in the parent (NOT set to sub entities)
3. Now set it to sub entities
4. Set a template with default text for the description
5. Set the ticket description as mandatory
6. Click on create new ticket
7. Set what you need but don't touch the description as it's pre-filled.
8. Click add
9. Ticket validation refused (because description empty but is not)

Fault
Required fields are not defined. Please correct: Description

Unfortunately I'm not 100% sure of this one, because I've already setup some sub categories for tickets but do not have this issue with those.

If not a bug thanks for feedbacks of those who experience the same behaviour

```
9.3.3 Prod
9.3.3 Nightlybuild  #test
PHP 7.2.12 litespeed / Apcu 5.1.12
MariaDB Server Version: 10.1.37-MariaDB
```

**Comment by TheLostDBA** [comment]
Hello, I am also experiencing this.
After updating GLPI to 9.3.3 and this rich text box appeared:
![desc1](https://user-images.githubusercontent.com/47581116/54177770-64680080-44ce-11e9-98e8-3be3e8aaa532.png)

Tickets can now be saved if **mandatory** with **pre-defined description field**.
_Looks like this:_
![desc2](https://user-images.githubusercontent.com/47581116/54177824-8792b000-44ce-11e9-82cc-0f941690fc05.png)

_Notification that ticket was saved:_
![desc3](https://user-images.githubusercontent.com/47581116/54177828-8bbecd80-44ce-11e9-8a7d-250ecc1edc06.png)

But if this was blank, it will send you an **error** that you are expecting since this is mandatory.
![desc4](https://user-images.githubusercontent.com/47581116/54177850-a5f8ab80-44ce-11e9-8905-70088329a070.png)

**Conclusion**
I really suspect this is because of the update that is why GLPI is behaving like this. I think they oversee the validation code behind description box.

**Comment by cedric-anne** [comment]
Hi,

@M-Falken,
The behaviour you describe is the expected one (see https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/ticket.class.php#L1681). If description is mandatory but contains the predefined value, it is considered as not filled.

@TheLostDBA,
I think your problem is due to the fact that your template was filled when "rich text mode" was disabled for tickets, and this mode is now enabled. As rich text processing depends on a javascript component (TinyMCE), which reformats the given predefined value to embed it into HTML tags, we have no solution to automatize migration from "plain text" to "html". You will have to delete predefined values and set them back again.

Regards
