### ISSUE TITLE
Tests on master fail during winter holidays

### ISSUE THREAD

**Issue by cconard96** [glpi-project/glpi#5188]
Tests on master fail depending on the day they run. From Dec 31 to Jan 13, the test for cron autoclose ticket will fail due to the holiday in the test calendar (Tested by changing my local system date). Manually removing the holiday from glpi_holidays and running the ticket tests again work properly.

Unsure of the best solution for this issue.

Faulting test:
tests/functionnal/Ticket.php -> testCronCloseTicket()

**Comment by trasher** [comment]
Oh... Thanks, I'll take a look at that.

**Comment by trasher** [comment]
Faultly commit is: https://github.com/glpi-project/glpi/commit/95d16cffd64bfb5987eab65629bfbbf77df2bc37#diff-10eafd8bf5fbdde867b86fe38d30b9bb

If we drop `glpi_calendars_holidays` entry, all is fine. As it would be complicated to change cron tests to reflect that change, and since this is only used in one test, dropping data from bootstrap and add it when needed only would be a working solution.

Your opinion?

**Comment by cconard96** [comment]
That would be the easiest way. If we really have to test how the taks handles holidays, we should truncate the table and add a holiday relative to the current date.

**Comment by cconard96** [comment]
Fixed by #5192
