### ISSUE TITLE
9.1.3 queuedmail does not execute (locaweb)

### ISSUE THREAD

**Issue by taiuan99** [glpi-project/glpi#5195]
I create a new task and it does not send notification email

![0](https://user-images.githubusercontent.com/46347804/50640541-f2aa8e00-0f43-11e9-9dac-9ab74e11199a.png)

![2](https://user-images.githubusercontent.com/46347804/50640550-f76f4200-0f43-11e9-901e-35ad730f408b.png)

![3](https://user-images.githubusercontent.com/46347804/50640559-fb9b5f80-0f43-11e9-9748-c1197065e000.png)

![1](https://user-images.githubusercontent.com/46347804/50640624-284f7700-0f44-11e9-8308-6a091c55e23b.png)

**Comment by pedroluisvsousa** [comment]
Dear taiuan99,
run the authomatic actions in CLI mode. There are many tutorials on the internet about.

**Comment by taiuan99** [comment]
My host does not allow creating a crontab

**Comment by orthagh** [comment]
Hello again.

if your issue is a cron one:

- take a provider which supply a cron, it's a shame you can't have access to one today.
- use an external webcron (not a good solution)
- use glpi execution (the mail will send only when user present on glpi).

AND upgrade your glpi version, 9.1.3 is old.

By the way, if you want community support, use the community forum -> https://forum.glpi-project.org/index.php

This issues space is reserved for bug and their fixes.
Regards
