### ISSUE TITLE
[API] with_networkports returns data only when computer ID is being supplied

### ISSUE THREAD

**Issue by GitStorm** [glpi-project/glpi#5257]
**Describe the bug**

As far as I understand, the API is supposed to return the following information, when `with_networkports=true` is being supplied:

```
  "_networkports": {
    "NetworkPortEthernet": [
      {
        "netport_id": 1,
        "entities_id": 0,
        "is_recursive": 0,
        "logical_number": 1,
... 

```

In my case, this is only true when I query for a specific computer item directly like this:
`https://<GLPISERVER>/apirest.php/Computer/1/?with_networkports=true&expand_dropdowns=true`

The `_networkports` section is missing however, when querying for all items like this:
`https://<GLPISERVER>/apirest.php/Computer/?with_networkports=true&expand_dropdowns=true`

**To reproduce**

See above.

**Expected behavior**
The `_networkports` section should appear when querying for all items as well as when querying for specific a item when `with_networkports` is being set to `true`.

**Logs**
php-errors.log + sql-errors.log do not show any errors related to those queries.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
GLPI 9.3.2

**Comment by cedric-anne** [comment]
Hi,

Actually, it is not supposed to work. If you look at documentation ( https://<GLPISERVER>/apirest.php#get-all-items ), you will see that `with_*` parameters are not available when requesting all items. This has not been done due to a technical difficulty.

However, you should be able to create a custom query listing all what you need using the search endpoint of the API( https://<GLPISERVER>/apirest.php#search-items ).

Regards
