### ISSUE TITLE
followup from collector creating new ticket

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#5283]
glpi 9.3.3

Hello, since 9.3.3 migration last week when a user respond to a ticket from mail a new ticket is created instead of adding a follow up in existing ticket.

No change has been made in notification during migration

Thank you for your help

**Comment by cedric-anne** [comment]
Hi,

Sorry for the late.

From which version were you migrating ?

We added rights checking in GLPI 9.3.x for mail collector. Following comment is a good summary of how mails are handled now: https://github.com/glpi-project/glpi/issues/4889#issuecomment-438240534.

Regards

**Comment by tomSDL** [comment]
Hi Cedric,

Still struggling with this. Tested with a user that has super-admin rights and still a new ticket is created each time.

What am I missing please?

I was on v 9.3.3 without this issue :)

Thanks,
Tom

**Comment by cedric-anne** [comment]
@tomSDL 

Is your user having its email correctly filled ?

Regards

**Comment by tomSDL** [comment]
@cedric-anne 
Thanks for you support so far. 
Yes e-mails are entered correctly.

**Comment by tomSDL** [comment]
I used to be able to copy e-mail threads with multiple reply's into the receiver inbox. If, for example I had an e-mail conversation I wanted to send into GLPI as a ticket I could. The e-mails would become followups in the one ticket.

Since 9.4 this has changed and no longer does GLPI recognize the e-mail thread as one ticket.

Is it possible to get this function back somehow? It meant I could use outlook for creating and replying to tickets.

Thanks

**Comment by cedric-anne** [comment]
@tomSDL 

Although it is an interesting feature, I do not see such feature in core.

Is it possible that the behaviour comes from the `mailanalyzer` plugin ?

Regards

**Comment by cedric-anne** [comment]
ping @tomolimo
