### ISSUE TITLE
Tickets list in project task is empty when I use entity different than root

### ISSUE THREAD

**Issue by sonbinome** [glpi-project/glpi#5293]
**Describe the bug**
Hi every body, I'm french and I try to explain my problem in English.
I use an Entity and I create a project.
After create project task, i would like attach or create a ticket in the same entity.
When I would like see list of tickets in project task I have to go in root entity.

**To reproduce**

1. Select an entity other root
2. Create a project
3. Create a project task
4. Create from task a ticket or attach a ticket
5. See list of ticket in project task (it's should be empty)
6. Select root entity
7. Go back in list of ticket in project task (you should be see all tickets)

**Expected behavior**

Why I can't see list of ticket when I in another entity than root ?

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.3.3 ( => /var/www/glpi)
Installation mode: TARBALL
```

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce your issue on the demo website ( https://demo.glpi-project.org/ ).

**First test:**
1. I login as admin user.
2. I go to a sub-entity.
3. I created a project.
4. I created a task.
5. I created a ticket from this task.
-> The ticket is visible in the "Tickets" tab from the task when beeing on the sub-entity.

**Second test:**
1. I login as admin user.
2. I go to a sub-entity.
3. I created a project.
4. I created a task.
5. I logout.
6. I login as normal user.
7. I created a ticket.
8. I associate this ticket to the task created on step 4 from the "Project task" tab of the ticket.
-> The ticket is visible in the "Tickets" tab from the task when beeing on the sub-entity.

If you have some plugins, can you try to deactivate them and check if your problem is still reproductible ?
Can you also check your logs to see if you have any error related to this problem ?

Regards

**Comment by sonbinome** [comment]
Sorry, when I have this problem I worked whit version 9.3.2.
I installed the last version but probably I was have a problem with cache or other.
I reboot all environment (desktop, server, ...) and it's OK.
Thanks a lot for your return and sorry for your lost time...
