### ISSUE TITLE
Add a lock mecanism for tickets

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#54]
Add a mecanism to prevent several people to work on the same ticket.

**Comment by remicollet** [comment]
FYI a simple implementation exists in "Bevaviors"

https://forge.glpi-project.org/projects/behaviors/repository/entry/trunk/inc/ticket.class.php#L198

**Comment by tomolimo** [comment]
Hello,
For me it has to be managed on server side AND on client side (browser) to really prevent users to double edit of a ticket (for example, but it can be applied to any items providing the following hooks). Behaviours only prevent double writing by returning an alert telling you that your current modifications can't be saved due to concurrent editing: this is really frustrating for users to do modifications and to be alerted after saving that it can't be saved...
The best behaviours (on my opinion) is to prevent double editing with an alert or whatever to inform users that an item is read-only because it is currently edited by someone else.

For user stories (or use-cases): there are two ways for implementing such lock token:
1) is to get a token automatically at item openning, then a further openning will show the item in read-only mode. The token is automatically freed when leaving the open item page or closing the browser window. Pro: use of GLPI like today, Con: if you want read-only an item, you can't: automatically you are going to lock any other people who are going to work on this item if you open the item before the others.

2) to show item in read-only mode and to get the lock token by a user action (on a button for exemple) to claim the token. then a further openning will show the item in read-only mode. The token is automatically freed when leaving the open item page or closing the browser window. Pro: At any time you may open an item without locking it, Con: You must click one more time to request lock tokens.

I've developped a plugin which implements solution 1) for that, but it needs new special hooks in kernel (called pre_show_item and post_show_item) in order to prevent too much javascript coding.
Explanations: the idea of this plugin is to set a new profile (called "Plugin Lock Read-Only Profile": this profile has read-only access to items in GLPI) and when a lock is detected on an item, this profile is subtituted to the current profile during the "show" of the item. This forces the kernel to show items in read-only. This profile must be set before the showItem() methods and reset after, in order for GLPI to continue normal operations.

This plugin also manages special cases like:
a) possibility when openning a locked item to request from the locking user to free the item (by sending an email). 
b) a special report has been developped to give service desk possibility to unlock items with massive actions.

Thank you
Regards,
Tomolimo

**Comment by ddurieux** [comment]
We can make like other tools (like python-eve) and have etag on glpi_tickets generated on each add / modification and each time display ticket get this etag and when click on update button, a pre-hook check if etag from form is same than etag in DB, if yes it update, if no have error.

**Comment by tomolimo** [comment]
I don't know etag nor python-eve, but if this gives the browser user-friendly use I proposed then why not.

**Comment by wawax** [comment]
David, can you please post some screencaptures so we can figure out how it looks like ?

**Comment by ddurieux** [comment]
In db it's like 
![etag](https://cloud.githubusercontent.com/assets/239744/9163167/3e863762-3f49-11e5-84f9-4a6bb276b27a.png)

Has you see we have an _etag field where is regenerated each time db modified (managed by application).

So it's a little like CSRF in GLPI, if etag in ticket form different from etag in DB when want to update ticket, glpi must refure update because somebody else has modified between time you get the etag and time you clik on update button

**Comment by tomolimo** [comment]
Thank you for this explanation, but as far as I understand, this is like the plugin Behaviors at the end?

**Comment by ddurieux** [comment]
Seems same system yes (sorry, I hasen't read Behaviors code earlier :p)

**Comment by tomolimo** [comment]
No problem David :)
But could you give me your ideas about my proposals?

**Comment by wawax** [comment]
Tomolimo,
Could you post you code somewhere on github so that we can have a look at it and test it ?

I'm not willing to add new hooks for the moment, especially if we want to integrate it into GLPI's core.

**Comment by tomolimo** [comment]
Here it is: https://github.com/tomolimo/lock

**Comment by wawax** [comment]
This is a new feature in iTop 2.2. Here is the description : https://wiki.openitop.org/doku.php?id=2_2_0:admin:locking&s[]=lock

**Comment by tomolimo** [comment]
:)
Seems like they copied my specs :)
:)

Apart that the expiration delay default value is 4 hours and configurable in a GLPI cron.
And apart that the kill of the lock is requested to current locking user by email and not "stolen" from him/her. The only case when a lock is killed without the knowledge of initial locking user is when Admin kills a lock on an emergency need (using a special report with massive actions).

:)

**Comment by tomolimo** [comment]
Hello,
I've got something very interesting: I found the way to dynamically patch code without touching the source.
I'm using module 'runkit' (see: http://php.net/manual/fr/book.runkit.php) which permits to do this without the drawback of the 'Patchwork' (which is pure PHP code): no delay during run time.
So I'm going to provide the 'lock' plugin using this 'runkit' PHP PECL module.
It's already on my Test server running with satisfactory results.
Regards,
Tomolimo

**Comment by tomolimo** [comment]
That's lock is now free from any special hooks: https://github.com/tomolimo/lock
regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
I'm going to modify the lock plugin in order to reflect this change: https://github.com/tomolimo/lock/issues/5
regards,
Tomolimo

**Comment by remicollet** [comment]
runkit is mostly dead unmaintained, and should never be used, except for debugging purpose.

**Comment by tomolimo** [comment]
I though that also till the day I found that it was not:
https://github.com/zenovich/runkit
https://github.com/php/pecl-php-runkit
https://github.com/Crack/runkit-windows
Of course it seems dead on the PECL repository, but some people keep it alive :)!

**Comment by tomolimo** [comment]
Would you agree to add hooks so that we may implement this without runkit?
