### ISSUE TITLE
GLPI racks_plugin.php scripts error

### ISSUE THREAD

**Issue by willowpet** [glpi-project/glpi#5533]
Hi,

I upgraded glpi from 9.1.6 to 9.4, after I use the scripts racks_plugin.php to use new DCIM feature but I have this error:

Some errors triggered, aborting!
array(1) {
  [1]=>
  array(1) {
    [0]=>
    string(40) "Not enough space available to place item"
  }
}

Where I can find more information of this error ?

Best,
Wilfrid

**Comment by trasher** [comment]
Sounds like you have an issue in your original data (multiple elements at the same place); but if this is the case, that was a kind of bug in the plugin that was not known (and therefore not handled in the migration).

You should try to add `-vv` to the command args to get more informations.

**Comment by cedric-anne** [comment]
Hi,

The problem is that the new DCIM feature does checks on available space in rack when trying to add a new element.

You can run the command using `skip_error`. It will do the migration ignoring errored elements. Your element will be created but not put in its rack, so you will have to fix it manually using DCIM UI.

Regards

**Comment by willowpet** [comment]
Hi,

thanks for the help

Best
