### ISSUE TITLE
[9.4] Dropdowns redirect to ajax/comment.php

### ISSUE THREAD

**Issue by zoriax** [glpi-project/glpi#5591]
Hello,

It seems that this bug https://github.com/glpi-project/glpi/issues/4635 is already "active" in version 9.4. I have some task templates and when I select one and select back anotherone, in some case I am redirected to ajax/comment.php.

It's a bit difficulte to reproduce but it always when I look for a dropdown entry.

Thanks

**Comment by cedric-anne** [comment]
Hi,

First #4635 has nothing to do with a redirection. It was a bug occuring when trying to display a dropdown created by a plugin (i.e. GenericObject).

Second, could you provide requested informations, at least:
- Page(s) URL
- Your GLPI setup (you can find it in Setup > General menu, System tab)

We cannot really investigate if we do not even know the context of your issue.

Regards

**Comment by ciadch** [comment]
HI @cedric-anne,

Thanks for your reply

I try to reproduce this issue and here are the steps but I think it come from LDAP users.

I have approx 5000 users syn with my LDAP directory. I try to launch manually sync and I have an error (request launch from bin/console)
 
```
getFromDBByCrit expects to get one resul, 2 found! CommonDBTM::getFromDVVCrit() in /glpi/inc/commondbtm.class.php line 378
```

When I create my template task, In user I saw all my LDAP users (and I have a special profile for these users).
In the template I selected one LDAP  user. So I think when I try to apply my task template, GLPI can't load user because the dropdown list is to  huge. It's why I'm redirected to ajax/comment.php

**Comment by ciadch** [comment]
Hi @cedric-anne,

It seems thant this problem is always active. When a user create a new ticket and select a category or a user, I am redirected randomely redirected to sometimes plugins/moreticket/ajax/ticket.php sometimes to /ajax/usemailUpdate.php and sometimes it works.. 

Do you think it could be a cache problem ? APC or Opcache ?

Thanks for your help

**Comment by cedric-anne** [comment]
Hi,

I really don't know. Maybe it is a problem with `moreticket`. Can you try to disable it and see if the problem persist ?

Regards

**Comment by ciadch** [comment]
Hi @cedric-anne,

I'll investigate with moreticket, I give you a feedback if this plugin as a bug

**Comment by ciadch** [comment]
Hi @cedric-anne,

I found the way to reproduice the issue. It's related to the user Layout. If I chanche layout to for exemple Vertical Split :
![image](https://user-images.githubusercontent.com/12936546/55305216-a2ae6b00-544f-11e9-8b00-f5551e16f59e.png)
Then logout, login and go to Assitance > Create Ticket and select a user in requester dropdown, I was redirected to /ajax/uemailUpdate.php. If I switch back to Tabs on Left layout, it works fine again. 

I have to change once Layout and Color Palette, and I can go back to previous settings (the "buggy" setttings) and it works now for my users (???)

What is strange that this issue appears only on my production environment, I'can't reproduice it on a fresh GLPI install.

Mybe it could help to investigate if necessary.
