### ISSUE TITLE
regression from 0.84

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#57]
http://forum.glpi-project.org/viewtopic.php?id=118624

**Comment by Letargie** [comment]
So... I had a look on it.

The code that set the color of the faq elements in orange :
'a.pubfaq {margin-left:8px; color: #c9993C;}' seems to be ovetake by two classes according to the element examination :
'.ui-widget-content a { color: #659900; }' in jquery-glpi.css
'.ui-widget-content a { color: #222; }' in jquery-ui-1.10.4.custom.min.css
Those classes are in conflict and the one that is diplay is '.ui-widget-content a { color: #659900; }'

Moreover the '.ui-widget-content a { color: #222; }' seems useless because of the following code :
.ui-widget-content{
   border:1px solid #aaa;
   background:#fff url(images/ui-bg_flat_75_ffffff_40x100.png) 50% 50% repeat-x;
   color:#222
}

In order to change the order of priotity changing 'a.pubfaq {margin-left:8px; color: #c9993C;}' in
'a.pubfaq:link {margin-left:8px; color: #c9993C;}' will do the trick when the code is examinate.
However the color is still display in green even if the inspection says otherwise and I absolutely don't know why.

Moreover the function :hover is not displayed for the elements that aren't classed as '.pubfaq' like '.knowbase' :
The css code : a:hover {color: black;} didn't work for the link to the knowbase article.
The hover work only for '.pubfaq' because a 'a.pubfaq:hover {color: black;}' has been add.

In order to correct the hover for '.knowbase' it is necessary to add a 'a.knowbase:hover {color: black;}'
