### ISSUE TITLE
Sorting dropdown elements

### ISSUE THREAD

**Issue by ettalhi** [glpi-project/glpi#5714]
**Describe the bug**
Some users want to see elements sorted into some dropdown lists; especially those which don't come from DB and used as search criteria fields.

I also have discovered a bug in \glpi\inc\plugin.class.php caused by a previous contribution of mine. that bug prevented one of my PR to pass travis-ci steps. so I included the fix in a subsequent PR.

**Page(s) URL**
You will have to adapt this URL to see an example of the dropdown that is not sorted, it is the one used for criteria search :
http://localhost:8080/glpi/plugins/genericobject/front/object.php?itemtype=PluginGenericobjectRadiomobile

**To reproduce**

1. Go to [Assets/Computers] to make a search by criteria.
2. Click on dropdown list of fields used as criteria fields.
4. See elements are not sorted.

**Expected behavior**
Users want to see elements sorted.

**Screenshots**
![issue_dropdown_sorted](https://user-images.githubusercontent.com/29466957/55241451-73aab600-5211-11e9-8ca3-a0f26e9ec352.png)

**Comment by ettalhi** [comment]
this issue should be open again because it is referenced by a [new pull ](https://github.com/VilledeMontreal/glpi/pull/18)to version 9.5/bugfixes .

**Comment by trasher** [comment]
PR is not opened on GLPI project.

**Comment by ettalhi** [comment]
I think our client [VilledeMontreal] has instructed us to make PRs on its branch before they send theme to GLPI project.

**Comment by cedric-anne** [comment]
Hi,

Currently, display order corresponds to declaration order inside `rawSearchOptions`/`rawSearchOptionsToAdd` methods. I am not aware of all the history of the project to be certain, but I will tend to think that this behavior is wanted, in order to display the most used options at the top of the list.

As this list is easilly searcheable (using the search input automatically available when opening the list), I think it is preferable to not change current sort order.

Ping @orthagh @trasher 

Regards

**Comment by trasher** [comment]
Agree with @cedric-anne

**Comment by cedric-anne** [comment]
Hi,

We discussed this change with the core team and we do not want to integrate it.

Regards
