### ISSUE TITLE
[9.4.2] Bug button "Add" in "Rules for assigning an application created through the mail receiver"

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#5836]
Good day, developers.

**Describe the bug**
In the process of setting up a clean GLPI 9.4.2 with the interface language set to Russian, on the page "Rules for assigning an application created through the mail receiver", the (+) button is not available to create a rule for the receiver.

When pointing to (+) it says that "Adding is disabled."

The problem is solved by switching to the interface language - English and then returning to Russian.

**Page(s) URL**
http://ip_GLPI/front/rulemailcollector.php

**Screenshots**
![Error-GLPI-1](https://user-images.githubusercontent.com/21122546/56863052-084c3380-69cb-11e9-9c9e-b879995c2e27.jpg)

![Error-GLPI-2](https://user-images.githubusercontent.com/21122546/56863054-0d10e780-69cb-11e9-95be-6fe3ef7aaa82.jpg)

**Comment by cedric-anne** [comment]
Hi,

How did you access this page ? On my test environment, it is displayed like this only when `RuleMailCollectorCollection::canList()` returns `false`. And when it is the case, link is not available in the rules index page.

Switching language should not change anything, but reloading the page after requirements fulfillment may explain that result changed.

Regards

**Comment by gloomy-master** [comment]
I rolled back to check at that time when I set up, really, if I first log in Administration -> Rules -> "Rules for assigning a ticket created through a mails receiver" then the "Add" button is not available, after which you exit the GLPI and log in again, the button becomes available.

Why not immediately available?

**Comment by cedric-anne** [comment]
Hi,

Problem is menu and breadcrumb are generated once and stored in sessions. In this case, breadcrumb informations do not contains mail collector rules specs as these informations were generated before you had rights to create them (you had no mail collector configured at this moment).

So this is not related to your language. I just found that switching language force regeneration of menu data in session, so that explains this behaviour.

This is a global problem in GLPI and it is a huge job to redesign this part. If you want, during your configuration phase, you can use "debug mode", that force the regeneration of menu on each page, but it can lower your performances.

Regards
