### ISSUE TITLE
Synology Installer

### ISSUE THREAD

**Issue by moodyblue** [glpi-project/glpi#595]
Excuse me for posting here but the GLPI Forum is saying (erroneously) that my IP and email are "spammer", therefore I'm not able to register and post this question in the forum.

The Synology installer available in the Synology catalog (0.85.4) is too old. It's very easy to update the installer to include GLPI 0.90.3 instead (I've done it already). Would it be possible to use github (or the Forum) to distribute more recent versions of the Synology installer ?

**Comment by wawax** [comment]
Hello, 

Please contact Synology directly, as we do not maintain packages for this NAS distribution. 

Regards, 


----- Mail original -----

De: "moodyblue" <notifications@github.com> 
À: "glpi-project/glpi" <glpi@noreply.github.com> 
Envoyé: Mercredi 13 Avril 2016 15:33:52 
Objet: [glpi-project/glpi] Synology Installer (#595) 



Excuse me for posting here but the GLPI Forum is saying (erroneously) that my IP and email are "spammer", therefore I'm not able to register and post this question in the forum. 

The Synology installer available in the Synology catalog (0.85.4) is too old. It's very easy to update the installer to include GLPI 0.90.3 instead (I've done it already). Would it be possible to use github (or the Forum) to distribute more recent versions of the Synology installer ? 

— 
You are receiving this because you are subscribed to this thread. 
Reply to this email directly or view it on GitHub 



-- 
Walid Nouh 
R&D Manager 
wnouh@teclib.com 

3 rue Doria, 
34000 Montpellier - France 
Landline. +33 1 79 97 02 78 - Direct phone line : +33 1 79 97 72 93 - Fax. +33 1 72 70 31 18 
Facebook | Twitter | Website Teclib' 

Discover our Products!
