### ISSUE TITLE
Text editor for changes is different from text editor for ticket and problem

### ISSUE THREAD

**Issue by usrqmor** [glpi-project/glpi#6062]
Hello,

I see the text editor for changes are different compared to the text editor for tickets or problems. 
There is less available options for the changes. Is it a bug or do I need to create a suggestion ?
![image](https://user-images.githubusercontent.com/17316903/60026317-a0009200-969b-11e9-941d-ae6bfc32ca30.png)
![image](https://user-images.githubusercontent.com/17316903/60026492-f1a91c80-969b-11e9-961b-45c32f5d261f.png)

Thanks for the help

**Comment by trasher** [comment]
This is not a bug, but certainly a feature.
Adding rich text support when missing may be a real nightmare, this could be a quite important change.

**Comment by usrqmor** [comment]
Hi @trasher, 
Thanks for the reply. I understand the problematic. I'll wait.
Have a good day.

**Comment by phamorais** [comment]
Is there a provision for inclusion of the Rich Text for this?

**Comment by cedric-anne** [comment]
Hi,

This is not planned for now. If you want to sponsor this enhancement, feel free to contact us at contact@teclib.com.


Regards

**Comment by cconard96** [comment]
Was this not already done for some time now? I have no memory of making this specific change, but it looks like I enabled that when I brought the timeline to Changes and Problems (9.4.0). I think it was part of a refactor bringing most of the logic into the CommonITILObject class instead of Ticket. At least on a clean install of 9.5.0, this feature exists.

![Selection_031](https://user-images.githubusercontent.com/17678637/86863518-59f55100-c099-11ea-9b89-d798e78ef0a8.png)
![Selection_032](https://user-images.githubusercontent.com/17678637/86863523-5bbf1480-c099-11ea-906e-20b2b9945592.png)
![Selection_033](https://user-images.githubusercontent.com/17678637/86863527-5d88d800-c099-11ea-8984-101861b913fe.png)

**Comment by phamorais** [comment]
@cconard96 Only in 9.5.

But only in the description of the change. For the other fields, it still does not, making a better experience unfeasible, including with the formcreator.

**Comment by phamorais** [comment]
@cconard96 @cedric-anne 
Hey guys!
At the time of Creating a "change" the field does not yet have the Rich Text.

**Comment by tomolimo** [comment]
Hello @phamorais 
Here is a screen copy of the creation of a change on the 9.5.5... The rich text toolbar is present...
![image](https://user-images.githubusercontent.com/7569958/135397635-b25fac68-455a-40e8-803b-16b691437f82.png)

Thank you
Regards,
Tomolimo
