### ISSUE TITLE
[9.4.3] [2019-07-16 13:49:03] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit()  error

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#6145]
```
[2019-07-16 13:49:03] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/inc/commondbtm.class.php 5084  {"user":"@vs-glpi.infotel.com","mem_usage":"0.000\", 22.68Mio)"} 
```

I add trace : 
```
CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/inc/document.class.php 567 CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/inc/commondbtm.class.php 5084 CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/inc/itilfollowup.class.php 207 CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/inc/commondbtm.class.php 1148 CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/inc/mailcollector.class.php 756 CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/inc/mailcollector.class.php 1796 CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/inc/crontask.class.php 829 CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 379
BackTrace : /usr/share/glpi/front/cron.php 83 CommonDBTM::getFromDBByCrit() in /usr/share/glpi/inc/commondbtm.class.php line 385
getFromDBByCrit expects to get one result, 51 found! glpi_documents 
```

I see that the error comes from : 

Function addfiles into commondbtm.class.php

// Check for duplicate
if ($doc->getFromDBbyContent($entities_id, $filename)) which use getFromDBByCrit

**Comment by tsmr** [comment]
Same error on auth.class.php : 

```
if (!$tmpuser->getFromDBByDn(Toolbox::addslashes_deep($user['user_dn']))) {
                     //This should never happened
                     //If a user_dn is present more than one time in database
                     //Just skip user synchronization to avoid errors
                     continue;
                  }
```

```
function getFromDBbyDn($user_dn) {
      return $this->getFromDBByCrit(['user_dn' => $user_dn]);
   }
```

**Comment by cedric-anne** [comment]
Hi,

You have 2 distinct issues here, you should open another one related to your second comment.

For first issue, I reproduced using following steps:
 - I created a ticket on entity A with an attached image, a document entry is created,
 - I created a ticket on entity B with same image attached, another document entry is created, having same `sha1sum` but another `entities_id`,
 - I transfered second ticket on entity A, resulting in a duplicate in document entries due to an update of `entities_id` of the second document entry.

I am pretty sure that this kind of problem will appear often only if:
 - mailcollector create tickets in different entities from mails with images in signatures in different entities,
 - then one of thoose tickets is transfered in same entity as another ticket having same attached image.

Simple fix is to get first matching entry in `Document::getFromDBbyContent()` instead of using `CommonDBTM::getFromDBByCrit()` method. For duplicates already existing in DB, not sure it is mandatory to work on a "deduplicate" migration.

Regards

**Comment by cedric-anne** [comment]
@tsmr ,

Can you test #6148 ?

Regards
