### ISSUE TITLE
Support hosting behind a context

### ISSUE THREAD

**Issue by bcantera** [glpi-project/glpi#6196]
As stated in https://community.containo.us/t/traefik-routing-issues/624/4, when GLPI is behind a context, content is not served in the correct way which causes to load invalid links. Reproduction case and more details on the issue is in the link with traefik.

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by bcanterac** [comment]
Sorry, ticket template attached below:


**Describe the bug**
As stated in https://community.containo.us/t/traefik-routing-issues/624/4, when GLPI is behind a context, content is not served in the correct way which causes to load invalid links. 

A clear and concise description of what the bug is.
The HTML generated by GLPI starts with /xxxx,
(example <script type="text/javascript" src="/lib/jquery/js/jquery.min.js?v=9.4.3"></script>),
which are assuming the webapp is always served under the root path of the website (aka. /).
GLPI is not built for supporting hosting behind a context by default.


**Page(s) URL**
https://github.com/glpi-project/glpi/issues/new?template=bug_report.md

If applicable, page(s) URL where the bug happens.
-

**To reproduce**

Steps to reproduce the behavior:
Deploy GLPI in a docker container behind a reverse proxy like traefik

**Expected behavior**
Content is served by GLPI pointing to / instead /path when using path redirection in the reverse proxy

A clear and concise description of what you expected to happen.
Load GLPI normally as it should be when served at /

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

If applicable, add screenshots to help explain your problem.


**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

Add any other context about the problem here.

**Comment by cedric-anne** [comment]
Hi,

I often use GLPI hosting behind a context (i.e. `http://my.domain/glpi/`) and I did not face this issue. However, I never used GLPI behind a context AND a proxy, so I cannot says if it is a server configuration issue or a case that is not handled correctly by the application.

The "context" is computed by the method [Config::detectRootDoc()](https://github.com/glpi-project/glpi/blob/9.4.3/inc/config.class.php#L2050). It may help you to debug. If you find a solution, feel free to open a pull request.

You can also ask for community support on [forum](https://forum.glpi-project.org/) or [get a subscription for a professionnal support](https://glpi-project.org/subscriptions/).

Regards
