### ISSUE TITLE
LDAP sync user after rename login (create a new one, not update)

### ISSUE THREAD

**Issue by sazanof** [glpi-project/glpi#6212]
Hello! There is a problem when a domain controller renames a user (edit login), then it is not updated in GLPI. This user is added as a new one, naturally without any requests. It seems to me users need to be added on the unique identifier of the container in the domain controller. Then the connection of users will not be lost when you change  login

**Comment by flegastelois** [comment]
Hi,

You must correctly set the "Synchronization field" (which exists since GLPI 9.2) in your LDAP directory configuration (Setup > Authentication > LDAP directories), so that a user's login can be modified in the LDAP directory without creating a duplicate in GLPI.

In predefined templates, we advise to use, for example:
- for Microsoft Active Directory : “objectGUID” attribute (official unique identifier of an object) ;
- for OpenLDAP: the attribute “entryUUID”
**Caution:** Some attributes on Microsoft Active Directory are not supported (“objectSID” for example).

Regards,
