### ISSUE TITLE
Bug api ticket followup

### ISSUE THREAD

**Issue by Akuket** [glpi-project/glpi#6474]
**Describe the bug**

When a ticket is created by a user classically and then someone tries to reply to that ticket by using the api, an error 400 appears. If you make the same thing with a ticket created by the api, it works well.

**To reproduce**

1. Create a ticket in the glpi interface
2. Make a ticket followup by using the api with those parameters:
{
  "input": {
    "items_id": `ticketId`,
    "itemtype": "Ticket",
    "content": "test",
    "is_private": "0",
    "requesttypes_id": "2"
  }
}
You will normally have a 400 bad request.

**Expected behavior**

Create the ticket followup

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.4 ( => /opt/glpi)
Installation mode: TARBALL
```

Regards

**Comment by glpibr** [comment]
#EN  
GLPi 9.4.4 has the same error.
I even tested with the super admin user.
The web interface works perfectly but via API gives permission error.

#PT_BR
O GLPi 9.4.4 possui o mesmo erro.
Testei inclusive com o usuário super-admin.
Na interface Web funciona perfeitamente mas via API dá erro de permissão.

![image](https://user-images.githubusercontent.com/22614882/69569449-6f02f100-0f9c-11ea-8123-5d2b39b14e85.png)

**Comment by glpibr** [comment]
#EN 
The problem is:
There is a new method created for tracking addition that is not very clear / documented.
But in the following print you can see the changes:

**New Method**

- itilfollowup

**JSON Input**
```
{
   "input":
      {
         "itemtype": "Ticket",
         "items_id": "2019032882",
         "content": "Verdanatech.com tracking test",
         "is_private": "0"
      }
}
```

As I understand it, they created the new method and, while maintaining the old method, did not keep it functional, breaking applications that already consumed it. This is not very good to see in an API (methods being broken).


#PT_BR
O problema é:
Existe um novo método criado para adição de acompanhamento que não está muito claro/documentado.
Mas no print a seguir você pode ver as alterações:

**Método Novo**

- itilfollowup

**JSON Input**
```
{
	"input": 
		{
			"itemtype":"Ticket",
			"items_id":"2019032882",
			"content": "Teste de acompanhamento Verdanatech.com", 
			"is_private": "0" 
		}
}
```

Pelo que entendi, criaram o novo método e, apesar de manterem o antigo, não o mantiveram funcional, quebrando aplicações que já o consumiam. Isso não é muito bom de ser ver em uma API (métodos sendo quebrados).


![image](https://user-images.githubusercontent.com/22614882/69582289-07a66a80-0fb7-11ea-8732-7e4b1343c871.png)

@Akuket 

#verdanatech #5859

**Comment by cedric-anne** [comment]
Hi,

Sorry for the late answer.

TicketFollowup class has been deprecated and replace by ITILFollowup class since GLPI 9.4.0, and this was documented in our changelog.

I do not understand why you had this permission error, as we keep the old TicketFollowup class in the code to handle this kind of case. I do not have time to debug this part right now, but it looks like a bug somewhere in rights check.

By the way, using TicketFollowup is deprecated and this class will be removed in 9.5.0, so you will have to update your code anymays.

Regards
