### ISSUE TITLE
[9.4.4]Ticketcreator gets notified about his own replies

### ISSUE THREAD

**Issue by At-M** [glpi-project/glpi#6549]
When the creator of the ticket (requester) is commenting on the ticket, there's a notification mail sent out to the creator itself too.

**To reproduce**

(Enabled E-Mail Notifications and using a User with a working E-Mail)

1. create a ticket
2. post a followup message
3. A mail about their own answer should arrive soon

The logs don't seem to have mail-related issues :/

`GLPI 9.4.4 (/glpi => /var/www/html/glpi) Installation mode: TARBALL
`

**Comment by Eon9D** [comment]
What about:
![image](https://user-images.githubusercontent.com/32479943/68417949-a0f01700-0197-11ea-931f-93c868654a4d.png)

Same in user profile?

**Comment by At-M** [comment]
Hm, i actually didn't see that, thanks!
But even if I change it to "no" and change it in user profile too, it still happens

**Comment by cedric-anne** [comment]
Hi,

I did some archeology and found the reason for this behavior. Send a notification even if the user does not wish to be notified of its changes is intentional, in order to provide proof of creation of the ticket.
See https://forge.glpi-project.org/issues/5102

For followups, you should not receive notifications if you ask to not be notified of your changes.

Regards
