### ISSUE TITLE
Ticket e-mail with attachment bigger than 10mb

### ISSUE THREAD

**Issue by Tradition2** [glpi-project/glpi#6573]
If we upload attachments on a ticket and they ammount to 10mb or more the queuenotification hangs and dosent send any e-mail not even manually i have to delete from the queue in order for the other tickets to be sent i've looked everywhere for a fix and coudnt find it using GLPI 9.4.4

**Comment by Tradition2** [comment]
anyone?

**Comment by mab18** [comment]
Hi,

did you configure maxmem and others in php.ini?

**Comment by Tradition2** [comment]
Yes i did =/ yet no luck

**Comment by cedric-anne** [comment]
Hi,

We use PHPMailer library to send emails.
As you can see https://github.com/PHPMailer/PHPMailer/issues/1863, https://github.com/PHPMailer/PHPMailer/issues/1712, https://github.com/PHPMailer/PHPMailer/issues/374 and certainly in many forums, PHPMailer consumes lot of memory to handle files attachements.

Unfortunately, we do not really have time to benchmark alternative libraries right now, so unless someone proposes us a working implementation using a more optimized library, this problem will not be solved.

Regards

**Comment by Tradition2** [comment]
just so you guys know i increse the php memory to 512MB and its working now it takes some time but works

**Comment by andrepetinga** [comment]
Hello.
In my case, for email messages with total size greater than 20MB, the only way to fix the problem was to change this:

/etc/nginx/conf.d/glpi.conf

•	memory_limit = 512M
•	post_max_size = 0 
•	upload_max_filesize = 20M

/etc/php-fpm.d/www.conf

•	memory_limit = 512M
•	post_max_size = 0
•	upload_max_filesize = 20M

Hope this helps someone.
