### ISSUE TITLE
Drop colorpicker lib

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#6584]
Color picker is natively implemented in browsers nowadays.

Maybe should we just remove the spectrum Javascript lib; but I do not know if that can cause issues where used.
Along with standard usage from Html class, this is used in kanban and impact javascript.

**Comment by trasher** [comment]
ping @cedric-anne @AdrienClairembault @cconard96

**Comment by AdrienClairembault** [comment]
Color pickers are natively implemented in "only" 90% of browers : https://caniuse.com/#feat=input-color (and I guess companies are above the average concerning IE11 usage...).

I don't see too much of an issue for impacts as it does no use alpha (only set value from user input and programmatically from DB on load).

**Comment by cconard96** [comment]
Not sure how I missed this ping.
Personally I don't think supporting IE is a good idea. It just holds GLPI back from using modern features (like ES6, etc).
Kanban only uses it because in was used in the Project form (I wanted to be consistent). A small patch can be made to drop usage of it in this feature.
