### ISSUE TITLE
mailcollector not working not creating ticket

### ISSUE THREAD

**Issue by YuppieJupp** [glpi-project/glpi#6844]
Hi,

We have a problem with the mailcollector in version 9.4.4.
We have changed our exchange server from 2010 to 2016. After that only the server adress in the receiver settings was changed. Now the mails where taken from the inbox oft he mailbox an we can see them in the list of not imported emails with the following error.
„Unable to affect the email to an entity“
No ticket was created. Neeed some help

**Comment by cedric-anne** [comment]
Hi,

Rules that are used to affect an entity to incoming emails are located on page `/front/rulemailcollector.php`. It seems that they are no longer matching, maybe due to some changes in your mail server configuration.
As this does not seems to be a bug, I close this issue. Feel free to ask for community support on [forums](https://forum.glpi-project.org/) or for professionnal support via the [GLPI Network](https://glpi-project.org/glpi-network/).

Regards
