### ISSUE TITLE
Problem: different behavior for IP networks as the entity

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#701]
GLPI version 0.90 bugfixes

In a computer when displaying network ports, IP networks are displayed depending on the entity.

Parent entity : 
![image](https://cloud.githubusercontent.com/assets/15138371/15746378/a21b6898-28d6-11e6-82f1-aa6e7b978ae9.png)

Entity of the object : 
![image](https://cloud.githubusercontent.com/assets/15138371/15746443/d31581ae-28d6-11e6-986b-52fcb59e8c15.png)

Fichier ipnetwork.class.php, from line 563.

**Comment by yllen** [comment]
No problem for me.
In your parent entity you don't see "Réseau IP" because you don't have created them in Setup > Dropdown.

**Comment by tsmr** [comment]
There is a problem of visibility for me.

I have a computer on child entity, his network IP informations are into child entity too.

So i cannot see the informations of my computer whereas i'm logged on root entity (for example).

You see only the column then you are on the computer entity and this is not normal

**Comment by tabad** [comment]
Hello,

I was ready to open a new issue about this bug because, as @tsmr said it's a bug, but I have found this one closed and I hope someone reconsider it and open it again.

@yllen's  justification to close this issue makes no sense to me. The reason is simple: whether you are in an entity, GLPI shows the objects inside that entity and inside of her sub-entities all time --even whether you are not in the entity which those objects are defined-- as long as the recursive view of the entities is activated. And there are a lot examples of that.

Please, reconsider this matter and open it again.

Regards,

**Comment by tabad** [comment]
I forget to indicate the GLPI version; it's v9.2.4.

**Comment by tabad** [comment]
This issue should be labelled as "Bug" and not "Invalid".

Thanks in advance,
