### ISSUE TITLE
cPanel - PHP7.3 - GLPI 9.4.5 - Error Cron...

### ISSUE THREAD

**Issue by thytetgc** [glpi-project/glpi#7025]
I'm running GLPI 9.4.5 in a cPanel environment, running with PHP 7.3

Everything looks OK, but the automatic actions are not working.

Doing a test via CLI I get the error:

**/usr/local/bin/php /var/home/hostlpne/public_html/glpi/front/cron.php --debug**

`Fatal error: Uncaught Error: Class 'Zend\Serializer\Adapter\PhpSerialize' not found in /var/home/hostlpne/public_html/glpi/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php:30
Stack trace:
#0 /var/home/hostlpne/public_html/glpi/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(764): Zend\ServiceManager\Factory\InvokableFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'Zend\\Serializer...', NULL)
#1 /var/home/hostlpne/public_html/glpi/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('Zend\\Serializer...')
#2 /var/home/hostlpne/public_html/glpi/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(152): Zend\ServiceManager\ServiceManager->get('Zend\\Serializer...')
#3 /var/home/hostlpne/public_html/glpi/vendor/zendframework/zend-serializer/src/Serializer.php(43): Zend\ServiceManager\AbstractPluginManager->get('PhpSerialize', NULL)
#4 /var/home/hostlpne/public_html/glpi/vendor/zendframework/ze in /var/home/hostlpne/public_html/glpi/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php on line 30`

Even using --force parameters and adding functions eg mailgate, queuednotification or whatever, it gives the same error.

Here is an image of PHP
https://www.imagemhost.com.br/images/2020/03/05/PHP.png

**Comment by dani** [comment]
Indeed. Same error on a CentOS 7 server. All previous versions of PHP are KO (7.0, 7.1, 7.2, 7.3). Only 7.4 works. (but can't use 7.4 right now because it makes FusionInventory plugin to output several GB of error logs / day)

**Comment by cedric-anne** [comment]
Hi,

Sorry about the delay.

I do not know how you installed GLPI on your server (you did not provide informations requested during issue creation), but it seems to be an issue with a specific environment and/or an issue due to a bad manipulation during installation process.

I close this issue as is does not seems to be a GLPI bug.

Feel free to ask for community support on [forums](https://forum.glpi-project.org/) or for professionnal support via the [GLPI Network](https://glpi-project.org/glpi-network/).

Regards
