### ISSUE TITLE
[9.4 - 9.5] Vertical split layout - Display problem with full screen option from followup

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7194]
1. In preferences : Use Vertical split layout

2. In an existant ticket, launch creation of a new followup

3. Click on Full screen option of tinyMCE
![image](https://user-images.githubusercontent.com/13178158/80578675-221ebd00-8a09-11ea-8bf3-23792e5696b6.png)

4. Result : The principal form is not hidden

![image](https://user-images.githubusercontent.com/13178158/80578748-45e20300-8a09-11ea-9f63-3a9910a6af94.png)

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug.
It is due to the fact that main form (`.layout_vsplit.form .form_content`) has `z-index: 1` and tabs div (`.layout_vsplit #page .glpi_tabs`) has `z-index: 2`, so main form will alway be displayed in front of tabs content.

I do not know why this has been done like that, but I am not confident in changing it.

Regards
