### ISSUE TITLE
[GLPI 9.5] - dependencies installation script maybe incompatible with windows

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#7275]
Hello

I try to install glpi 9.5 to test it.

I followed instructions but it does not work

![image](https://user-images.githubusercontent.com/30655170/82027421-86da4880-9694-11ea-95d9-3557e50f5931.png)
Thank you for your help

**Comment by trasher** [comment]
The `composer` command is not found. Can't really help as I do not use windows.

The dependencies install script is maybe not working on windows (I'm not sure anyone tested before); if you really want to use GLPI development tools under windows, then you (or someone else using the same operating system) will have to fix yourself and open a pull request. 

If you just want to use GLPI, prefer downloading the latest branch [nightly build](https://forge.glpi-project.org/tarballs).

**Comment by cedric-anne** [comment]
Hi,

This command works on windows, but it requires to have both composer and node/npm installed on the system.

Regards

**Comment by yalgva** [comment]
Hello, 

Could you tell me where and how to install node/npm ?

Do I need to install composer ?

Will it be included in final version ?

Thank you for your answer

**Comment by cedric-anne** [comment]
Hi,

Sorry for the delay. I am currently working on updating building tools to make the 9.5 nightly build producing an archive containing all dependencies. So with it, you will not have to install composer nor npm/node on you system to test GLPI 9.5.

Build is not yet pushed to a stable URL, but you can get the archive I just built on https://github.com/cedric-anne/glpi/suites/754498219/artifacts/7781576 . It is a zip containing the archive, but I cannot remove the zip step due to Github UI limitations.

Regards
