### ISSUE TITLE
Testing DB timezone data - Wrong url

### ISSUE THREAD

**Issue by pieterliekens** [glpi-project/glpi#7498]
While installing 9.5 RC2, system is Testing DB timezone data. I've got an error, no problem. But he links to te website https://glpi-install.readthedocs.io/en/latest/timezones.html witch doesn't exists.

**Page(s) URL**

https://glpi-install.readthedocs.io/en/latest/timezones.html

If applicable, page(s) URL where the bug happens.

Install.

**Expected behavior**

A working link to fix the problem

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by trasher** [comment]
Hi, this is because the doc is not yet published (will be on final release). The page is here (replace master with develop):
https://glpi-install.readthedocs.io/en/develop/timezones.html

We won't change this URL since the next release will probably be the latset, and the doc will be published at this time :)
