### ISSUE TITLE
[HELP] GLPI version 4 - Datacenter 

### ISSUE THREAD

**Issue by massinlaaouaj** [glpi-project/glpi#7593]
Hello, I would like to use GLPI version 4 in production, but it seems that it doesn't have "DATACENTER MODE". Do you plan to add it in the future?

Thanks.

**Comment by orthagh** [comment]
Hello.

Last (current) version of glpi is **9.4**.

We have DCIM mode since 9.3 version. You can view some screenshots of the feature in the screenshots provided in the readme : 
https://github.com/glpi-project/glpi#some-screenshots

of in the relative blog news of 9.3 : https://glpi-project.org/glpi-9-3-itsm-software/

Regards
