### ISSUE TITLE
GLPI 9.5.1 UPGRADE MAIL BUG

### ISSUE THREAD

**Issue by MOUSTACHEBIKES** [glpi-project/glpi#8005]
Hello,

We update GLPI to 9.5.1 version with the copy/past method
GLPI is installed on Debian 10

We have a problem with mail collector, the debug mode display this message :

Uncaught Exception Laminas\Mail\Header\Exception\InvalidArgumentException: Invalid header line for Content-Disposition string - incomplete continuation in /usr/share/glpi/vendor/laminas/laminas-mail/src/Header/ContentDisposition.php at line 84

Thanks for your Help

**Comment by cedric-anne** [comment]
Hi,

This is due to a bug in the library we use to fetch emails. I proposed a fix, see https://github.com/laminas/laminas-mail/pull/111 .

Can you attach here the email that cause the issue into `.eml` format here and on https://github.com/laminas/laminas-mail/pull/111 ? It may help us to validate the fix and to get a review on the proposed fix.

Regards

**Comment by MOUSTACHEBIKES** [comment]
Dear Cédric-Anne,

All is good
I confirme your solution fixed the problem with mail sent in GLPI from an Apple Mail client with attached files.

Good journey and thanks again :-)

Regards

**Comment by trasher** [comment]
Fixed then, will be part of 9.5.2
