### ISSUE TITLE
Merge email to the same ticket in glpi 9.5.1

### ISSUE THREAD

**Issue by SakisGalanis** [glpi-project/glpi#8016]
Hello,
A user sends email to glpi and a ticket is created. The person who is assigned to the ticket responds with a followup or a task and the requester receives the answer. If the requester tries to answer:
1. the email delivered to glpi's receiver mailbox ( in web app is located to the inbox )
2. the mailgate in glpi receives the email ( receivers inbox becomes empty )
3. the requester's email is vanished! It is not merged to the original ticket, it is not shown as new ticket and it is not listed in the notifacation queue

Thanks

**Comment by cedric-anne** [comment]
Hi,

This issue seems to be a configuration issue (check `Administration > Rules > Rules for assigning a ticket created through a mails receiver` and `Setup > General > Assistance`).

If you need help for receiver configuration, you can get community support on [forums](https://forum.glpi-project.org/) or you can consider [taking a subscription](https://glpi-project.org/subscriptions/) to get professional support.

Regards

**Comment by SakisGalanis** [comment]
Thak you very much
