### ISSUE TITLE
I have upgraded from 9.4.7 to 9.5.2 and LDAP access doesn't work

### ISSUE THREAD

**Issue by cpasDav** [glpi-project/glpi#8188]
I have upgraded from 9.4.7 to 9.5.2 and I also have this problem.
From LDAP settings, the LDAP connexion test is fine.
However I can't sync users neither log in using ldap account.

Any idea?

_Originally posted by @cpasDav in https://github.com/glpi-project/glpi/issues/7838#issuecomment-718037568_

**Comment by cedric-anne** [comment]
Hi,

Please provide requested informations in issue form (steps to reproduce, logs, GLPI setup informations, ...).

Regards

**Comment by cpasDav** [comment]
Hi,

GLPI 9.5.2 is installed on centOS 8.2.2004
Installation mode Tarball

There is no glpi plugin installed.

I updated glpi 8.4.7 to 9.5.2 and I get several problems.
Then I performed a new install of 9.5.2, then I restored the database and files directory.
When I go to LDAP settings, the LDAP connexion test is OK, however i can't find users from LDAP while from glpi 9.4.7 it worked with those parameters.

From a support forum I have read that the password encryption changed which implies to refill all glpi passwords.
When I re-fill the password of the glpi account used to sync LDAP, the LDAP connexion always fails.
If I remove the password, the LDAP connexion test always succeeds.

But in any case I'm never able to find users through LDAP.

Regards

**Comment by coldscientist** [comment]
I'm using GLPI 9.5.2 and it's authenticating fine into my Active Directory (AD) server using SSL.
Are you using SSL to connect to the LDAP server? If so, please note that CentOS 8 enforces a [cryptography policy](https://access.redhat.com/articles/3666211) by default, so legacy communications protocols, like TLS 1.1 and lower, are blocked by default and must be manually enabled. If your LDAP server is using Windows Server 2008 R2 and lower, you must install hotfixes to add the TLS 1.2 support into it and then enable it manualy through registry. This post was written by me and it's in Portuguese, but Google Translate is your friend: https://eduardomozartdeoliveira.wordpress.com/2020/09/25/ldap_sasl_bindsimple-cant-contact-ldap-server-1-ao-conectar-via-ldap-sobre-ssl-ldaps/
Windows Server 2003 doesn't support TLS 1.2, so you must use TLS 1.0 by decreasing the accepted cryptography level into your CentOS 8 crypto policy.
If it helps, I'll be sharing the settings that I'm using into my environment and that's working fine using SSL. You don't need to use SSL if you don't want to, but I personally recomends it if you want to ensure that the communication between LDAP and your CentOS 8 is secure. I'm using CentOS 8 to host my GLPI instance too, and documented how to enable LDAPS connections using AD CS into my blog (again, Google Translator is your friend): https://eduardomozartdeoliveira.wordpress.com/2020/09/02/configurando-apache-httpd-pure-ftpd-e-ispconfig-com-tls-ssl-usando-certificados-do-microsoft-ad-cs/
Here is the settings that I'm using:

```
Name: Active Directory
Default Server: Yes
Server: ldaps://ad.example.com
Connection Filter: (&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(memberOf=CN=Service Accounts - Deny Interactive Logon,OU=EXAMPLE,DC=ad,DC=example,DC=com))(!(sAMAccountName=fabrica)))
Base DN: DC=ad,DC=example,DC=com
RootDN (for non anonymous binds): glpiaduser@ad.example.com
Password (for non-anonymous binds): (Type the password for glpiaduser account)
Login Field: samaccountname
Synchronization field: objectguid
```
Replace ``ad.example.com`` with your DNS domain name/LDAP server. You will need to change Base DN to match your environment too. You need to fill the Root DN field if your LDAP server doesn't support anonymous queries. By default, Active Directory doesn't support anonymous queries so if you're using Active Directory, make sure that you created an user that is member only of the "Domain Users" group. You can notice that I created a custon group called "Service Accounts - Deny Interactive Logon". I use this group to create accounts that do not have rights to login into the computers available at my environment, so even if the password of the 'glpiaduser' is compromised (that belongs to "Service Accounts - Deny Interactive Logon" group too), it can't logon into my local computers. I also excluded the LDAP user 'fabrica' from being imported into GLPI using this Connection Filter. Keeped it only as an example, if you're interesting in not importing some user or group from LDAP into GLPI.

If you're not using TLS, replace ``ldaps://ad.example.com`` with ``ldap://ad.example.com`` (notice that the 's' from 'ldap' was removed from URI). Even if you're using TLS, make sure that you have disabled TLS into the "Advanced Information" tab at your LDAP directory config. Informing the "ldaps://ad.example.com" (using the 's') at the server field is enough to using encrypted connections because the way that 'ldap_connect()' function works, accordingly to GLPI documentation: https://wiki.glpi-project.org/doku.php?id=en:ldap

If you're using custom fields, please make sure that you're using lowercase attributes (e.g. ``samaccountname`` instead of ``sAMAccountName``) into 'User' and 'Group' tabs of LDAP directory configuration, as stated at GLPI documentation: https://wiki.glpi-project.org/doku.php?id=en:ldap

If you're still having trouble with this config, please post the output of the following command (run it into your CentOS 8 terminal - you may install ldapsearch through YUM installing the ldap* packages: ``yum install openldap*``):

```
ldapsearch \
    -x -H ldaps://ad.example.com \
    -D "glpiaduser" \
    -W \
    -b "dc=ad,dc=example,dc=com" "cn=Eduardo Mozart de Oliveira" \
    -s sub "(cn=*)" cn mail sn
```

Replace ``ad.example.com`` with your own LDAP server address and the Base DN and CN with the Name of an user that already exists into your LDAP server. If you're not using TLS, replace ``ldaps://ad.example.com`` with ``ldap://ad.example.com`` (notice that the 's' from 'ldap' was removed from URI). Your CentOS 8 must be able to connect

**Comment by koddajr** [comment]
same problem here... from 9.4.6 to 9.5.2 cant connect LDAP but say OK on connection tests through GLPI

**Comment by cpasDav** [comment]
Thanks for your post @coldscientist 
The AD is windows server 2003 (will be changed very soon).
I don't use ldaps, so if I understood correctly your post in that case I have nothing special to set.

Here attached, the output of the command.

![output](https://user-images.githubusercontent.com/73603880/98108284-fb4fb080-1e9b-11eb-88e2-73e99aa6a068.jpg)

Did you see the weird part of my initial post?
In the GLPI ldap settings, if I fill the password of the AD user I created for glpi, then the connexion test failed.
If I clean the password field, the connexion succeeds!
But in both case I can't update/import users using ldap.

**Comment by coldscientist** [comment]
> Thanks for your post @coldscientist
> The AD is windows server 2003 (will be changed very soon).
> I don't use ldaps, so if I understood correctly your post in that case I have nothing special to set.
> 
> Here attached, the output of the command.
> 
> ![output](https://user-images.githubusercontent.com/73603880/98108754-cc860a00-1e9c-11eb-95d4-3bff6db295d6.jpg)
> 
> Did you see the weird part of my initial post?
> In the GLPI ldap settings, if I fill the password of the AD user I created for glpi, then the connexion test failed.
> If I clean the password field, the connexion succeeds!
> But in both case I can't update/import users using ldap.

It seems to be working fine, the crypto policy from CentOS 8 maybe not affecting your environment because you're not using cryptography at all.
Into my environment, I set the LDAP connection using GLPI 9.5.1 and upgraded it manually through Tarball to 9.5.2 when it was released. Maybe you could give I try.

Adapting the settings to your environment, I would use into GLPI:

```
Name: Active Directory
Default Server: Yes
Server: ldap://ad.example.com
Port: 389
Connection Filter: (&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
Base DN: DC=ad,DC=example,DC=com
RootDN (for non anonymous binds): glpiaduser@ad.example.com
Password (for non-anonymous binds): (Type the password for glpiaduser account)
Login Field: samaccountname
Synchronization field: objectguid
```

Please make sure that the LDAP Port is correctly set (389). Maybe you can try to specify the user using "CN=glpiaduser,CN=Users,DC=ad,DC=example,DC=com" to give a try.

Make sure that "Use TLS" is disabled into "Advanced settings".

Any PHP error is logged into "php-errors.log" into ``<GLPI_ROOT>/files/_logs``, e.g. /var/www/glpi/files/_logs. Please also checks "error.log" and "access.log" files available at ``/var/log/httpd`` to see if there's any errors. But "php-errors.log" should be enough to detect errors into ldap_connect() function.

You can also try to sync LDAP users using the CentOS 8 command line:

```
cd /var/www/html/glpi/bin
php -q -f console ldap:sync --ldap-server-id=1 --no-interaction -vvv
```

It will print verbose information about the connection to the LDAP server.

**Comment by cpasDav** [comment]
@coldscientist, my LDAP settings were already good and fit your example.
I have reset the password of the glpi user in the AD, and guess what... now the connection test using glpi user/password works, and the LDAP sync works also!

So it seems the very complex password I set earlier caused problem in GLPI.

note: I am fully sure the password was correctly filled as I reset several times the glpi user password using that complex password.

**Comment by cedric-anne** [comment]
@cpasDav 

Could you give an example of a complex password that fails ?

Regards

**Comment by cpasDav** [comment]
8676<88Vdcde&$v

**Comment by cpasDav** [comment]
found same password problem under email notification.
The email test to admin failed with the right mail account password. This password contain letters, numbers and a '@'.
I tested using another email account which contains only letters and numbers and the test worked.

**Comment by coldscientist** [comment]
When you said it started working when you reset the password of glpi user I thought that it could be related to the password of the account expired (make sure that you selected the password to never expire at the User properties at ADUC). But it does not appears to be the cause, maybe GLPI is somehow trying to parse the password, maybe to avoid MySQL injection, but it seems like a bug to me.

**Comment by cpasDav** [comment]
It was already set to never expire


> Le 9 nov. 2020 à 18:31, Eduardo Mozart de Oliveira <notifications@github.com> a écrit :
> 
> ﻿
> When you said it started working when you reset the password of glpi user I thought that it could be related to the password of the account expired (make sure that you selected the password to never expire at the User properties at ADUC). But it does not appears to be the cause, maybe GLPI is somehow trying to parse the password, maybe to avoid MySQL injection, but it seems like a bug to me.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.


***********************************************************************
Le présent message électronique n'engage nullement le CPAS de Wavre. 
Seuls les documents portant conjointement la signature du Président et du
Directeur général du Centre sont susceptibles de l’engager. Il s'agit donc d'un
document préparatoire envoyé sous la seule responsabilité de son signataire.
Le présent document n'établit aucun lien de droit, ne peut être constitutif
de reconnaissance préjudiciable, et ne peut constituer, ni à lui seul, ni en
combinaison avec d'autres messages, des pourparlers précontractuels.

**Comment by cedric-anne** [comment]
Hi @cpasDav ,

#8283 should fix this issue (will require to re-enter affected passwords). Could you give us a feedback on this fix ?

Regards

**Comment by cpasDav** [comment]
Hi,

What's the best way to integrate the changes? 
Manually editing my source files?

**Comment by cedric-anne** [comment]
Hi,

You can get the patch from this URL (the PR URL with a `.patch` suffix) : https://github.com/glpi-project/glpi/pull/8283.patch

Then use the patch utility (i.e. `patch -p1 < 8283.patch` in the GLPI root folder). Patch may fail on `tests/*` files, this is not a problem.

Regards
