### ISSUE TITLE
notimportedemail empty itself

### ISSUE THREAD

**Issue by fralla2** [glpi-project/glpi#8297]
**Describe the bug**

When an email get rejected by mailcollectors, they appears in the front/notimportedemail.php interface. Few minutes later, the list get emptied and all the rejected emails disappears so we can't get to see what was causing the rejection.

It's like the table in the database get flushed by some function.

Not sure if the problem happened on earlier version because we were missing a column (users_id) in the glpi_notimportedemails table but since fixed, I see them getting added to the list/table but then, get flushed.

**Page(s) URL**

front/notimportedemail.php

**To reproduce**

Get an email denied for whatever reason (user don't exist, permissions, etc)
Go quickly to the front/notimportedemail.php page or in the database and see the email with the reason for refusal 
Go back to the same page or database later, the table is empty

**Expected behavior**

Emails not imported should stay present in the section

**Logs**

didn't see any error related to this in the logs

**Screenshots**

![001](https://user-images.githubusercontent.com/38400135/99585749-c15ece00-29b4-11eb-8800-13c4bb85f764.png)
![002](https://user-images.githubusercontent.com/38400135/99585751-c15ece00-29b4-11eb-96c0-798da3c60fdb.png)
![003](https://user-images.githubusercontent.com/38400135/99585752-c1f76480-29b4-11eb-942b-f6d192fea722.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]   GLPI 9.5.2 (/glpi => /var/www/html/glpi-9.5.2) Installation mode: TARBALL
--

Operating system: Linux glpi06 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 PHP 7.3.24 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sodium, sqlite3, 	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="8M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.24 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36 Server Software: Source distribution 	Server Version: 8.0.21 	Server SQL Mode:  	Parameters: REDACTED/glpi 	Host info: REDACTED via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (8.0.21) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/glpiData/config/ has been validated. Write access to /var/www/glpiData/files has been validated. Write access to /var/www/glpiData/files/_dumps has been validated. Write access to /var/www/glpiData/files/_sessions has been validated. Write access to /var/www/glpiData/files/_cron has been validated. Write access to /var/www/glpiData/files/_graphs has been validated. Write access to /var/www/glpiData/files/_lock has been validated. Write access to /var/www/glpiData/files/_plugins has been validated. Write access to /var/www/glpiData/files/_tmp has been validated. Write access to /var/www/glpiData/files/_cache has been validated. Write access to /var/www/glpiData/files/_rss has been validated. Write access to /var/www/glpiData/files/_uploads has been validated. Write access to /var/www/glpiData/files/_pictures has been validated. Write access to /var/www/html/glpi-9.5.2/marketplace has been validated. For security reasons, SELinux mode should be Enforcing.

GLPI_ROOT: /var/www/html/glpi-9.5.2 GLPI_CONFIG_DIR: /var/www/glpiData/config/ GLPI_VAR_DIR: /var/www/glpiData/files GLPI_LOG_DIR: /var/log/glpi GLPI_MARKETPLACE_DIR: /var/www/html/glpi-9.5.2/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/glpiData/files GLPI_CACHE_DIR: /var/www/glpiData/files/_cache GLPI_CRON_DIR: /var/www/glpiData/files/_cron GLPI_DUMP_DIR: /var/www/glpiData/files/_dumps GLPI_GRAPH_DIR: /var/www/glpiData/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/glpiData/files/_locales GLPI_LOCK_DIR: /var/www/glpiData/files/_lock GLPI_PICTURE_DIR: /var/www/glpiData/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/glpiData/files/_plugins GLPI_RSS_DIR: /var/www/glpiData/files/_rss GLPI_SESSION_DIR: /var/www/glpiData/files/_sessions GLPI_TMP_DIR: /var/www/glpiData/files/_tmp GLPI_UPLOAD_DIR: /var/www/glpiData/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi-9.5.2/locales GLPI_VERSION: 9.5.2 GLPI_SCHEMA_VERSION: 9.5.2 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi-9.5.2/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi-9.5.2/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.5 in (/var/www/html/glpi-9.5.2/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi-9.5.2/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi-9.5.2/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi-9.5.2/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi-9.5.2/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi-9.5.2/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi-9.5.2/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi-9.5.2/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi-9.5.2/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi-9.5.2/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi-9.5.2/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi-9.5.2/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi-9.5.2/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi-9.5.2/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi-9.5.2/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi-9.5.2/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi-9.5.2/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi-9.5.2/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi-9.5.2/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi-9.5.2/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi-9.5.2/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi-9.5.2/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi-9.5.2/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi-9.5.2/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi-9.5.2/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi-9.5.2/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi-9.5.2/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi-9.5.2/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi-9.5.2/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/pear)

Server: 'REDACTED', Port: '389', BaseDN: 'REDACTED', Connection filter: 		'(&(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=514))(!(userAccountControl:1.2.840.113556.1.4.803:=546))(!(userAccountControl:1.2.840.113556.1.4.803:=66050))(!(userAccountControl:1.2.840.113556.1.4.803:=66082)))(\|(samaccountname=e*)(samaccountname=m*)(samaccountname=o*)(samaccountname=t*)(samaccountname=*garde*)(samaccountname=ressources.materiell)))', 		RootDN: 'REDACTED', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@localhost)

Name: 'REDACTED' Active: Yes 	Server: '{outlook.office365.com/imap/ssl}' Login: 'REDACTED' Password: Yes Name: 'REDACTED' Active: Yes 	Server: '{outlook.office365.com/imap/ssl}' Login: 'REDACTED' Password: Yes Name: 'REDACTED' Active: No 	Server: '{outlook.office365.com/imap/ssl}' Login: 'REDACTED' Password: Yes Name: 'REDACTED' Active: Yes 	Server: '{outlook.office365.com/imap/ssl}' Login: 'REDACTED' Password: Yes Name: 'REDACTED' Active: Yes 	Server: '{outlook.office365.com/imap/ssl}' Login: 'REDACTED' Password: Yes Name: 'REDACTED' Active: Yes 	Server: '{outlook.office365.com/imap/ssl}' Login: 'REDACTED' Password: Yes Name: 'REDACTED' Active: Yes 	Server: '{outlook.office365.com/imap/ssl}' Login: 'REDACTED' Password: Yes

advancedplanning     Name: advancedplanning               Version: 0.2.0      State: Enabled 	treeview             Name: Arborescence                   Version: 1.9.0      State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.12.0     State: Enabled 	datainjection        Name: Data Injection                 Version: 2.8.1      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.10.4     State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	genericobject        Name: Gestion d'objets               Version: 2.9.1      State: Enabled 	order                Name: Gestion des commandes          Version: 2.6.0      State: Enabled 	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.4.0      State: Enabled 	manufacturersimports Name: Imports fabricants             Version: 2.3.0      State: Enabled 	jamf                 Name: Plugin Jamf pour GLPI          Version: 2.1.3      State: Enabled 	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Enabled
[/code]

**Comment by cedric-anne** [comment]
Hi,

In fact, it is not a bug. It has been done like that from the beginning (see https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/mailcollector.class.php#L705).

I never understood why it has been done like that. It is nearly impossible to find something in this table, especially if the collecting process is scheduled to be run at a high frequency.
IMHO, we should not completelly remove this cleaning process. Indeed, I think old entries should be cleaned (let's says entries older than 30 days), in order to be able to find usefull data here without risking to overload the database.

This improvement is not in our roadmap for now. If you want to sponsor this feature, feel free to contact your partner manager, or submit this form: https://portal.glpi-network.com/contact-us . You can also propose a pull request to implement this change.

Regards

**Comment by trasher** [comment]
I confirm this has been done that way since 0.83; and like Cédric, I have no idea why.

Original commit was: https://github.com/glpi-project/glpi/commit/895761af5f1cb9a4519e95149eb4c5ddca776547

**Comment by fralla2** [comment]
Thanks for the fast reply. That's a little odd because it defeats the purpose of this list since we can't really use it
Here we trigger the mailcollectors at each 2 min so I always saw that list empty.

I'll try to implement a fix like 30 days before cleaning on my side for our uses. If it works, I might submit it for review ;)

Thanks
Francois

**Comment by tsmr** [comment]
I have the same problem : email stay on notimported.php page & are refused next

I have to patch the mailcollector.class.php

```
diff --git a/inc/mailcollector.class.php b/inc/mailcollector.class.php
index 0c9c8f3ff3..220799c2c1 100644
--- a/inc/mailcollector.class.php
+++ b/inc/mailcollector.class.php
@@ -886,9 +886,11 @@ class MailCollector  extends CommonDBTM {
                   } else {
                      $rejinput['reason'] = NotImportedEmail::MATCH_NO_RULE;
                   }
-                  $refused++;
+                  //INFOTEL
+                  //$refused++;
                   $rejected->add($rejinput);
-                  $delete[$uid] =  self::REFUSED_FOLDER;
+                  //INFOTEL
+                  //$delete[$uid] =  self::REFUSED_FOLDER;
                }
 
                // Clean mail author used for notification settings
```

**Comment by SruiSan** [comment]
### Still relevant in recent versions – automatic cleanup makes the feature unusable

We are still observing this behavior today (GLPI 10.x):

* A rejected email **does appear briefly** in *Not imported emails* (`front/notimportedemail.php`).
* **Seconds or minutes later it disappears**, and the corresponding record is removed from `glpi_notimportedemails`.

This confirms what was already described in this issue: entries are **automatically deleted by design**, not by user configuration.

---

### Why this is a real problem

While this was previously classified as *not a bug*, the current behavior effectively **defeats the purpose of having a UI and a database table** for rejected emails:

* Administrators cannot reliably inspect why emails are rejected.
* With mailgate running frequently (every 1–2 minutes is common), the list is almost always empty.
* The feature exists in the interface, but is unusable in practice.

In real-world operations, this causes loss of traceability and makes troubleshooting mail issues unnecessarily difficult.

---

### Proposal (already suggested in this issue, still valid)

As already mentioned by @cedric-anne back in 2020, a **time-based cleanup** would make much more sense than an immediate purge.

Suggested approaches:

* Do **not delete entries immediately**.
* Integrate the cleanup into **automatic purge tasks**, like other GLPI data.
* Keep rejected emails for a configurable retention period, for example:

  * **30 days** (preferred)
  * or at least **15 or 10 days**

This would:

* preserve useful diagnostic information
* avoid database overload
* align this feature with other GLPI purge mechanisms

---

### Why this should be reconsidered now

* Mailgate usage has increased significantly.
* Email rejection debugging is critical in modern deployments (shared mailboxes, external senders, security rules).
* GLPI 10.x and later versions expose this UI, which creates an expectation that the data is actually usable.

At the moment, the near-instant cleanup removes most of the practical value of this feature.

---

### Summary

* The behavior described in this issue is **still reproducible today**.
* Immediate deletion of `glpi_notimportedemails` records makes the interface ineffective.
* A **retention-based cleanup (10–30 days)** would be a reasonable and low-risk improvement.

We believe it is worth reconsidering this enhancement, even if implemented incrementally.

Thanks for taking another look at this.

**Comment by trasher** [comment]
Please use suggestions website for RFEs.
