### ISSUE TITLE
Corrupt data when a migration fail

### ISSUE THREAD

**Issue by carlsonsantana** [glpi-project/glpi#8305]
**Describe the bug**

I was updating the GLPI version when a failure occurred, probably due to the size of the log table. So when I tried to perform the update again it was not possible, as the table had already been renamed.

**Page(s) URL**

<GLPI_BASE_URL>/glpi/install/install.php

**To reproduce**

1. Install a old version of GLPI
2. Download a new verson of GLPI
3. Go to installation page
4. Click on Update button, when the GLPI ask for Install or Update
5. While the GLPI is updating database, cancel the operation
6. Try to update the GLPI again
7. You see the error

**Expected behavior**

Only commit the changes (INSERTS, UPDATES, CREATE TABLES, RENAME TABLES, DELETE TABLES, etc) for database when no errors is detected for whole update of migration. If has failed, must undo the whole operation of migration on the database with rollback.

**Comment by trasher** [comment]
Well, that is a god idea, but this is not possible with MySQL; since some queries cannot be rolled back (see mysql docs about their auto-commited queries); so similar issues are going to happen; depending on what queries has been executed... Well; I'm not sure it would really solve the issue.

This kind of case is exactly why it's recommended to do a database backup by the way.

Pleas note that even if you were able to propose an alternative; we've recently talked about that, and we're not going to work on that, and more, any consequent changes on that part would be refused (there are lot of other issues to address and enhancements to work on before).
