### ISSUE TITLE
lightbox issues on tickets

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#8321]
on GLPI 9.5.x, lightbox was added for managing pictures in tickets timeline.
some issues we note:

- ticket recall (in lefttabs layout) doesn't have the lightbox effect
- i don't know if it's related to lightbox, but miniature in followup content is very small recently

@cconard96 do you replicate this ?

**Comment by cedric-anne** [comment]
Hi,

1. I noticed that sometimes lightbox effect is not available due to the fact that image is rendered using base64 src data, which means that image has not been imported correctly. I see this case with tickets created by FormCreator.

2. Miniature is small due to usage of `timeline` context in its src, maybe it can be enhanced.

**Comment by cconard96** [comment]
I've seen the second issue. The size is currently set to 100px wide in the stylesheet (.timeline_history .timeline_img_preview img).
