### ISSUE TITLE
Integrate GLPI with Apache Guacamole Remote Desktop

### ISSUE THREAD

**Issue by lexcorp** [glpi-project/glpi#8334]
Add support to integrate GLPI with Apache Guacamole Remote Desktop like this:

https://tic.gal/es/project/tviewer-soporte-remoto-glpi/

https://glpi.userecho.com/en/communities/1/topics/878-remote-desktop-integrating-apache-guacamole

We use Apache Guacamole Remote Desktop to solve most of the tickets remotely, consider possible to perform an integration of GLPI with Guacamole Remote Desktop.

Glpi could integrate the Apache Guacamole Remote Desktop Web API to visualize the equipment, and insert a button in the standard interface in the details of the ticket to request the remote connection, which will open the browser to view the remote computer.

https://guacamole.apache.org/api-documentation/

https://guacamole.apache.org/doc/gug/guacamole-common-js.html

In the administration page of glpi, we could insert the user / password and the necessary data for the management of Apache Guacamole Remote Desktop.

Apache Guacamole

https://guacamole.apache.org/

Apache Guacamole is a clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH.
We call it clientless because no plugins or client software are required. Thanks to HTML5, once Guacamole is installed on a server, all you need to access your desktops is a web browser.

![d65830533ba787eba92351823a506605](https://user-images.githubusercontent.com/5751288/100406468-864f4100-302b-11eb-86b7-0d7c6caa07df.png)
![827ca435fe77530f0a186987785e599c](https://user-images.githubusercontent.com/5751288/100406473-8b13f500-302b-11eb-8a49-a4dadcea6f69.png)

**Comment by cconard96** [comment]
My only qualm with this would be that is relies on a specific RDP/VNC/SSH server implementation. While Apache Guacamole looks like a great solution, it forces GLPI to directly support this specific implementation. I would much rather see this done as a plugin while GLPI provides the interface or abstraction needed for plugins which could integrate Apache Guacamole or any other solution.
It would be up to GLPI's team through an official plugin or up to the plugin community to handle the actual implementation.

Some businesses may want to use RDP/VNC/SSH directly while others may want an external source such as TeamViewer, LogMeIn, etc. For example, my employer is now responsible for supporting users who may be offsite without a proper VPN so we are using LogMeIn due to the current pandemic.

It's difficult to plan for the many possible implementations as long as there aren't any plugins that integrate these remote control services (at least none that I know of).

For now, I suggest upvoting the UserEcho thread and adding a comment on the thread if you know a plugin that already fulfills this role either through Apache Guacamole or another service.

**Comment by trasher** [comment]
Please use existing topic on suggestion website; there is no need to duplicate the request.

**Comment by lexcorp** [comment]
ngx-remote-desktop is an Angular component for connecting to a remote desktop using the guacamole remote desktop gateway

https://illgrenoble.github.io/ngx-remote-desktop/
