### ISSUE TITLE
Mailgate error

### ISSUE THREAD

**Issue by Dealtis-mcado** [glpi-project/glpi#8513]
hi

my glpi is in 9.5.1
i have a problem with a mailgate
when i transfert an email from my inbox to this mailgate, the mail is not imported, i have an error
![image](https://user-images.githubusercontent.com/69046138/104170365-4b4d7500-5401-11eb-824f-43eb112ad119.png)

the log in mailgate.log
Message invalide : 'dealtis.fr>e' is not a valid hostname for the email address<br/>
dealtis.fr is my domain name, i don't know there is >e after my domain

However, when i send an email directly, its ok
thanks

**Comment by trasher** [comment]
You should first try with last GLPI release. If problem is not solved, try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)) and see if you reproduce.

If the issue is not solved in latest nightly build, please provide a test email that we can use in our test suite; in EML format only.

**Comment by babouche91** [comment]
Hi, same issue here, ive got a mail stuck in the mailgate 

![Screenshot_20210113_073722](https://user-images.githubusercontent.com/76037788/104418809-cafd5000-5577-11eb-9a40-29e2384de877.png)

and mailgate.log:
Message invalide : 'hostnameXXX.fr>n' is not a valid hostname for the email address<br/>2021-01-13 07:34:02 [@myserveur.mydomain.fr]

**Comment by cedric-anne** [comment]
@ThierryLam 

This is a PHP bug, see https://github.com/php/php-src/issues/7980. It has been fixed in PHP 8.0.17/8.1.4.

**Comment by ThierryLam** [comment]
Hello,
I've found my problem : it was an issue regarding the self-service profile. It was not allowed to make followup on ticket.
Once I've modified the profile, the mail was correctly collected by the system.
Regards,
Thierry.
