### ISSUE TITLE
APCu for windows is not working

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#864]
Dear all,
APCu is not working in IIS FastCGI configuration/environment: see [APCu crashing on IIS 7.5](https://github.com/krakjoe/apcu/issues/67#issuecomment-164926913).
I think that we should not keep the advice for using APCu in GLPi as it is not usable everywhere!
Regards,
Tomolimo

**Comment by trasher** [comment]
Hello,

I do not agree to remove the advice.
The problem seems too specific; and is not really related to GLPi.

As long as activating APCu is a good idea on many cases, we can continue to advice using it.

Perhaps a solution would be to add an additionnal information saying that IIS users should not use apcu (or remove the advice if we can be sure instance is running on that particular webserver); at least until the bug will be fixed.

Anyways, I'm not running windows, I cannot test nor help with that.

**Comment by remicollet** [comment]
BTW, APCu 5.1.6 is expected in a few days, and should fix lot of pending issues (not really sure about Windows...)

**Comment by tomolimo** [comment]
Thank you, I'll test it.

**Comment by tomolimo** [comment]
Do you mean that `apcu_bc` will no longer be needed?

**Comment by remicollet** [comment]
apcu_bc is still needed, but it is mostly only function aliases, apcu if the really used extension.

**Comment by trasher** [comment]
I do not know if current APCu is now Windows compliant, but Remi has added ability to use other cache systems :)
