### ISSUE TITLE
[9.5.3] Wrong used email in created ticket from collector

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#8711]
Let me explain.
A user has 2 emails (one from the company, one personal)
He writes on the collector from his personal address.
The ticket is well created. 

Against the email that is referenced on the ticket, is that of the company and not the one with which he wrote.

I think the patch is to import the email too : 

```
diff --git a/inc/mailcollector.class.php b/inc/mailcollector.class.php
index 272ec0caa7..e08f604be5 100644
--- a/inc/mailcollector.class.php
+++ b/inc/mailcollector.class.php
@@ -1003,9 +1005,9 @@ class MailCollector  extends CommonDBTM {
       $tkt['_users_id_requester']                              = User::getOrImportByEmail($requester);
       $tkt["_users_id_requester_notif"]['use_notification'][0] = 1;
       // Set alternative email if user not found / used if anonymous mail creation is enable
-      if (!$tkt['_users_id_requester']) {
+//      if (!$tkt['_users_id_requester']) {
          $tkt["_users_id_requester_notif"]['alternative_email'][0] = $requester;
-      }
+//      }
 
       // Fix author of attachment
       // Move requester to author of followup
```

**Comment by cedric-anne** [comment]
Hi,

Please propose a PR and add a test case for this.

Regards

**Comment by andrepetinga** [comment]
Hello.
Yes, I can confirm this too.

I added my personal email as my secondary email.

I sent an email from that personal email and the ticket was created with my company email (the notification was sent to my company email too).

If I look at the "Email Followup" Tooltip, I can see my Company email and it should be the Personal one, since it was the one that originated the ticket.

Curious fact: If I press the "Email Followup" envelope, the email listed is the personal one! If I hit Save and send a followup, the notification is correctly sent to my personal email.

So it seems the bug is just on the ticket creation.

**Comment by tsmr** [comment]
OK i will try to make a PR
