### ISSUE TITLE
[9.5.3] Bug display statistics for tickets

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#8744]
Example :

Ticket opened :  05-02-2021 16:20
In history :
09-02-2021 13:36	XXXXX (55)	take into account date

![image](https://user-images.githubusercontent.com/13178158/109633670-a28ddd00-7b48-11eb-9e7d-b1072fca33cf.png)

So the take into account date must be  : 09-02-2021 13:36

The stats displays : 

![image](https://user-images.githubusercontent.com/13178158/109633578-88ec9580-7b48-11eb-93da-78e8ab5950da.png)

**Comment by cedric-anne** [comment]
Hi,

Indeed, this is a known issue. Problem is that time is store in seconds inside working time of related calendar. Dates should then be recomputed based on this calendar, but it may have changed between computation and display time.

Solution may be to store information with more details (i.e. list of periods like `[{"from":"2021-03-06 09:12:15", "to":"2021-03-06 18:00:00"}, {"from":"2021-03-07 07:00:00", "to":"2021-03-07 13:53:54"}]`), in order to be able to display correct value, even when reference calendar has been modified removed after these informations were saved.

Regards

**Comment by tsmr** [comment]
So you want a PR for this ?

**Comment by cedric-anne** [comment]
Hi,

Feel free to make a PR for this.

Regards
