### ISSUE TITLE
API config for Nginx

### ISSUE THREAD

**Issue by Elitius** [glpi-project/glpi#881]
Hi everyone.

I'm trying GLPI 0.91 RC2 but I have a problem with API and .htaccess.
I'm using Nginx so .htaccess is useless for me.
I can't use RewriteRule for Nginx, so if you can provide them, it will be great.

Thanks.

**Comment by tyronewyatt** [comment]
I came across your issue and since I use Nginx for pre-production I thought I chime in. 
GLPI's githib main page says that the web server prerequisites are Apache, Nginx and IIS.
Nginx doesn't use a .ntaccess or similar web config as per https://www.nginx.com/blog/converting-apache-to-nginx-rewrite-rules/. 
If unfamiliar with Nginx configs please refer to this guide and how achieve best practice https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
Can we please extend any Nginx config to include the other .htaccess in folders you wish to block access to such as ./files/.htaccess (deny from all).
Since I use IIS in production and we wish to start using the REST API I will create another issue for IIS and the creation of a web.config if there isn't one logged already.

**Comment by orthagh** [comment]
here is https://github.com/glpi-project/glpi/blob/master/apirest.md#nginx

Let me know if you have trouble with this config.

**Comment by Elitius** [comment]
Perfect, thanks ! ;)

**Comment by wertex** [comment]
Hello!
I made the settings as indicated in the link https://github.com/glpi-project/glpi/blob/master/apirest.md#nginx but when I go to http://path/to/glpi/api/ it gives me a 404 error that still e and where to check?
