### ISSUE TITLE
massive actions do not work properly

### ISSUE THREAD

**Issue by Rms78** [glpi-project/glpi#8994]
**Describe the bug**

When trying to perform massive actions, like trash sending multiple tickets or permanent removing user from bin, url http://glpi/front/massiveaction.php freezes. 
Going back results in no action performed. 

**Page(s) URL**
http://glpi.mydomain/front/massiveaction.php

**To reproduce**

1. Go to 'tickets' and select multiple tickets to perform massive action like send to bin
2. Click on 'actions->send to bin'
3. action never ends , get freeze
Same behavior when trying to permanent deletion of trash elements in users' bin to permanent elimination of a user. 

**Expected behavior**

action performed

**Logs**

```
paste logs here
451,SMTP server error: MAIL FROM command failed Detail: "Sending messages Ratio overload - must wait to send more"
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
[code]
 
GLPI 9.5.5 ( => /var/www/glpi)
Installation mode: TARBALL
```

**Additional context**

Could be related with problems in mail account for notifications, but, I think, if the mail account is having any trouble, actions in GLPI should be performed normally.

**Comment by cedric-anne** [comment]
Hi,

Notifications related to tickets are sent synchronously. It means that when you perform massive actions on ticket, many e-mails (notifications) may be sent during this action. Notifications related to tickets will be sent asynchronously in next major GLPI version, due to #8496, but this will not be applied on GLPI 9.5.x.

SMTP error should not block script execution, and massive action on users should not trigger mail sending synchronously. You should check your logs again, you should have more than just a SMTP error there.

Regards
