### ISSUE TITLE
Image size is wrong in processing ticket tab

### ISSUE THREAD

**Issue by nenes82** [glpi-project/glpi#9263]
Hello,
we have an issue when a ticket is create via an email.
There is 2 pictures, the first one is display but its size is of 1x4 px in the processing ticket tab!! In the ticket tab it's ok.
Processing tab (Picture is shown by the arrow)
![Window-2021-07-07 13_45_11](https://user-images.githubusercontent.com/48098839/124754426-805b0000-df2a-11eb-8add-708cb88584a5.jpg)

Ticket tab
![Window-2021-07-07 13_46_57](https://user-images.githubusercontent.com/48098839/124754472-8f41b280-df2a-11eb-961a-00901989099a.jpg)

eml file to reproduce the problem.
[hiddenimage.zip](https://github.com/glpi-project/glpi/files/6776885/hiddenimage.zip)

**To reproduce**

1. Send mail to glpi
2. Go to processing ticket tab

Regards

**Comment by cedric-anne** [comment]
Hi,

This is due to a conflict between GLPI and Outlook styles. If I disable some of them, image is correctly displayed:
![image](https://user-images.githubusercontent.com/33253653/125249478-90d9f480-e2f5-11eb-8630-ec45b24026ae.png)

Cleaning Outlook styles will not be done in GLPI, as it is too complex and may result in unwanted side effects.

Regards
