### ISSUE TITLE
No documents / no access after GLPI update.

### ISSUE THREAD

**Issue by IT-Garant-bis** [glpi-project/glpi#9658]
After upgrading the glpi database from 9.5.1 to 9.5.6, when opening **any** document, a "file not found" error occurs.
Also in the title of the page it says "GLPI - Access Denied".
Saw a similar issue when upgrading to 9.5.3.
Please help me solve the problem. 
![изображение](https://user-images.githubusercontent.com/86767053/135877378-667cdaef-7bd3-458e-852a-e3662db4d58c.png)
![изображение](https://user-images.githubusercontent.com/86767053/135877259-b2149e9f-c929-4b6a-8cbd-0f0fffad8570.png)

**Comment by cedric-anne** [comment]
Hi,

If there was a bug at this level, since 9.5.3 version, many GLPI administrators would have already warned us. If you need support you can open a topic on [community forums](https://forum.glpi-project.org/), or ask for professionnal support on [Glpi Network](https://services.glpi-network.com/).

I close this issue as only bugs are tracked here.

Regards

**Comment by IT-Garant-bis** [comment]
I repeated the experience with a clean install of 9.5.1 and an upgrade to 9.5.6 on another PC. The error persists. Doesn't work for you out of the box. I can record all the steps on video.

**Comment by cedric-anne** [comment]
Did you copied the `glpi/files` directory ?
